"""Compile one canonical camera channel into private flattened candidate storage."""
from __future__ import annotations
import argparse,importlib.util,re,sys
from pathlib import Path

FUNCTION="CompileCameraChannelCandidateV1"
TARGET='"/Script/Engine.BlueprintGeneratedClass\'/Game/Mods/ExileDroneDirector/Core/Client/BPC_EDD_ClientDirector.BPC_EDD_ClientDirector_C\'"'
CHANNELS=("focal_length_mm","aperture_fstop","focus_distance_cm","focus_influence","exposure_ev","bloom_weight","vignette_weight","color_grading_weight","tint_weight","motion_blur_weight","chromatic_aberration_weight","sharpening_weight","matte_weight")
GENERIC_INPUTS=(("CameraScalarTrackInputKeyTimesV1","real"),("CameraScalarTrackInputKeyValuesV1","real"),("CameraScalarTrackInputInterpolationModesV1","string"),("CameraScalarTrackInputArriveTangentsV1","real"),("CameraScalarTrackInputLeaveTangentsV1","real"))
COPIES=(("CameraScalarTrackCandidateKeyTimesV1","CameraChannelCandidateKeyTimesV1","real"),("CameraScalarTrackCandidateDomainValuesV1","CameraChannelCandidateDomainValuesV1","real"),("CameraScalarTrackCandidateInterpolationModesV1","CameraChannelCandidateInterpolationModesV1","string"),("CameraScalarTrackCandidateArriveTangentsV1","CameraChannelCandidateArriveTangentsV1","real"),("CameraScalarTrackCandidateLeaveTangentsV1","CameraChannelCandidateLeaveTangentsV1","real"))
def load(root):
 p=root/"tools/blueprint/Build-TrajectoryScalarEvaluatorGraphs.py";s=importlib.util.spec_from_file_location("edd_camera_channel_candidate_base",p);m=importlib.util.module_from_spec(s);sys.modules[s.name]=m;s.loader.exec_module(m);return m
def kind(n,p,k,array=False):
 cat,sub={"bool":("bool",""),"int":("int",""),"real":("real","double"),"string":("string","")}[k]
 def f(line):line=re.sub(r'PinType.PinCategory="[^"]*"',f'PinType.PinCategory="{cat}"',line,1);line=re.sub(r'PinType.PinSubCategory="[^"]*"',f'PinType.PinSubCategory="{sub}"',line,1);line=re.sub(r'PinType.PinSubCategoryObject=(?:None|"[^"]*")','PinType.PinSubCategoryObject=None',line,1);return re.sub(r'PinType.ContainerType=(?:None|Array)',f'PinType.ContainerType={"Array" if array else "None"}',line,1)
 n.mutate_pin(p,f)
def main():
 p=argparse.ArgumentParser();p.add_argument("--project-root",type=Path,required=True);p.add_argument("--output",type=Path,required=True);p.add_argument("--paste-output",type=Path);a=p.parse_args();s=load(a.project_root);bp=s.load_helpers(a.project_root);forms=s.load_templates(a.project_root,bp);b=s.Builder(bp,forms,FUNCTION)
 edit=bp.read_blocks(a.project_root/"tools/blueprint/templates/waypoint-edit-node-forms.eddgraph");play=bp.read_blocks(a.project_root/"tools/blueprint/snippets/update-linear-playback.eddgraph");capture=bp.read_blocks(a.project_root/"tools/blueprint/templates/waypoint-capture-node-forms.eddgraph");reset=bp.read_blocks(a.project_root/"tools/blueprint/snippets/reset-adaptive-arc-build-v1.eddgraph");loops=bp.read_blocks(a.project_root/"tools/blueprint/templates/adaptive-arc-forloop-node-form.eddgraph");sync=bp.read_blocks(a.project_root/"tools/blueprint/templates/waypoint-struct-sync-node-forms.eddgraph");find_graph=bp.read_blocks(a.project_root/"tools/blueprint/snippets/find-record-index-v1.eddgraph");public=bp.read_blocks(a.project_root/"tools/blueprint/live-snippets/list-public-v1.eddgraph");calls=bp.read_blocks(a.project_root/"tools/blueprint/snippets/activate-drone-view.eddgraph")
 template={"length":bp.find_block(edit,r'MemberName="Array_Length"'),"item":bp.find_block(play,r"^Begin Object Class=/Script/BlueprintGraph.K2Node_GetArrayItem"),"add":bp.find_block(capture,r'MemberName="Array_Add"'),"clear":bp.find_block(reset,r'MemberName="Array_Clear"'),"loop":bp.find_block(loops,r"StandardMacros:ForLoop"),"foreach":bp.find_block(sync,r"^Begin Object Class=/Script/BlueprintGraph.K2Node_MacroInstance"),"find":bp.find_block(find_graph,r'MemberName="Array_Find"'),"select":bp.find_block(public,r"^Begin Object Class=/Script/BlueprintGraph.K2Node_Select "),"call":bp.find_block(calls,r'MemberName="SwitchToDroneView"')}
 def addform(key,form,x,y):
  raw=template[form];m=bp.BLOCK_RE.match(raw);cls=m.group("class").rsplit(".",1)[-1];i=b.serial.get(cls,0);b.serial[cls]=i+1;n=bp.Node.clone(key,raw,f"{cls}_{i}",x,y);b.nodes.append(n);return n
 def var(n,name,k,array=False):s.retarget_variable(n,name,"real" if k=="int" else k);kind(n,name,k,array);kind(n,"Output_Get",k,array) if "Output_Get" in n.pins else None
 def get(name,k,x,y,array=False):n=b.add(f"get_{name}_{len(b.nodes)}","get",x,y);var(n,name,k,array);return n
 def setv(name,k,x,y,default=None):n=b.add(f"set_{name}_{len(b.nodes)}","set",x,y);var(n,name,k);s.set_default(n,name,default) if default is not None else None;return n
 def length(src,pin,k,x,y):n=addform(f"len_{pin}_{len(b.nodes)}","length",x,y);kind(n,"TargetArray",k,True);kind(n,"ReturnValue","int");bp.connect(src,pin,n,"TargetArray");return n
 def item(src,pin,k,index,indexpin,x,y):n=addform(f"item_{pin}_{len(b.nodes)}","item",x,y);kind(n,"Array",k,True);kind(n,"Output",k);bp.connect(src,pin,n,"Array");bp.connect(index,indexpin,n,"Dimension 1");return n
 def arrayop(form,src,pin,k,x,y,new=None,newpin=None):
  n=addform(f"{form}_{pin}_{len(b.nodes)}",form,x,y);kind(n,"TargetArray",k,True);bp.connect(src,pin,n,"TargetArray")
  if form=="add":kind(n,"NewItem",k);kind(n,"ReturnValue","int");bp.connect(new,newpin,n,"NewItem") if new is not None else s.set_default(n,"NewItem",newpin)
  return n
 def cmp(member,left,leftpin,x,y,right=None,rightpin=None,default=None,k="int"):
  n=b.add(f"cmp_{member}_{len(b.nodes)}","compare",x,y);s.retarget_function(n,member);kind(n,"A",k);kind(n,"B",k);kind(n,"ReturnValue","bool");bp.connect(left,leftpin,n,"A");bp.connect(right,rightpin,n,"B") if right is not None else s.set_default(n,"B",default);return n
 def math(member,left,leftpin,x,y,right=None,rightpin=None,default=None):
  n=b.math("Add_IntInt",x,y);s.retarget_function(n,member);[kind(n,pin,"int") for pin in ("A","B","ReturnValue")];bp.connect(left,leftpin,n,"A");bp.connect(right,rightpin,n,"B") if right is not None else s.set_default(n,"B",default);return n
 def select(condition,false_source,false_pin,true_source,true_pin,x,y,k,false_default=None,true_default=None):
  n=addform(f"select_{len(b.nodes)}","select",x,y);kind(n,"Index","bool");[kind(n,pin,k) for pin in ("Option 0","Option 1","ReturnValue")];bp.connect(condition,"ReturnValue",n,"Index")
  bp.connect(false_source,false_pin,n,"Option 0") if false_source is not None else s.set_default(n,"Option 0",false_default);bp.connect(true_source,true_pin,n,"Option 1") if true_source is not None else s.set_default(n,"Option 1",true_default);return n
 def call(name,x,y):
  n=addform(f"call_{name}_{len(b.nodes)}","call",x,y);n.text=re.sub(r"FunctionReference=\([^\n]*\)",f'FunctionReference=(MemberName="{name}",bSelfContext=True)',n.text,1);n.mutate_pin("self",lambda line:re.sub(r'PinType.PinSubCategoryObject="/Script/Engine.BlueprintGeneratedClass\'[^\']+\'"',f"PinType.PinSubCategoryObject={TARGET}",line,1));return n
 def find(src,pin,value,valuepin,x,y):n=addform(f"find_{len(b.nodes)}","find",x,y);kind(n,"TargetArray","string",True);kind(n,"ItemToFind","string");kind(n,"ReturnValue","int");bp.connect(src,pin,n,"TargetArray");bp.connect(value,valuepin,n,"ItemToFind");return n
 index=get("CameraChannelScratchChannelIndexV1","int",0,0);stage=get("CameraChannelScratchValidV1","bool",0,160);index_low=cmp("GreaterEqual_IntInt",index,"CameraChannelScratchChannelIndexV1",256,0,default="0");index_high=cmp("Less_IntInt",index,"CameraChannelScratchChannelIndexV1",256,160,default="13");both=cmp("BooleanAND",index_low,"ReturnValue",480,80,index_high,"ReturnValue",k="bool");ready=cmp("BooleanAND",stage,"CameraChannelScratchValidV1",704,80,both,"ReturnValue",k="bool");guard=b.add("guard","branch",928,3200);bp.connect(b.entry,"then",guard,"execute");bp.connect(ready,"ReturnValue",guard,"Condition")
 equal=[cmp("EqualEqual_IntInt",index,"CameraChannelScratchChannelIndexV1",0,480+i*112,default=str(i)) for i in range(13)]
 channel=None
 for i in reversed(range(12)):channel=select(equal[i],channel,"ReturnValue" if channel else None,None,None,288+i*208,480+i*112,"string",false_default=CHANNELS[-1] if channel is None else None,true_default=CHANNELS[i])
 default=None
 for i,value in reversed(((0,"35.0"),(1,"2.8"),(2,"1000.0"),(3,"1.0"))):default=select(equal[i],default,"ReturnValue" if default else None,None,None,288+i*208,2080+i*112,"real",false_default="0.0" if default is None else None,true_default=value)
 minimum=None
 for i,value in reversed(((0,"1.0"),(1,"0.1"),(2,"1.0"),(4,"-20.0"))):minimum=select(equal[i],minimum,"ReturnValue" if minimum else None,None,None,1344+i*208,2080+i*112,"real",false_default="0.0" if minimum is None else None,true_default=value)
 maximum=None
 for i,value in reversed(((0,"1000.0"),(1,"64.0"),(2,"1000000000.0"),(4,"20.0"))):maximum=select(equal[i],maximum,"ReturnValue" if maximum else None,None,None,2400+i*208,2080+i*112,"real",false_default="1.0" if maximum is None else None,true_default=value)
 ge_effect=cmp("GreaterEqual_IntInt",index,"CameraChannelScratchChannelIndexV1",3328,2080,default="5");clamp=cmp("BooleanOR",equal[3],"ReturnValue",3552,2080,ge_effect,"ReturnValue",k="bool")
 generic={name:get(name,k,0,3520+i*144,True) for i,(name,k) in enumerate(GENERIC_INPUTS)};clears=[arrayop("clear",generic[name],name,k,1152+i*224,3200) for i,(name,k) in enumerate(GENERIC_INPUTS)];duration=get("CameraChannelInputDurationV1","real",0,2800);policies=(("CameraScalarTrackInputDurationV1","real",duration,"CameraChannelInputDurationV1"),("CameraScalarTrackInputHasMinimumV1","bool",None,"true"),("CameraScalarTrackInputMinimumV1","real",minimum,"ReturnValue"),("CameraScalarTrackInputHasMaximumV1","bool",None,"true"),("CameraScalarTrackInputMaximumV1","real",maximum,"ReturnValue"),("CameraScalarTrackInputClampOutputV1","bool",clamp,"ReturnValue"));sets=[]
 for i,(name,k,source,pin) in enumerate(policies):
  n=setv(name,k,2272+i*224,3200,"true" if source is None else None);bp.connect(source,pin,n,name) if source is not None else None;sets.append(n)
 chain=[*clears,*sets];bp.connect(guard,"then",chain[0],"execute");[bp.connect(left,"then",right,"execute") for left,right in zip(chain,chain[1:])]
 input_ids=get("CameraChannelInputChannelIdsV1","string",0,4320,True);found=find(input_ids,"CameraChannelInputChannelIdsV1",channel,"ReturnValue",3648,3200);is_found=cmp("GreaterEqual_IntInt",found,"ReturnValue",3872,2880,default="0");found_branch=b.add("found_branch","branch",4096,3200);bp.connect(chain[-1],"then",found_branch,"execute");bp.connect(is_found,"ReturnValue",found_branch,"Condition")
 offsets=get("CameraChannelInputKeyOffsetsV1","int",0,4480,True);counts=get("CameraChannelInputKeyCountsV1","int",0,4640,True);domains=get("CameraChannelInputDomainsV1","string",0,4800,True);offset=item(offsets,"CameraChannelInputKeyOffsetsV1","int",found,"ReturnValue",4320,2400);count=item(counts,"CameraChannelInputKeyCountsV1","int",found,"ReturnValue",4320,2560);domain=item(domains,"CameraChannelInputDomainsV1","string",found,"ReturnValue",4320,2720);set_domain=setv("CameraScalarTrackInputDomainV1","string",4320,3200);bp.connect(domain,"Output",set_domain,"CameraScalarTrackInputDomainV1");bp.connect(found_branch,"then",set_domain,"execute")
 last=math("Subtract_IntInt",count,"Output",4544,2560,default="1");auth_loop=addform("auth_loop","loop",4768,3200);s.set_default(auth_loop,"FirstIndex","0");bp.connect(last,"ReturnValue",auth_loop,"LastIndex");bp.connect(set_domain,"then",auth_loop,"execute");flat=math("Add_IntInt",offset,"Output",4992,2400,auth_loop,"Index");input_sources={name:get(name,k,0,5040+i*144,True) for i,(name,k) in enumerate((("CameraChannelInputKeyTimesV1","real"),("CameraChannelInputKeyValuesV1","real"),("CameraChannelInputArriveTangentsV1","real"),("CameraChannelInputLeaveTangentsV1","real"),("CameraChannelInputInterpolationModesV1","string")))};auth_adds=[]
 for i,(source,target,k) in enumerate((("CameraChannelInputKeyTimesV1","CameraScalarTrackInputKeyTimesV1","real"),("CameraChannelInputKeyValuesV1","CameraScalarTrackInputKeyValuesV1","real"),("CameraChannelInputArriveTangentsV1","CameraScalarTrackInputArriveTangentsV1","real"),("CameraChannelInputLeaveTangentsV1","CameraScalarTrackInputLeaveTangentsV1","real"))):
  value=item(input_sources[source],source,k,flat,"ReturnValue",5216+i*224,2400);auth_adds.append(arrayop("add",generic[target],target,k,5216+i*224,3200,value,"Output"))
 bp.connect(auth_loop,"LoopBody",auth_adds[0],"execute");[bp.connect(left,"then",right,"execute") for left,right in zip(auth_adds,auth_adds[1:])];one=math("Subtract_IntInt",count,"Output",5888,2720,default="1");not_last=cmp("Less_IntInt",auth_loop,"Index",6112,2720,one,"ReturnValue");mode_branch=b.add("mode_branch","branch",6336,3200);bp.connect(auth_adds[-1],"then",mode_branch,"execute");bp.connect(not_last,"ReturnValue",mode_branch,"Condition");mode_base=math("Subtract_IntInt",offset,"Output",6336,2560,found,"ReturnValue");mode_index=math("Add_IntInt",mode_base,"ReturnValue",6560,2560,auth_loop,"Index");mode=item(input_sources["CameraChannelInputInterpolationModesV1"],"CameraChannelInputInterpolationModesV1","string",mode_index,"ReturnValue",6784,2560);mode_add=arrayop("add",generic["CameraScalarTrackInputInterpolationModesV1"],"CameraScalarTrackInputInterpolationModesV1","string",7008,3200,mode,"Output");bp.connect(mode_branch,"then",mode_add,"execute")
 auth_call=call("CompileCameraScalarTrackV1",7232,3200);bp.connect(auth_loop,"Completed",auth_call,"execute")
 default_domain=setv("CameraScalarTrackInputDomainV1","string",4320,3520,"linear");bp.connect(found_branch,"else",default_domain,"execute");positive=cmp("Greater_DoubleDouble",duration,"CameraChannelInputDurationV1",4544,3520,default="0.0",k="real");duration_branch=b.add("duration_branch","branch",4768,3520);bp.connect(default_domain,"then",duration_branch,"execute");bp.connect(positive,"ReturnValue",duration_branch,"Condition")
 def default_path(prefix,start_x,y,positive_duration):
  ops=[]
  ops.append(arrayop("add",generic["CameraScalarTrackInputKeyTimesV1"],"CameraScalarTrackInputKeyTimesV1","real",start_x,y,newpin="0.0"))
  if positive_duration:ops.append(arrayop("add",generic["CameraScalarTrackInputKeyTimesV1"],"CameraScalarTrackInputKeyTimesV1","real",start_x+224,y,duration,"CameraChannelInputDurationV1"))
  ops.append(arrayop("add",generic["CameraScalarTrackInputKeyValuesV1"],"CameraScalarTrackInputKeyValuesV1","real",start_x+len(ops)*224,y,default,"ReturnValue"))
  if positive_duration:ops.append(arrayop("add",generic["CameraScalarTrackInputKeyValuesV1"],"CameraScalarTrackInputKeyValuesV1","real",start_x+len(ops)*224,y,default,"ReturnValue"))
  for target in ("CameraScalarTrackInputArriveTangentsV1","CameraScalarTrackInputLeaveTangentsV1"):
   ops.append(arrayop("add",generic[target],target,"real",start_x+len(ops)*224,y,newpin="0.0"))
   if positive_duration:ops.append(arrayop("add",generic[target],target,"real",start_x+len(ops)*224,y,newpin="0.0"))
  if positive_duration:ops.append(arrayop("add",generic["CameraScalarTrackInputInterpolationModesV1"],"CameraScalarTrackInputInterpolationModesV1","string",start_x+len(ops)*224,y,newpin="linear"))
  call_node=call("CompileCameraScalarTrackV1",start_x+len(ops)*224,y);[bp.connect(left,"then",right,"execute") for left,right in zip(ops,[*ops[1:],call_node])];return ops[0],call_node
 positive_first,positive_call=default_path("positive",4992,3520,True);zero_first,zero_call=default_path("zero",4992,3840,False);bp.connect(duration_branch,"then",positive_first,"execute");bp.connect(duration_branch,"else",zero_first,"execute")
 candidate_targets={name:get(name,k,0,5920+i*144,True) for name,k in (("CameraChannelCandidateKeyOffsetsV1","int"),("CameraChannelCandidateKeyCountsV1","int"),("CameraChannelCandidateKeyTimesV1","real"),("CameraChannelCandidateDomainValuesV1","real"),("CameraChannelCandidateInterpolationModesV1","string"),("CameraChannelCandidateArriveTangentsV1","real"),("CameraChannelCandidateLeaveTangentsV1","real"),("CameraChannelCandidateDomainsV1","string"))};generic_candidates={source:get(source,k,0,7200+i*144,True) for i,(source,_target,k) in enumerate(COPIES)};generic_valid=get("CameraScalarTrackCompileValidV1","bool",0,8000);generic_domain=get("CameraScalarTrackInputDomainV1","string",0,8160)
 def copy_after(call_node,prefix,x0,y0):
  branch=b.add(f"{prefix}_compiled_branch","branch",x0,y0);bp.connect(call_node,"then",branch,"execute");bp.connect(generic_valid,"CameraScalarTrackCompileValidV1",branch,"Condition");fail=setv("CameraChannelScratchValidV1","bool",x0+224,y0+160,"false");failure=setv("CameraChannelFailureCodeV1","string",x0+448,y0+160,"channel_compile_failed");bp.connect(branch,"else",fail,"execute");bp.connect(fail,"then",failure,"execute")
  prior_len=length(candidate_targets["CameraChannelCandidateKeyTimesV1"],"CameraChannelCandidateKeyTimesV1","real",x0,y0-480);track_len=length(generic_candidates["CameraScalarTrackCandidateKeyTimesV1"],"CameraScalarTrackCandidateKeyTimesV1","real",x0+224,y0-480);add_offset=arrayop("add",candidate_targets["CameraChannelCandidateKeyOffsetsV1"],"CameraChannelCandidateKeyOffsetsV1","int",x0+224,y0,prior_len,"ReturnValue");add_count=arrayop("add",candidate_targets["CameraChannelCandidateKeyCountsV1"],"CameraChannelCandidateKeyCountsV1","int",x0+448,y0,track_len,"ReturnValue");bp.connect(branch,"then",add_offset,"execute");bp.connect(add_offset,"then",add_count,"execute");previous=add_count
  for j,(source,target,k) in enumerate(COPIES):
   loop=addform(f"{prefix}_copy_{j}","foreach",x0+672+j*448,y0);kind(loop,"Array",k,True);kind(loop,"Array Element",k);kind(loop,"Array Index","int");bp.connect(generic_candidates[source],source,loop,"Array");bp.connect(previous,"then" if j==0 else "Completed",loop,"Exec");add=arrayop("add",candidate_targets[target],target,k,x0+896+j*448,y0,loop,"Array Element");bp.connect(loop,"LoopBody",add,"execute");previous=loop
  add_domain=arrayop("add",candidate_targets["CameraChannelCandidateDomainsV1"],"CameraChannelCandidateDomainsV1","string",x0+3136,y0,generic_domain,"CameraScalarTrackInputDomainV1");bp.connect(previous,"Completed",add_domain,"execute");return add_domain
 copy_after(auth_call,"auth",7488,3200);copy_after(positive_call,"positive",7488,4320);copy_after(zero_call,"zero",7488,5440)
 full="\n".join(n.text for n in b.nodes)+"\n";a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(full,encoding="utf-8")
 if a.paste_output:a.paste_output.parent.mkdir(parents=True,exist_ok=True);a.paste_output.write_text("\n".join(re.sub(r',LinkedTo=\(K2Node_FunctionEntry_0 [0-9A-F]{32},\)',"",n.text) for n in b.nodes[1:])+"\n",encoding="utf-8")
if __name__=="__main__":main()
