"""Build the first absolute-time linear playback Blueprint functions.

The generated evaluator traverses every captured transform with one fixed
duration per segment.  Position and quaternion rotation are derived from
absolute game time, never integrated from the previous frame.
"""

from __future__ import annotations

import argparse
import importlib.util
import re
import sys
from pathlib import Path


ENTRY_PIN_IDS = {
    "StartLinearPlayback": "FC0C8A964A8862D3DBF92085F481DC5E",
    "UpdateLinearPlayback": "5FC3F7CF4F95F5365B2BE8925BFB9606",
    "StopLinearPlayback": "C5A53E2845C95E562903858D95765858",
}
SELECTED_INDEX_GUID = "23B9561944904F583A9AAE8770F8810B"


def load_builder(project_root: Path):
    path = project_root / "tools" / "blueprint" / "Build-WaypointCaptureGraph.py"
    spec = importlib.util.spec_from_file_location("edd_playback_graph_base", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load shared graph builder: {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def set_default(bp, node, pin_name: str, value: str) -> None:
    def mutate(line: str) -> str:
        if "DefaultValue=" in line:
            line = re.sub(r'(?<!Autogenerated)DefaultValue="[^"]*"', f'DefaultValue="{value}"', line, count=1)
        else:
            line = line.replace(",PersistentGuid=", f',DefaultValue="{value}",PersistentGuid=', 1)
        return line

    node.mutate_pin(pin_name, mutate)


def set_transform_array_get(node) -> None:
    def transform_pin(line: str) -> str:
        line = line.replace('PinType.PinCategory="wildcard"', 'PinType.PinCategory="struct"', 1)
        return line.replace(
            "PinType.PinSubCategoryObject=None",
            "PinType.PinSubCategoryObject=\"/Script/CoreUObject.ScriptStruct'"
            "/Script/CoreUObject.Transform'\"",
            1,
        )

    node.mutate_pin("Array", transform_pin)
    node.mutate_pin("Output", transform_pin)


def retarget_entry(node, function_name: str) -> None:
    node.text = re.sub(
        r'FunctionReference=\(MemberName="[^"]+"\)',
        f'FunctionReference=(MemberName="{function_name}")',
        node.text,
        count=1,
    )
    old_pin_id = node.pins["then"]
    new_pin_id = ENTRY_PIN_IDS[function_name]
    node.text = node.text.replace(f"PinId={old_pin_id}", f"PinId={new_pin_id}", 1)
    node.pins["then"] = new_pin_id


def retarget_selected(bp, node) -> None:
    bp.retarget_variable(
        node,
        "PlaybackStartTimeSeconds",
        "SelectedWaypointIndex",
        SELECTED_INDEX_GUID,
    )
    node.text = node.text.replace('PinType.PinCategory="real"', 'PinType.PinCategory="int"')
    node.text = node.text.replace('PinType.PinSubCategory="double"', 'PinType.PinSubCategory=""')
    node.text = node.text.replace('DefaultValue="0.0"', 'DefaultValue="0"')
    node.text = node.text.replace('AutogeneratedDefaultValue="0.0"', 'AutogeneratedDefaultValue="0"')


def templates(bp, project_root: Path) -> dict[str, str]:
    root = project_root / "tools" / "blueprint"
    playback = bp.read_blocks(root / "templates" / "linear-playback-node-forms.eddgraph")
    capture = bp.read_blocks(root / "templates" / "waypoint-capture-node-forms.eddgraph")
    edit = bp.read_blocks(root / "templates" / "waypoint-edit-node-forms.eddgraph")
    enter = bp.read_blocks(root / "snippets" / "enter-drone-mode.eddgraph")
    return {
        "entry": bp.find_block(capture, r"K2Node_FunctionEntry"),
        "time": bp.find_block(playback, r'MemberName="GetGameTimeInSeconds"'),
        "sub_double": bp.find_block(playback, r'MemberName="Subtract_DoubleDouble"'),
        "div_double": bp.find_block(playback, r'MemberName="Divide_DoubleDouble"'),
        "mul_double": bp.find_block(playback, r'MemberName="Multiply_DoubleDouble"'),
        "int_to_double": bp.find_block(playback, r'MemberName="Conv_IntToDouble"'),
        "floor": bp.find_block(playback, r'MemberName="FFloor"'),
        "add_int": bp.find_block(playback, r'MemberName="Add_IntInt"'),
        "sub_int": bp.find_block(playback, r'MemberName="Subtract_IntInt"'),
        "ge_double": bp.find_block(playback, r'MemberName="GreaterEqual_DoubleDouble"'),
        "ge_int": bp.find_block(playback, r'MemberName="GreaterEqual_IntInt"'),
        "tlerp": bp.find_block(playback, r'MemberName="TLerp"'),
        "set_transform": bp.find_block(playback, r'MemberName="K2_SetActorTransform"'),
        "print": bp.find_block(playback, r'MemberName="PrintString"'),
        "active_get": bp.find_block(playback, r'K2Node_VariableGet.*?MemberName="PlaybackActive"'),
        "active_set": bp.find_block(playback, r'K2Node_VariableSet.*?MemberName="PlaybackActive"'),
        "start_get": bp.find_block(playback, r'K2Node_VariableGet.*?MemberName="PlaybackStartTimeSeconds"'),
        "start_set": bp.find_block(playback, r'K2Node_VariableSet.*?MemberName="PlaybackStartTimeSeconds"'),
        "duration_get": bp.find_block(playback, r'MemberName="PlaybackSecondsPerSegment"'),
        "array_get": bp.find_block(playback, r"K2Node_GetArrayItem"),
        "transforms": bp.find_block(capture, r'MemberName="DraftWaypointTransforms"'),
        "drone": bp.find_block(capture, r'MemberName="DroneCameraRef"'),
        "length": bp.find_block(edit, r'MemberName="Array_Length"'),
        "branch": bp.find_block(
            enter,
            r"^Begin Object Class=/Script/BlueprintGraph\.K2Node_IfThenElse\b",
        ),
        "valid": bp.find_block(enter, r'MemberName="IsValid"'),
    }


def graph_builder(bp, graph_name: str, source: dict[str, str]):
    bp.TARGET_GRAPH = graph_name
    nodes = {}

    def add(key: str, template: str, name: str, x: int, y: int):
        node = bp.Node.clone(key, source[template], name, x, y)
        nodes[key] = node
        return node

    return nodes, add


def build_start(bp, source):
    graph = "StartLinearPlayback"
    nodes, add = graph_builder(bp, graph, source)
    entry = add("entry", "entry", "K2Node_FunctionEntry_0", 0, 0)
    retarget_entry(entry, graph)
    transforms = add("transforms", "transforms", "K2Node_VariableGet_0", 0, 304)
    length = add("length", "length", "K2Node_CallArrayFunction_0", 224, 304)
    count_ge = add("count_ge", "ge_int", "K2Node_CallFunction_0", 448, 304)
    set_default(bp, count_ge, "B", "2")
    count_branch = add("count_branch", "branch", "K2Node_IfThenElse_0", 672, 0)
    duration = add("duration", "duration_get", "K2Node_VariableGet_1", 672, 304)
    duration_ge = add("duration_ge", "ge_double", "K2Node_CallFunction_1", 896, 304)
    set_default(bp, duration_ge, "B", "0.001")
    duration_branch = add("duration_branch", "branch", "K2Node_IfThenElse_1", 1120, 0)
    drone = add("drone", "drone", "K2Node_VariableGet_2", 1120, 304)
    valid = add("valid", "valid", "K2Node_CallFunction_2", 1344, 304)
    camera_branch = add("camera_branch", "branch", "K2Node_IfThenElse_2", 1568, 0)
    time = add("time", "time", "K2Node_CallFunction_3", 1568, 304)
    start_set = add("start_set", "start_set", "K2Node_VariableSet_0", 1792, 0)
    first = add("first", "array_get", "K2Node_GetArrayItem_0", 1792, 304)
    set_transform = add("set_transform", "set_transform", "K2Node_CallFunction_4", 2048, 0)
    set_transform_array_get(first)
    set_default(bp, set_transform, "bTeleport", "true")
    active_set = add("active_set", "active_set", "K2Node_VariableSet_1", 2304, 0)
    set_default(bp, active_set, "PlaybackActive", "true")
    print_node = add("print", "print", "K2Node_CallFunction_5", 2560, 0)
    set_default(bp, print_node, "InString", "[EDD] Linear playback started")

    bp.connect(entry, "then", count_branch, "execute")
    bp.connect(transforms, "DraftWaypointTransforms", length, "TargetArray")
    bp.connect(length, "ReturnValue", count_ge, "A")
    bp.connect(count_ge, "ReturnValue", count_branch, "Condition")
    bp.connect(count_branch, "then", duration_branch, "execute")
    bp.connect(duration, "PlaybackSecondsPerSegment", duration_ge, "A")
    bp.connect(duration_ge, "ReturnValue", duration_branch, "Condition")
    bp.connect(duration_branch, "then", camera_branch, "execute")
    bp.connect(drone, "DroneCameraRef", valid, "Object")
    bp.connect(valid, "ReturnValue", camera_branch, "Condition")
    bp.connect(camera_branch, "then", start_set, "execute")
    bp.connect(time, "ReturnValue", start_set, "PlaybackStartTimeSeconds")
    bp.connect(start_set, "then", set_transform, "execute")
    bp.connect(transforms, "DraftWaypointTransforms", first, "Array")
    bp.connect(first, "Output", set_transform, "NewTransform")
    bp.connect(drone, "DroneCameraRef", set_transform, "self")
    bp.connect(set_transform, "then", active_set, "execute")
    bp.connect(active_set, "then", print_node, "execute")
    return list(nodes.values())


def build_stop(bp, source):
    graph = "StopLinearPlayback"
    nodes, add = graph_builder(bp, graph, source)
    entry = add("entry", "entry", "K2Node_FunctionEntry_0", 0, 0)
    retarget_entry(entry, graph)
    active_set = add("active_set", "active_set", "K2Node_VariableSet_0", 256, 0)
    set_default(bp, active_set, "PlaybackActive", "false")
    print_node = add("print", "print", "K2Node_CallFunction_0", 512, 0)
    set_default(bp, print_node, "InString", "[EDD] Linear playback stopped")
    bp.connect(entry, "then", active_set, "execute")
    bp.connect(active_set, "then", print_node, "execute")
    return list(nodes.values())


def build_update(bp, source):
    graph = "UpdateLinearPlayback"
    nodes, add = graph_builder(bp, graph, source)
    entry = add("entry", "entry", "K2Node_FunctionEntry_0", 0, 0)
    retarget_entry(entry, graph)
    active = add("active", "active_get", "K2Node_VariableGet_0", 0, 304)
    active_branch = add("active_branch", "branch", "K2Node_IfThenElse_0", 224, 0)
    drone = add("drone", "drone", "K2Node_VariableGet_1", 224, 304)
    valid = add("valid", "valid", "K2Node_CallFunction_0", 448, 304)
    camera_branch = add("camera_branch", "branch", "K2Node_IfThenElse_1", 672, 0)
    transforms = add("transforms", "transforms", "K2Node_VariableGet_2", 672, 304)
    length = add("length", "length", "K2Node_CallArrayFunction_0", 896, 304)
    count_ge = add("count_ge", "ge_int", "K2Node_CallFunction_1", 1120, 304)
    set_default(bp, count_ge, "B", "2")
    count_branch = add("count_branch", "branch", "K2Node_IfThenElse_2", 1344, 0)
    duration = add("duration", "duration_get", "K2Node_VariableGet_3", 1344, 304)
    duration_ge = add("duration_ge", "ge_double", "K2Node_CallFunction_2", 1568, 304)
    set_default(bp, duration_ge, "B", "0.001")
    duration_branch = add("duration_branch", "branch", "K2Node_IfThenElse_3", 1792, 0)

    now = add("now", "time", "K2Node_CallFunction_3", 1792, 304)
    start = add("start", "start_get", "K2Node_VariableGet_4", 1792, 400)
    elapsed = add("elapsed", "sub_double", "K2Node_CallFunction_4", 2016, 304)
    segment_count = add("segment_count", "sub_int", "K2Node_CallFunction_5", 2016, 464)
    set_default(bp, segment_count, "B", "1")
    count_double = add("count_double", "int_to_double", "K2Node_CallFunction_6", 2240, 464)
    total = add("total", "mul_double", "K2Node_CallFunction_7", 2464, 464)
    complete_ge = add("complete_ge", "ge_double", "K2Node_CallFunction_8", 2688, 304)
    complete_branch = add("complete_branch", "branch", "K2Node_IfThenElse_4", 2912, 0)

    last = add("last", "array_get", "K2Node_GetArrayItem_0", 2912, 464)
    set_transform_array_get(last)
    set_last = add("set_last", "set_transform", "K2Node_CallFunction_9", 3168, -128)
    set_default(bp, set_last, "bTeleport", "true")
    selected_last = add("selected_last", "start_set", "K2Node_VariableSet_0", 3424, -128)
    retarget_selected(bp, selected_last)
    segment_time = add("segment_time", "div_double", "K2Node_CallFunction_11", 2912, 656)
    floor_node = add("floor", "floor", "K2Node_CallFunction_12", 3136, 656)
    index_double = add("index_double", "int_to_double", "K2Node_CallFunction_13", 3360, 656)
    alpha = add("alpha", "sub_double", "K2Node_CallFunction_14", 3584, 656)
    next_index = add("next_index", "add_int", "K2Node_CallFunction_15", 3360, 816)
    set_default(bp, next_index, "B", "1")
    first = add("first", "array_get", "K2Node_GetArrayItem_1", 3808, 496)
    second = add("second", "array_get", "K2Node_GetArrayItem_2", 3808, 752)
    set_transform_array_get(first)
    set_transform_array_get(second)
    tlerp = add("tlerp", "tlerp", "K2Node_CallFunction_16", 4064, 624)
    set_transform = add("set_transform", "set_transform", "K2Node_CallFunction_17", 4320, 128)
    set_default(bp, set_transform, "bTeleport", "true")
    selected_segment = add("selected_segment", "start_set", "K2Node_VariableSet_2", 4576, 128)
    retarget_selected(bp, selected_segment)

    bp.connect(entry, "then", active_branch, "execute")
    bp.connect(active, "PlaybackActive", active_branch, "Condition")
    bp.connect(active_branch, "then", camera_branch, "execute")
    bp.connect(drone, "DroneCameraRef", valid, "Object")
    bp.connect(valid, "ReturnValue", camera_branch, "Condition")
    bp.connect(camera_branch, "then", count_branch, "execute")
    bp.connect(transforms, "DraftWaypointTransforms", length, "TargetArray")
    bp.connect(length, "ReturnValue", count_ge, "A")
    bp.connect(count_ge, "ReturnValue", count_branch, "Condition")
    bp.connect(count_branch, "then", duration_branch, "execute")
    bp.connect(duration, "PlaybackSecondsPerSegment", duration_ge, "A")
    bp.connect(duration_ge, "ReturnValue", duration_branch, "Condition")
    bp.connect(duration_branch, "then", complete_branch, "execute")

    bp.connect(now, "ReturnValue", elapsed, "A")
    bp.connect(start, "PlaybackStartTimeSeconds", elapsed, "B")
    bp.connect(length, "ReturnValue", segment_count, "A")
    bp.connect(segment_count, "ReturnValue", count_double, "InInt")
    bp.connect(count_double, "ReturnValue", total, "A")
    bp.connect(duration, "PlaybackSecondsPerSegment", total, "B")
    bp.connect(elapsed, "ReturnValue", complete_ge, "A")
    bp.connect(total, "ReturnValue", complete_ge, "B")
    bp.connect(complete_ge, "ReturnValue", complete_branch, "Condition")

    bp.connect(complete_branch, "then", set_last, "execute")
    bp.connect(transforms, "DraftWaypointTransforms", last, "Array")
    bp.connect(segment_count, "ReturnValue", last, "Dimension 1")
    bp.connect(last, "Output", set_last, "NewTransform")
    bp.connect(drone, "DroneCameraRef", set_last, "self")
    bp.connect(set_last, "then", selected_last, "execute")
    bp.connect(segment_count, "ReturnValue", selected_last, "SelectedWaypointIndex")

    bp.connect(complete_branch, "else", set_transform, "execute")
    bp.connect(elapsed, "ReturnValue", segment_time, "A")
    bp.connect(duration, "PlaybackSecondsPerSegment", segment_time, "B")
    bp.connect(segment_time, "ReturnValue", floor_node, "A")
    bp.connect(floor_node, "ReturnValue", index_double, "InInt")
    bp.connect(segment_time, "ReturnValue", alpha, "A")
    bp.connect(index_double, "ReturnValue", alpha, "B")
    bp.connect(floor_node, "ReturnValue", next_index, "A")
    bp.connect(transforms, "DraftWaypointTransforms", first, "Array")
    bp.connect(transforms, "DraftWaypointTransforms", second, "Array")
    bp.connect(floor_node, "ReturnValue", first, "Dimension 1")
    bp.connect(next_index, "ReturnValue", second, "Dimension 1")
    bp.connect(first, "Output", tlerp, "A")
    bp.connect(second, "Output", tlerp, "B")
    bp.connect(alpha, "ReturnValue", tlerp, "Alpha")
    bp.connect(tlerp, "ReturnValue", set_transform, "NewTransform")
    bp.connect(drone, "DroneCameraRef", set_transform, "self")
    bp.connect(set_transform, "then", selected_segment, "execute")
    bp.connect(floor_node, "ReturnValue", selected_segment, "SelectedWaypointIndex")
    return list(nodes.values())


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-root", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--paste-dir", type=Path)
    args = parser.parse_args()
    bp = load_builder(args.project_root)
    source = templates(bp, args.project_root)
    update_nodes = build_update(bp, source)
    for node in update_nodes:
        node.text = re.sub(
            r"NodePosX=(-?\d+)",
            lambda match: f"NodePosX={int(int(match.group(1)) * 0.5)}",
            node.text,
            count=1,
        )
    products = {
        "start-linear-playback.eddgraph": build_start(bp, source),
        "update-linear-playback.eddgraph": update_nodes,
        "stop-linear-playback.eddgraph": build_stop(bp, source),
    }
    args.output_dir.mkdir(parents=True, exist_ok=True)
    if args.paste_dir:
        args.paste_dir.mkdir(parents=True, exist_ok=True)
    for filename, nodes in products.items():
        (args.output_dir / filename).write_text(
            "\n".join(node.text for node in nodes) + "\n",
            encoding="utf-8",
        )
        if args.paste_dir:
            (args.paste_dir / filename).write_text(
                "\n".join(node.text for node in nodes if node.key != "entry") + "\n",
                encoding="utf-8",
            )


if __name__ == "__main__":
    main()
