"""Build deterministic Clean Frame enter/exit/toggle Blueprint graphs.

The graphs suppress Conan's native HUD through the same GUI-module and ConanHUD
APIs used by FunCombat_PlayerController, while preserving the prior HUD and
Popup category flags.  The mod-owned path preview is hidden, never destroyed.
"""

from __future__ import annotations

import argparse
import importlib.util
import re
import sys
from pathlib import Path


CLIENT_ASSET = (
    "/Game/Mods/ExileDroneDirector/Core/Client/"
    "BPC_EDD_ClientDirector.BPC_EDD_ClientDirector"
)
PLAYER_CONTROLLER = "/Script/CoreUObject.Class'/Script/Engine.PlayerController'"
ACTOR = "/Script/CoreUObject.Class'/Script/Engine.Actor'"


def load_helpers(project_root: Path):
    path = project_root / "tools" / "blueprint" / "Build-WaypointCaptureGraph.py"
    spec = importlib.util.spec_from_file_location("edd_clean_frame_base", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load graph helpers: {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def set_entry(node, graph_name: str) -> None:
    node.text = re.sub(
        r'FunctionReference=\(MemberName="[^"]+"\)',
        f'FunctionReference=(MemberName="{graph_name}")',
        node.text,
        count=1,
    )


def set_default(node, pin_name: str, value: str) -> None:
    def mutate(line: str) -> str:
        if 'DefaultValue="' in line:
            return re.sub(r'DefaultValue="[^"]*"', f'DefaultValue="{value}"', line, count=1)
        return line.replace(",PersistentGuid=", f',DefaultValue="{value}",PersistentGuid=', 1)

    node.mutate_pin(pin_name, mutate)


def retarget_bool_variable(node, old: str, new: str) -> None:
    node.text = re.sub(
        rf'VariableReference=\(MemberName="{re.escape(old)}"[^)]*\)',
        f'VariableReference=(MemberName="{new}",bSelfContext=True)',
        node.text,
        count=1,
    )
    node.text = node.text.replace(f'PinName="{old}"', f'PinName="{new}"')
    node.pins[new] = node.pins.pop(old)


def retarget_self_call(node, name: str) -> None:
    node.text = re.sub(
        r'FunctionReference=\([^)]*\)',
        f'FunctionReference=(MemberName="{name}",bSelfContext=True)',
        node.text,
        count=1,
    )


def retarget_preview_get(node) -> None:
    old = "PathPreviewActorV1"
    node.text = re.sub(
        rf'VariableReference=\(MemberName="{old}"[^)]*\)',
        f'VariableReference=(MemberName="{old}",bSelfContext=True)',
        node.text,
        count=1,
    )


def set_category(node, category: str) -> None:
    set_default(node, "Category", category)


def make_is_category_template(enable_template: str) -> str:
    text = enable_template.replace(
        'MemberName="EnableCategory"', 'MemberName="IsCategoryEnabled"', 1
    )
    text = text.replace("   FunctionReference=", "   bDefaultsToPureFunc=True\n   FunctionReference=", 1)
    lines = []
    for line in text.splitlines():
        if 'PinName="execute"' in line or 'PinName="then"' in line:
            continue
        if 'PinName="Enable"' in line:
            line = line.replace('PinName="Enable"', 'PinName="ReturnValue"', 1)
            line = line.replace(
                'PinToolTip="Enable\\nBoolean"', 'PinToolTip="Return Value\\nBoolean"', 1
            )
            line = line.replace(
                'PinName="ReturnValue",',
                'PinName="ReturnValue",Direction="EGPD_Output",',
                1,
            )
            line = re.sub(r',DefaultValue="[^"]*"', '', line)
            line = re.sub(r',AutogeneratedDefaultValue="[^"]*"', '', line)
        lines.append(line)
    return "\n".join(lines)


def make_actor_hidden_template(enable_template: str) -> str:
    text = enable_template.replace(
        'MemberParent="/Script/CoreUObject.Class\'/Script/ConanSandbox.GUIModuleController\'",MemberName="EnableCategory"',
        'MemberParent="/Script/CoreUObject.Class\'/Script/Engine.Actor\'",MemberName="SetActorHiddenInGame"',
        1,
    )
    lines = []
    for line in text.splitlines():
        if 'PinName="Enable"' in line:
            continue
        if 'PinName="self"' in line:
            line = re.sub(
                r'PinType\.PinSubCategoryObject="[^"]+"',
                f'PinType.PinSubCategoryObject="{ACTOR}"',
                line,
                count=1,
            )
            line = line.replace("GUIModule Controller Object Reference", "Actor Object Reference")
        if 'PinName="Category"' in line:
            line = line.replace('PinName="Category"', 'PinName="bNewHidden"', 1)
            line = line.replace('PinToolTip="Category\\nEGUIModuleCategory Enum"', 'PinToolTip="New Hidden\\nBoolean"', 1)
            line = re.sub(r'PinType\.PinCategory="[^"]+"', 'PinType.PinCategory="bool"', line, count=1)
            line = re.sub(r'PinType\.PinSubCategoryObject="[^"]+"', 'PinType.PinSubCategoryObject=None', line, count=1)
            line = re.sub(r'DefaultValue="[^"]*"', 'DefaultValue="false"', line, count=1)
            line = re.sub(r'AutogeneratedDefaultValue="[^"]*"', 'AutogeneratedDefaultValue="false"', line, count=1)
        lines.append(line)
    return "\n".join(lines)


def make_player_controller_cast_template(hud_cast: str) -> str:
    text = hud_cast.replace(
        "/Script/Engine.BlueprintGeneratedClass'/Game/UI/Data/Blueprints/BaseGameHUD.BaseGameHUD_C'",
        PLAYER_CONTROLLER,
    )
    text = text.replace('PinName="AsBase Game HUD"', 'PinName="As Player Controller"')
    return text


def load_templates(project_root: Path, bp) -> dict[str, str]:
    snippets = project_root / "tools" / "blueprint" / "snippets"
    templates = project_root / "tools" / "blueprint" / "templates"
    enter = bp.read_blocks(snippets / "enter-drone-mode.eddgraph")
    toggle = bp.read_blocks(snippets / "toggle-state.eddgraph")
    event = bp.read_blocks(snippets / "client-director-event-graph.eddgraph")
    preview = bp.read_blocks(snippets / "refresh-path-preview-v1.eddgraph")
    native = bp.read_blocks(templates / "conan-clean-frame-node-forms.eddgraph")
    capture = bp.read_blocks(templates / "waypoint-capture-node-forms.eddgraph")
    enable = bp.find_block(native, r'MemberName="EnableCategory"')
    hud_cast = bp.find_block(native, r"K2Node_DynamicCast")
    return {
        "entry": bp.find_block(capture, r"K2Node_FunctionEntry"),
        "branch": bp.find_block(
            enter,
            r"^Begin Object Class=/Script/BlueprintGraph\.K2Node_IfThenElse\b",
        ),
        "valid": bp.find_block(enter, r'MemberName="IsValid"'),
        "bool_get": bp.find_block(toggle, r'K2Node_VariableGet.*MemberName="DroneModeActive"'),
        "bool_set": bp.find_block(toggle, r'K2Node_VariableSet.*MemberName="DroneModeActive"'),
        "print": bp.find_block(toggle, r'MemberName="PrintString"'),
        "self_call": bp.find_block(event, r'MemberName="StopLinearPlayback"'),
        "get_owner": bp.find_block(event, r'MemberName="GetOwner"'),
        "preview_get": bp.find_block(preview, r'K2Node_VariableGet.*MemberName="PathPreviewActorV1"'),
        "get_gui": bp.find_block(native, r'MemberName="GetGUIModuleController"'),
        "enable_category": enable,
        "is_category": make_is_category_template(enable),
        "get_hud": bp.find_block(native, r'MemberName="GetHUD"'),
        "player_cast": make_player_controller_cast_template(hud_cast),
        "hud_cast": hud_cast,
        "set_hud_visibility": bp.find_block(native, r'MemberName="SetHUDVisibility"'),
        "select_visibility": bp.find_block(native, r"K2Node_Select"),
        "set_actor_hidden": make_actor_hidden_template(enable),
    }


class Builder:
    def __init__(self, bp, templates: dict[str, str], graph_name: str):
        self.bp = bp
        self.templates = templates
        self.nodes = []
        bp.TARGET_ASSET = CLIENT_ASSET
        bp.TARGET_GRAPH = graph_name
        self.entry = self.add("entry", "entry", "K2Node_FunctionEntry_0", 0, 0)
        set_entry(self.entry, graph_name)

    def add(self, key: str, template: str, name: str, x: int, y: int):
        node = self.bp.Node.clone(key, self.templates[template], name, x, y)
        self.nodes.append(node)
        return node

    def bool_get(self, variable: str, x: int, y: int):
        node = self.add(variable + "_get", "bool_get", f"K2Node_VariableGet_{len(self.nodes)}", x, y)
        retarget_bool_variable(node, "DroneModeActive", variable)
        return node

    def bool_set(self, variable: str, x: int, y: int):
        node = self.add(variable + "_set", "bool_set", f"K2Node_VariableSet_{len(self.nodes)}", x, y)
        retarget_bool_variable(node, "DroneModeActive", variable)
        return node

    def call(self, function: str, x: int, y: int):
        node = self.add(
            function,
            "self_call",
            f"K2Node_CallFunction_Call_{function}_{len(self.nodes)}",
            x,
            y,
        )
        retarget_self_call(node, function)
        return node

    def print(self, text: str, x: int, y: int):
        node = self.add(
            "print_" + str(len(self.nodes)),
            "print",
            f"K2Node_CallFunction_Print_{len(self.nodes)}",
            x,
            y,
        )
        set_default(node, "InString", text)
        return node


def build_enter(bp, templates):
    b = Builder(bp, templates, "EnterCleanFrameV1")
    active = b.bool_get("CleanFrameActiveV1", 0, 224)
    guard = b.add("guard", "branch", "K2Node_IfThenElse_0", 272, 0)
    ignored = b.print("[EDD] Clean Frame ignored: already enabled", 528, -144)

    gui_popup = b.add("gui_popup", "get_gui", "K2Node_CallFunction_0", 416, 240)
    query_popup = b.add("query_popup", "is_category", "K2Node_CallFunction_1", 656, 240)
    set_category(query_popup, "Popup")
    save_popup = b.bool_set("CleanFrameRestorePopupCategoryV1", 912, 32)

    gui_hud = b.add("gui_hud", "get_gui", "K2Node_CallFunction_2", 912, 336)
    query_hud = b.add("query_hud", "is_category", "K2Node_CallFunction_3", 1152, 336)
    set_category(query_hud, "HUD")
    save_hud = b.bool_set("CleanFrameRestoreHUDCategoryV1", 1408, 32)

    gui_disable_popup = b.add("gui_disable_popup", "get_gui", "K2Node_CallFunction_4", 1408, 432)
    disable_popup = b.add("disable_popup", "enable_category", "K2Node_CallFunction_5", 1664, 32)
    set_category(disable_popup, "Popup")
    set_default(disable_popup, "Enable", "false")
    gui_disable_hud = b.add("gui_disable_hud", "get_gui", "K2Node_CallFunction_6", 1952, 432)
    disable_hud = b.add("disable_hud", "enable_category", "K2Node_CallFunction_7", 2208, 32)
    set_category(disable_hud, "HUD")
    set_default(disable_hud, "Enable", "false")

    owner = b.add("owner", "get_owner", "K2Node_CallFunction_8", 2208, 384)
    pc_cast = b.add("pc_cast", "player_cast", "K2Node_DynamicCast_0", 2496, 32)
    get_hud = b.add("get_hud", "get_hud", "K2Node_CallFunction_9", 2736, 368)
    hud_cast = b.add("hud_cast", "hud_cast", "K2Node_DynamicCast_1", 2992, 32)
    hide_native = b.add("hide_native", "set_hud_visibility", "K2Node_CallFunction_10", 3264, 32)
    set_default(hide_native, "visibility", "Hidden")

    preview = b.add("preview", "preview_get", "K2Node_VariableGet_3", 2992, 464)
    retarget_preview_get(preview)
    preview_valid = b.add("preview_valid", "valid", "K2Node_CallFunction_11", 3264, 464)
    preview_branch = b.add("preview_branch", "branch", "K2Node_IfThenElse_1", 3536, 32)
    hide_preview = b.add("hide_preview", "set_actor_hidden", "K2Node_CallFunction_12", 3792, 32)
    set_default(hide_preview, "bNewHidden", "true")
    set_active = b.bool_set("CleanFrameActiveV1", 4080, 32)
    set_default(set_active, "CleanFrameActiveV1", "true")
    enabled = b.print("[EDD] Clean Frame enabled", 4368, 32)

    bp.connect(b.entry, "then", guard, "execute")
    bp.connect(active, "CleanFrameActiveV1", guard, "Condition")
    bp.connect(guard, "then", ignored, "execute")
    bp.connect(guard, "else", save_popup, "execute")
    bp.connect(gui_popup, "ReturnValue", query_popup, "self")
    bp.connect(query_popup, "ReturnValue", save_popup, "CleanFrameRestorePopupCategoryV1")
    bp.connect(save_popup, "then", save_hud, "execute")
    bp.connect(gui_hud, "ReturnValue", query_hud, "self")
    bp.connect(query_hud, "ReturnValue", save_hud, "CleanFrameRestoreHUDCategoryV1")
    bp.connect(save_hud, "then", disable_popup, "execute")
    bp.connect(gui_disable_popup, "ReturnValue", disable_popup, "self")
    bp.connect(disable_popup, "then", disable_hud, "execute")
    bp.connect(gui_disable_hud, "ReturnValue", disable_hud, "self")
    bp.connect(disable_hud, "then", pc_cast, "execute")
    bp.connect(owner, "ReturnValue", pc_cast, "Object")
    bp.connect(pc_cast, "then", hud_cast, "execute")
    bp.connect(pc_cast, "As Player Controller", get_hud, "self")
    bp.connect(get_hud, "ReturnValue", hud_cast, "Object")
    bp.connect(hud_cast, "then", hide_native, "execute")
    bp.connect(hud_cast, "AsBase Game HUD", hide_native, "self")
    bp.connect(hide_native, "then", preview_branch, "execute")
    bp.connect(hud_cast, "CastFailed", preview_branch, "execute")
    bp.connect(pc_cast, "CastFailed", preview_branch, "execute")
    bp.connect(preview, "PathPreviewActorV1", preview_valid, "Object")
    bp.connect(preview_valid, "ReturnValue", preview_branch, "Condition")
    bp.connect(preview_branch, "then", hide_preview, "execute")
    bp.connect(preview, "PathPreviewActorV1", hide_preview, "self")
    bp.connect(hide_preview, "then", set_active, "execute")
    bp.connect(preview_branch, "else", set_active, "execute")
    bp.connect(set_active, "then", enabled, "execute")
    return b.nodes


def build_exit(bp, templates):
    b = Builder(bp, templates, "ExitCleanFrameV1")
    active = b.bool_get("CleanFrameActiveV1", 0, 224)
    guard = b.add("guard", "branch", "K2Node_IfThenElse_0", 272, 0)
    ignored = b.print("[EDD] Clean Frame ignored: already disabled", 528, 240)

    popup_state = b.bool_get("CleanFrameRestorePopupCategoryV1", 416, 368)
    gui_popup = b.add("gui_popup", "get_gui", "K2Node_CallFunction_0", 416, 464)
    enable_popup = b.add("enable_popup", "enable_category", "K2Node_CallFunction_1", 656, 0)
    set_category(enable_popup, "Popup")
    hud_state = b.bool_get("CleanFrameRestoreHUDCategoryV1", 944, 368)
    gui_hud = b.add("gui_hud", "get_gui", "K2Node_CallFunction_2", 944, 464)
    enable_hud = b.add("enable_hud", "enable_category", "K2Node_CallFunction_3", 1184, 0)
    set_category(enable_hud, "HUD")

    owner = b.add("owner", "get_owner", "K2Node_CallFunction_4", 1184, 384)
    pc_cast = b.add("pc_cast", "player_cast", "K2Node_DynamicCast_0", 1472, 0)
    get_hud = b.add("get_hud", "get_hud", "K2Node_CallFunction_5", 1712, 368)
    hud_cast = b.add("hud_cast", "hud_cast", "K2Node_DynamicCast_1", 1968, 0)
    select_visibility = b.add("select_visibility", "select_visibility", "K2Node_Select_0", 2240, 368)
    restore_native = b.add("restore_native", "set_hud_visibility", "K2Node_CallFunction_6", 2240, 0)

    preview = b.add("preview", "preview_get", "K2Node_VariableGet_3", 1968, 512)
    retarget_preview_get(preview)
    preview_valid = b.add("preview_valid", "valid", "K2Node_CallFunction_7", 2240, 512)
    preview_branch = b.add("preview_branch", "branch", "K2Node_IfThenElse_1", 2528, 0)
    show_preview = b.add("show_preview", "set_actor_hidden", "K2Node_CallFunction_8", 2784, 0)
    set_default(show_preview, "bNewHidden", "false")
    clear_active = b.bool_set("CleanFrameActiveV1", 3072, 0)
    set_default(clear_active, "CleanFrameActiveV1", "false")
    disabled = b.print("[EDD] Clean Frame disabled", 3360, 0)

    bp.connect(b.entry, "then", guard, "execute")
    bp.connect(active, "CleanFrameActiveV1", guard, "Condition")
    bp.connect(guard, "else", ignored, "execute")
    bp.connect(guard, "then", enable_popup, "execute")
    bp.connect(gui_popup, "ReturnValue", enable_popup, "self")
    bp.connect(popup_state, "CleanFrameRestorePopupCategoryV1", enable_popup, "Enable")
    bp.connect(enable_popup, "then", enable_hud, "execute")
    bp.connect(gui_hud, "ReturnValue", enable_hud, "self")
    bp.connect(hud_state, "CleanFrameRestoreHUDCategoryV1", enable_hud, "Enable")
    bp.connect(enable_hud, "then", pc_cast, "execute")
    bp.connect(owner, "ReturnValue", pc_cast, "Object")
    bp.connect(pc_cast, "then", hud_cast, "execute")
    bp.connect(pc_cast, "As Player Controller", get_hud, "self")
    bp.connect(get_hud, "ReturnValue", hud_cast, "Object")
    bp.connect(hud_cast, "then", restore_native, "execute")
    bp.connect(hud_cast, "AsBase Game HUD", restore_native, "self")
    bp.connect(hud_state, "CleanFrameRestoreHUDCategoryV1", select_visibility, "Index")
    bp.connect(select_visibility, "ReturnValue", restore_native, "visibility")
    bp.connect(restore_native, "then", preview_branch, "execute")
    bp.connect(hud_cast, "CastFailed", preview_branch, "execute")
    bp.connect(pc_cast, "CastFailed", preview_branch, "execute")
    bp.connect(preview, "PathPreviewActorV1", preview_valid, "Object")
    bp.connect(preview_valid, "ReturnValue", preview_branch, "Condition")
    bp.connect(preview_branch, "then", show_preview, "execute")
    bp.connect(preview, "PathPreviewActorV1", show_preview, "self")
    bp.connect(show_preview, "then", clear_active, "execute")
    bp.connect(preview_branch, "else", clear_active, "execute")
    bp.connect(clear_active, "then", disabled, "execute")
    return b.nodes


def build_toggle(bp, templates):
    b = Builder(bp, templates, "ToggleCleanFrameV1")
    active = b.bool_get("CleanFrameActiveV1", 0, 224)
    branch = b.add("branch", "branch", "K2Node_IfThenElse_0", 272, 0)
    exit_call = b.call("ExitCleanFrameV1", 544, -96)
    enter_call = b.call("EnterCleanFrameV1", 544, 128)
    bp.connect(b.entry, "then", branch, "execute")
    bp.connect(active, "CleanFrameActiveV1", branch, "Condition")
    bp.connect(branch, "then", exit_call, "execute")
    bp.connect(branch, "else", enter_call, "execute")
    return b.nodes


def write_graph(nodes, output: Path, *, paste: bool) -> None:
    blocks = []
    for node in nodes:
        if paste and node is nodes[0]:
            continue
        text = node.text
        if paste:
            text = re.sub(r',LinkedTo=\(K2Node_FunctionEntry_0 [0-9A-F]{32},\)', '', text)
        blocks.append(text)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(blocks) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-root", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--paste-dir", type=Path)
    args = parser.parse_args()
    bp = load_helpers(args.project_root)
    templates = load_templates(args.project_root, bp)
    graphs = {
        "enter-clean-frame-v1": build_enter(bp, templates),
        "exit-clean-frame-v1": build_exit(bp, templates),
        "toggle-clean-frame-v1": build_toggle(bp, templates),
    }
    for stem, nodes in graphs.items():
        write_graph(nodes, args.output_dir / f"{stem}.eddgraph", paste=False)
        if args.paste_dir:
            write_graph(nodes, args.paste_dir / f"{stem}-paste.eddgraph", paste=True)


if __name__ == "__main__":
    main()
