"""Add shared draft-count/selection feedback after K, R, and Delete mutations."""

from __future__ import annotations

import argparse
import re
import uuid
from pathlib import Path


BLOCK_RE = re.compile(
    r"^Begin Object Class=(?P<class>\S+) Name=\"(?P<name>[^\"]+)\".*?^End Object\r?$",
    re.MULTILINE | re.DOTALL,
)
PIN_RE = re.compile(r'^\s*CustomProperties Pin \(.*?PinName="(?P<name>[^"]+)".*\)$')
ASSET_PATH = "/Game/Mods/ExileDroneDirector/Core/Client/BPC_EDD_ClientDirector.BPC_EDD_ClientDirector"
FEEDBACK_PREFIX = "[EDD] Draft waypoints: "
FEEDBACK_SEPARATOR = " | selected: "

_id_counter = 0


def new_id() -> str:
    global _id_counter
    _id_counter += 1
    return uuid.uuid5(
        uuid.NAMESPACE_URL,
        f"exile-drone-director:waypoint-feedback-dispatch:{_id_counter}",
    ).hex.upper()


def block_name(block: str) -> str:
    match = BLOCK_RE.match(block)
    if match is None:
        raise RuntimeError("Malformed Blueprint node block")
    return match.group("name")


def pin_map(block: str) -> dict[str, str]:
    result: dict[str, str] = {}
    for line in block.splitlines():
        match = PIN_RE.match(line)
        if match:
            pin_id = re.search(r"PinId=([0-9A-F]{32})", line)
            if pin_id is None:
                raise RuntimeError(f"Pin {match.group('name')} has no identifier")
            result[match.group("name")] = pin_id.group(1)
    return result


def add_link(block: str, pin_id: str, other_name: str, other_pin_id: str) -> str:
    lines = block.splitlines()
    for index, line in enumerate(lines):
        if f"PinId={pin_id}" not in line:
            continue
        existing = re.search(r",LinkedTo=\((?P<links>[^)]*)\)", line)
        if existing:
            links = existing.group("links") + f"{other_name} {other_pin_id},"
            lines[index] = line[: existing.start()] + f",LinkedTo=({links})" + line[existing.end() :]
        else:
            lines[index] = line.replace(
                ",PersistentGuid=",
                f",LinkedTo=({other_name} {other_pin_id},),PersistentGuid=",
                1,
            )
        return "\n".join(lines)
    raise RuntimeError(f"Could not find pin {pin_id}")


def connect(blocks: dict[str, str], left_name: str, left_pin: str, right_name: str, right_pin: str) -> None:
    left_pins = pin_map(blocks[left_name])
    right_pins = pin_map(blocks[right_name])
    blocks[left_name] = add_link(blocks[left_name], left_pins[left_pin], right_name, right_pins[right_pin])
    blocks[right_name] = add_link(blocks[right_name], right_pins[right_pin], left_name, left_pins[left_pin])


def clone_node(template: str, new_name: str, x: int, y: int, source_graph: str | None = None) -> str:
    old_name = block_name(template)
    block = template.replace(f'Name="{old_name}"', f'Name="{new_name}"', 1)
    block = block.replace(f".{old_name}'\"", f".{new_name}'\"", 1)
    if source_graph:
        block = block.replace(f":{source_graph}.", ":EventGraph.", 1)
    block = re.sub(r"NodePosX=\-?\d+", f"NodePosX={x}", block, count=1)
    block = re.sub(r"NodePosY=\-?\d+", f"NodePosY={y}", block, count=1)
    block = re.sub(r"NodeGuid=[0-9A-F]{32}", f"NodeGuid={new_id()}", block, count=1)
    block = re.sub(r",LinkedTo=\([^)]*\)", "", block)
    rebuilt: list[str] = []
    for line in block.splitlines():
        if PIN_RE.match(line):
            line = re.sub(r"PinId=[0-9A-F]{32}", f"PinId={new_id()}", line, count=1)
        rebuilt.append(line)
    return "\n".join(rebuilt)


def next_name(text: str, prefix: str) -> str:
    indexes = [int(value) for value in re.findall(rf'Name="{re.escape(prefix)}_(\d+)"', text)]
    return f"{prefix}_{max(indexes, default=-1) + 1}"


def find_one(blocks: list[str], marker: str) -> str:
    matches = [block for block in blocks if marker in block]
    if len(matches) != 1:
        raise RuntimeError(f"Expected exactly one node containing {marker!r}; found {len(matches)}")
    return matches[0]


def pin(
    name: str,
    category: str,
    *,
    direction: str = "",
    subcategory_object: str = "None",
    default: str | None = None,
    autogenerated_default: str | None = None,
    default_object: str | None = None,
    hidden: bool = False,
) -> str:
    fields = [
        f"PinId={new_id()}",
        f'PinName="{name}"',
    ]
    if direction:
        fields.append(f'Direction="{direction}"')
    fields.extend(
        [
            f'PinType.PinCategory="{category}"',
            'PinType.PinSubCategory=""',
            f"PinType.PinSubCategoryObject={subcategory_object}",
            "PinType.PinSubCategoryMemberReference=()",
            "PinType.PinValueType=()",
            "PinType.ContainerType=None",
            "PinType.bIsReference=False",
            "PinType.bIsConst=False",
            "PinType.bIsWeakPointer=False",
            "PinType.bIsUObjectWrapper=False",
            "PinType.bSerializeAsSinglePrecisionFloat=False",
        ]
    )
    if default is not None:
        fields.append(f'DefaultValue="{default}"')
        generated = default if autogenerated_default is None else autogenerated_default
        fields.append(f'AutogeneratedDefaultValue="{generated}"')
    if default_object is not None:
        fields.append(f'DefaultObject="{default_object}"')
    fields.extend(
        [
            "PersistentGuid=00000000000000000000000000000000",
            f"bHidden={'True' if hidden else 'False'}",
            "bNotConnectable=False",
            "bDefaultValueIsReadOnly=False",
            "bDefaultValueIsIgnored=False",
            "bAdvancedView=False",
            "bOrphanedPin=False",
        ]
    )
    return "   CustomProperties Pin (" + ",".join(fields) + ",)"


def build_string_int_node(name: str, x: int, y: int, prefix: str, suffix: str) -> str:
    return "\n".join(
        [
            f'Begin Object Class=/Script/BlueprintGraph.K2Node_CallFunction Name="{name}" ExportPath="/Script/BlueprintGraph.K2Node_CallFunction\'{ASSET_PATH}:EventGraph.{name}\'"',
            "   bDefaultsToPureFunc=True",
            '   FunctionReference=(MemberParent="/Script/CoreUObject.Class\'/Script/Engine.KismetStringLibrary\'",MemberName="BuildString_Int")',
            f"   NodePosX={x}",
            f"   NodePosY={y}",
            f"   NodeGuid={new_id()}",
            pin(
                "self",
                "object",
                subcategory_object='"/Script/CoreUObject.Class\'/Script/Engine.KismetStringLibrary\'"',
                default_object="/Script/Engine.Default__KismetStringLibrary",
                hidden=True,
            ),
            pin("AppendTo", "string", default=""),
            pin("Prefix", "string", default=prefix, autogenerated_default=""),
            pin("InInt", "int", default="0"),
            pin("Suffix", "string", default=suffix, autogenerated_default=""),
            pin("ReturnValue", "string", direction="EGPD_Output", default=""),
            "End Object",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    text = args.input.read_text(encoding="utf-8")
    if text.count(FEEDBACK_PREFIX) == 1 and text.count('MemberName="BuildString_Int"') == 2:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_bytes(args.input.read_bytes())
        print("Client graph already contains draft count/selection feedback; output unchanged.")
        return
    if FEEDBACK_PREFIX in text or 'MemberName="BuildString_Int"' in text:
        raise RuntimeError("Input contains a partial or ambiguous waypoint feedback graph")

    source_blocks = [match.group(0) for match in BLOCK_RE.finditer(text)]
    capture = find_one(source_blocks, 'MemberName="CaptureCurrentWaypoint"')
    replace = find_one(source_blocks, 'MemberName="ReplaceSelectedWaypoint"')
    delete = find_one(source_blocks, 'MemberName="DeleteSelectedWaypoint"')
    print_templates = [block for block in source_blocks if 'MemberName="PrintString"' in block]
    if not print_templates:
        raise RuntimeError("Input EventGraph has no PrintString node to clone")
    print_template = print_templates[0]

    template_path = Path(__file__).resolve().parent / "snippets" / "delete-selected-waypoint.eddgraph"
    template_text = template_path.read_text(encoding="utf-8")
    template_blocks = [match.group(0) for match in BLOCK_RE.finditer(template_text)]
    selected_templates = [
        block
        for block in template_blocks
        if block.startswith("Begin Object Class=/Script/BlueprintGraph.K2Node_VariableGet ")
        and 'VariableReference=(MemberName="SelectedWaypointIndex"' in block
    ]
    if len(selected_templates) != 1:
        raise RuntimeError(f"Expected one selected-index getter template; found {len(selected_templates)}")
    selected_template = selected_templates[0]
    ids_template = find_one(template_blocks, 'VariableReference=(MemberName="DraftWaypointIds"')
    length_template = find_one(template_blocks, 'MemberName="Array_Length"')

    staged = text
    names: list[str] = []
    for prefix in (
        "K2Node_VariableGet",
        "K2Node_VariableGet",
        "K2Node_CallArrayFunction",
        "K2Node_CallFunction",
        "K2Node_CallFunction",
        "K2Node_CallFunction",
        "K2Node_CallFunction",
        "K2Node_CallFunction",
    ):
        name = next_name(staged, prefix)
        staged += f' Name="{name}"'
        names.append(name)
    selected_name, ids_name, length_name, build_count_name, build_selected_name, capture_print_name, replace_print_name, delete_print_name = names

    blocks = {
        block_name(capture): capture,
        block_name(replace): replace,
        block_name(delete): delete,
        selected_name: clone_node(selected_template, selected_name, 7712, 1216, "DeleteSelectedWaypoint"),
        ids_name: clone_node(ids_template, ids_name, 7424, 1088, "DeleteSelectedWaypoint"),
        length_name: clone_node(length_template, length_name, 7712, 1088, "DeleteSelectedWaypoint"),
        build_count_name: build_string_int_node(build_count_name, 7984, 1088, FEEDBACK_PREFIX, FEEDBACK_SEPARATOR),
        build_selected_name: build_string_int_node(build_selected_name, 8320, 1088, "", ""),
        capture_print_name: clone_node(print_template, capture_print_name, 8000, 320),
        replace_print_name: clone_node(print_template, replace_print_name, 8000, 576),
        delete_print_name: clone_node(print_template, delete_print_name, 8000, 832),
    }

    connect(blocks, ids_name, "DraftWaypointIds", length_name, "TargetArray")
    connect(blocks, length_name, "ReturnValue", build_count_name, "InInt")
    connect(blocks, build_count_name, "ReturnValue", build_selected_name, "AppendTo")
    connect(blocks, selected_name, "SelectedWaypointIndex", build_selected_name, "InInt")

    for mutation, feedback in (
        (block_name(capture), capture_print_name),
        (block_name(replace), replace_print_name),
        (block_name(delete), delete_print_name),
    ):
        connect(blocks, mutation, "then", feedback, "execute")
        connect(blocks, build_selected_name, "ReturnValue", feedback, "InString")

    replacements = {
        block_name(capture): blocks.pop(block_name(capture)),
        block_name(replace): blocks.pop(block_name(replace)),
        block_name(delete): blocks.pop(block_name(delete)),
    }
    output_blocks = [replacements.get(block_name(block), block) for block in source_blocks]
    output_blocks.extend(blocks.values())

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(output_blocks) + "\n", encoding="utf-8")
    print("Added shared draft count/selection feedback after K, R, and Delete mutations.")


if __name__ == "__main__":
    main()
