"""Build atomic candidate-to-compiled publication for the camera channel bank."""
from __future__ import annotations
import argparse,importlib.util,re,sys
from pathlib import Path
FUNCTION="CommitCameraChannelAssemblyV1"
ARRAYS=(("KeyOffsets","int"),("KeyCounts","int"),("KeyTimes","real"),("DomainValues","real"),("InterpolationModes","string"),("ArriveTangents","real"),("LeaveTangents","real"),("Domains","string"))
def load(root):p=root/"tools/blueprint/Build-TrajectoryScalarEvaluatorGraphs.py";s=importlib.util.spec_from_file_location("edd_camera_channel_commit_base",p);m=importlib.util.module_from_spec(s);sys.modules[s.name]=m;s.loader.exec_module(m);return m
def kind(n,p,k,array=False):
 cat,sub={"bool":("bool",""),"int":("int",""),"real":("real","double"),"string":("string","")}[k]
 def f(line):line=re.sub(r'PinType.PinCategory="[^"]*"',f'PinType.PinCategory="{cat}"',line,1);line=re.sub(r'PinType.PinSubCategory="[^"]*"',f'PinType.PinSubCategory="{sub}"',line,1);line=re.sub(r'PinType.PinSubCategoryObject=(?:None|"[^"]*")','PinType.PinSubCategoryObject=None',line,1);return re.sub(r'PinType.ContainerType=(?:None|Array)',f'PinType.ContainerType={"Array" if array else "None"}',line,1)
 n.mutate_pin(p,f)
def main():
 p=argparse.ArgumentParser();p.add_argument("--project-root",type=Path,required=True);p.add_argument("--output",type=Path,required=True);p.add_argument("--paste-output",type=Path);a=p.parse_args();s=load(a.project_root);bp=s.load_helpers(a.project_root);forms=s.load_templates(a.project_root,bp);b=s.Builder(bp,forms,FUNCTION);edit=bp.read_blocks(a.project_root/"tools/blueprint/templates/waypoint-edit-node-forms.eddgraph");play=bp.read_blocks(a.project_root/"tools/blueprint/snippets/update-linear-playback.eddgraph");sync=bp.read_blocks(a.project_root/"tools/blueprint/templates/waypoint-struct-sync-node-forms.eddgraph");template={"length":bp.find_block(edit,r'MemberName="Array_Length"'),"item":bp.find_block(play,r"^Begin Object Class=/Script/BlueprintGraph.K2Node_GetArrayItem"),"foreach":bp.find_block(sync,r"^Begin Object Class=/Script/BlueprintGraph.K2Node_MacroInstance")}
 def addform(key,form,x,y):raw=template[form];m=bp.BLOCK_RE.match(raw);cls=m.group("class").rsplit(".",1)[-1];i=b.serial.get(cls,0);b.serial[cls]=i+1;n=bp.Node.clone(key,raw,f"{cls}_{i}",x,y);b.nodes.append(n);return n
 def var(n,name,k,array=False):s.retarget_variable(n,name,"real" if k=="int" else k);kind(n,name,k,array);kind(n,"Output_Get",k,array) if "Output_Get" in n.pins else None
 def get(name,k,x,y,array=False):n=b.add(f"get_{name}_{len(b.nodes)}","get",x,y);var(n,name,k,array);return n
 def setv(name,k,x,y,default=None,array=False):n=b.add(f"set_{name}_{len(b.nodes)}","set",x,y);var(n,name,k,array);s.set_default(n,name,default) if default is not None else None;return n
 def length(src,pin,k,x,y):n=addform(f"len_{pin}_{len(b.nodes)}","length",x,y);kind(n,"TargetArray",k,True);kind(n,"ReturnValue","int");bp.connect(src,pin,n,"TargetArray");return n
 def item(src,pin,k,index,indexpin,x,y):n=addform(f"item_{pin}_{len(b.nodes)}","item",x,y);kind(n,"Array",k,True);kind(n,"Output",k);bp.connect(src,pin,n,"Array");bp.connect(index,indexpin,n,"Dimension 1");return n
 def cmp(member,left,leftpin,x,y,right=None,rightpin=None,default=None,k="int"):n=b.add(f"cmp_{member}_{len(b.nodes)}","compare",x,y);s.retarget_function(n,member);kind(n,"A",k);kind(n,"B",k);kind(n,"ReturnValue","bool");bp.connect(left,leftpin,n,"A");bp.connect(right,rightpin,n,"B") if right is not None else s.set_default(n,"B",default);return n
 def math(member,left,leftpin,x,y,right=None,rightpin=None,default=None):n=b.math("Add_IntInt",x,y);s.retarget_function(n,member);[kind(n,pin,"int") for pin in ("A","B","ReturnValue")];bp.connect(left,leftpin,n,"A");bp.connect(right,rightpin,n,"B") if right is not None else s.set_default(n,"B",default);return n
 def and_all(values,x,y):
  current,pin=values[0]
  for i,(other,otherpin) in enumerate(values[1:]):current=cmp("BooleanAND",current,pin,x+i*208,y,other,otherpin,k="bool");pin="ReturnValue"
  return current
 invalidate=setv("CameraChannelCompileValidV1","bool",256,2880,"false");index_zero=setv("CameraChannelScratchKeyIndexV1","int",480,2880,"0");bp.connect(b.entry,"then",invalidate,"execute");bp.connect(invalidate,"then",index_zero,"execute")
 candidates={stem:get(f"CameraChannelCandidate{stem}V1",k,0,i*144,True) for i,(stem,k) in enumerate(ARRAYS)};lengths={stem:length(candidates[stem],f"CameraChannelCandidate{stem}V1",k,256,i*144) for i,(stem,k) in enumerate(ARRAYS)};key_count=lengths["KeyTimes"]
 shape=[(get("CameraChannelScratchValidV1","bool",0,1440),"CameraChannelScratchValidV1"),(cmp("EqualEqual_IntInt",lengths["KeyOffsets"],"ReturnValue",512,0,default="13"),"ReturnValue"),(cmp("EqualEqual_IntInt",lengths["KeyCounts"],"ReturnValue",512,144,default="13"),"ReturnValue"),(cmp("EqualEqual_IntInt",lengths["Domains"],"ReturnValue",512,288,default="13"),"ReturnValue")]
 for i,stem in enumerate(("DomainValues","ArriveTangents","LeaveTangents")):shape.append((cmp("EqualEqual_IntInt",lengths[stem],"ReturnValue",720,432+i*144,key_count,"ReturnValue"),"ReturnValue"))
 expected_modes=math("Subtract_IntInt",key_count,"ReturnValue",720,864,default="13");shape.append((cmp("EqualEqual_IntInt",lengths["InterpolationModes"],"ReturnValue",944,864,expected_modes,"ReturnValue"),"ReturnValue"));shape_valid=and_all(shape,1168,1280);shape_branch=b.add("shape_branch","branch",2832,2880);bp.connect(index_zero,"then",shape_branch,"execute");bp.connect(shape_valid,"ReturnValue",shape_branch,"Condition")
 loop=addform("offset_loop","foreach",3056,2880);kind(loop,"Array","int",True);kind(loop,"Array Element","int");kind(loop,"Array Index","int");bp.connect(candidates["KeyOffsets"],"CameraChannelCandidateKeyOffsetsV1",loop,"Array");bp.connect(shape_branch,"then",loop,"Exec");count=item(candidates["KeyCounts"],"CameraChannelCandidateKeyCountsV1","int",loop,"Array Index",3280,2080);expected=get("CameraChannelScratchKeyIndexV1","int",3280,2240);offset_ok=cmp("EqualEqual_IntInt",loop,"Array Element",3504,2080,expected,"CameraChannelScratchKeyIndexV1");count_low=cmp("GreaterEqual_IntInt",count,"Output",3504,2240,default="1");count_high=cmp("LessEqual_IntInt",count,"Output",3728,2240,default="512");row=and_all([(offset_ok,"ReturnValue"),(count_low,"ReturnValue"),(count_high,"ReturnValue")],3952,2160);row_branch=b.add("row_branch","branch",4400,2880);bp.connect(loop,"LoopBody",row_branch,"execute");bp.connect(row,"ReturnValue",row_branch,"Condition");row_reject=setv("CameraChannelScratchValidV1","bool",4624,3040,"false");bp.connect(row_branch,"else",row_reject,"execute");next_offset=math("Add_IntInt",expected,"CameraChannelScratchKeyIndexV1",4624,2240,count,"Output");store=setv("CameraChannelScratchKeyIndexV1","int",4848,2880);bp.connect(next_offset,"ReturnValue",store,"CameraChannelScratchKeyIndexV1");bp.connect(row_branch,"then",store,"execute")
 stage=get("CameraChannelScratchValidV1","bool",5072,2240);final_offset=get("CameraChannelScratchKeyIndexV1","int",5072,2400);exact=cmp("EqualEqual_IntInt",final_offset,"CameraChannelScratchKeyIndexV1",5296,2400,key_count,"ReturnValue");final=cmp("BooleanAND",stage,"CameraChannelScratchValidV1",5520,2320,exact,"ReturnValue",k="bool");final_branch=b.add("final_branch","branch",5744,2880);bp.connect(loop,"Completed",final_branch,"execute");bp.connect(final,"ReturnValue",final_branch,"Condition")
 publications=[]
 for i,(stem,k) in enumerate(ARRAYS):n=setv(f"CameraChannelCompiled{stem}V1",k,5968+i*224,2880,array=True);bp.connect(candidates[stem],f"CameraChannelCandidate{stem}V1",n,f"CameraChannelCompiled{stem}V1");publications.append(n)
 scalar_fields=(("CameraChannelInputDurationV1","CameraChannelCompiledDurationV1","real"),("CameraChannelInputFilmbackPresetIdV1","CameraChannelCompiledFilmbackPresetIdV1","string"),("CameraChannelInputFilmbackSensorWidthMmV1","CameraChannelCompiledFilmbackSensorWidthMmV1","real"),("CameraChannelInputFilmbackSensorHeightMmV1","CameraChannelCompiledFilmbackSensorHeightMmV1","real"));
 for i,(source,target,k) in enumerate(scalar_fields):g=get(source,k,0,1760+i*144);n=setv(target,k,7760+i*224,2880);bp.connect(g,source,n,target);publications.append(n)
 success_code=setv("CameraChannelFailureCodeV1","string",8656,2880,"");valid=setv("CameraChannelCompileValidV1","bool",8880,2880,"true");publications.extend((success_code,valid));bp.connect(final_branch,"then",publications[0],"execute");[bp.connect(left,"then",right,"execute") for left,right in zip(publications,publications[1:])]
 full="\n".join(n.text for n in b.nodes)+"\n";a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(full,encoding="utf-8")
 if a.paste_output:a.paste_output.parent.mkdir(parents=True,exist_ok=True);a.paste_output.write_text("\n".join(re.sub(r',LinkedTo=\(K2Node_FunctionEntry_0 [0-9A-F]{32},\)',"",n.text) for n in b.nodes[1:])+"\n",encoding="utf-8")
if __name__=="__main__":main()

