"""Build transactional native pose plus accepted engine-property application."""

from __future__ import annotations

import argparse
import importlib.util
import re
import sys
from pathlib import Path


FUNCTION = "ApplyCameraPlaybackNativeFrameV1"
TARGET = '"/Script/Engine.BlueprintGeneratedClass\'/Game/Mods/ExileDroneDirector/Core/Client/BPC_EDD_ClientDirector.BPC_EDD_ClientDirector_C\'"'
DRONE_CAMERA_CLASS = "/Script/Engine.BlueprintGeneratedClass'/Game/Mods/ExileDroneDirector/Core/Camera/BP_EDD_DroneCamera.BP_EDD_DroneCamera_C'"


def load(root: Path):
    path = root / "tools/blueprint/Build-TrajectoryScalarEvaluatorGraphs.py"
    spec = importlib.util.spec_from_file_location("edd_playback_native_apply_base", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def pin_kind(node, pin_name: str, kind: str) -> None:
    category, subcategory, obj = {
        "bool": ("bool", "", "None"), "int": ("int", "", "None"),
        "real": ("real", "double", "None"), "string": ("string", "", "None"),
        "vector": ("struct", "", '"/Script/CoreUObject.ScriptStruct\'/Script/CoreUObject.Vector\'"'),
        "quat": ("struct", "", '"/Script/CoreUObject.ScriptStruct\'/Script/CoreUObject.Quat\'"'),
        "rotator": ("struct", "", '"/Script/CoreUObject.ScriptStruct\'/Script/CoreUObject.Rotator\'"'),
        "transform": ("struct", "", '"/Script/CoreUObject.ScriptStruct\'/Script/CoreUObject.Transform\'"'),
    }[kind]
    def mutate(line: str) -> str:
        line = re.sub(r'PinType.PinCategory="[^"]*"', f'PinType.PinCategory="{category}"', line, 1)
        line = re.sub(r'PinType.PinSubCategory="[^"]*"', f'PinType.PinSubCategory="{subcategory}"', line, 1)
        line = re.sub(r'PinType.PinSubCategoryObject=(?:None|"[^"]*")', f"PinType.PinSubCategoryObject={obj}", line, 1)
        return re.sub(r"PinType.ContainerType=(?:None|Array)", "PinType.ContainerType=None", line, 1)
    node.mutate_pin(pin_name, mutate)


def remove_pin(node, pin_name: str) -> None:
    pin_id = node.pins.pop(pin_name)
    lines = [line for line in node.text.splitlines() if f"PinId={pin_id}" not in line]
    node.text = "\n".join(lines)


def rename_pin(node, old_name: str, new_name: str) -> None:
    pin_id = node.pins.pop(old_name)
    node.pins[new_name] = pin_id
    old = f'PinName="{old_name}"'
    if node.text.count(old) != 1:
        raise RuntimeError(f"unexpected pin rename shape: {old_name}")
    node.text = node.text.replace(old, f'PinName="{new_name}"', 1)


def collapse_pin(node, pin_name: str) -> None:
    """Collapse a harvested split struct pin so its parent link compiles authoritatively."""
    parent_id = node.pins[pin_name]
    parent_token = f"ParentPin={node.name} {parent_id}"
    child_names: list[str] = []
    lines: list[str] = []
    for line in node.text.splitlines():
        if parent_token in line:
            match = re.search(r'PinName="([^"]+)"', line)
            if match is not None:
                child_names.append(match.group(1))
            continue
        if f"PinId={parent_id}" in line:
            line = re.sub(r'SubPins=\([^)]*\),', '', line, count=1)
        lines.append(line)
    for child_name in child_names:
        node.pins.pop(child_name, None)
    node.text = "\n".join(lines)


def quat_equal_form(template: str) -> str:
    """Derive Unreal's reflected tolerance-aware Quat equality from a harvested Quat form."""
    text = template.replace('MemberName="Quat_Normalized"', 'MemberName="EqualEqual_QuatQuat"', 1)
    lines = text.splitlines()
    q_index = next(index for index, line in enumerate(lines) if 'PinName="Q"' in line)
    a_line = lines[q_index].replace('PinName="Q"', 'PinName="A"', 1)
    b_line = a_line.replace('PinName="A"', 'PinName="B"', 1)
    lines[q_index:q_index + 1] = [a_line, b_line]
    text = "\n".join(lines)
    match = re.search(r'(?m)^.*PinName="ReturnValue".*$', text)
    if match is None:
        raise RuntimeError("Quat equality form has no return pin")
    return_line = match.group(0)
    return_line = re.sub(r'PinType.PinCategory="[^"]*"', 'PinType.PinCategory="bool"', return_line, 1)
    return_line = re.sub(r'PinType.PinSubCategory="[^"]*"', 'PinType.PinSubCategory=""', return_line, 1)
    return_line = re.sub(r'PinType.PinSubCategoryObject=(?:None|"[^"]*")', 'PinType.PinSubCategoryObject=None', return_line, 1)
    return_line = re.sub(r'DefaultValue="[^"]*"', 'DefaultValue="false"', return_line, 1)
    return_line = re.sub(r'AutogeneratedDefaultValue="[^"]*"', 'AutogeneratedDefaultValue="false"', return_line, 1)
    return text[:match.start()] + return_line + text[match.end():]


def rotator_equal_form(template: str) -> str:
    """Derive Unreal's tolerance-aware Rotator equality from the canonical Quat equality form."""
    text = quat_equal_form(template)
    text = text.replace('MemberName="EqualEqual_QuatQuat"', 'MemberName="EqualEqual_RotatorRotator"', 1)
    text = text.replace("/Script/CoreUObject.Quat'", "/Script/CoreUObject.Rotator'")
    text = text.replace('PinName="Tolerance"', 'PinName="ErrorTolerance"', 1)
    return text


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-root", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--paste-output", type=Path)
    args = parser.parse_args()
    scalar = load(args.project_root)
    bp = scalar.load_helpers(args.project_root)
    forms = scalar.load_templates(args.project_root, bp)
    root = args.project_root / "tools/blueprint"
    capture = bp.read_blocks(root / "templates/waypoint-capture-node-forms.eddgraph")
    capture_live = bp.read_blocks(root / "snippets/capture-current-waypoint.eddgraph")
    native = bp.read_blocks(root / "templates/camera-engine-basic-node-forms.eddgraph")
    transform = bp.read_blocks(root / "templates/repository-codec-transform-node-forms.eddgraph")
    math_forms = bp.read_blocks(root / "templates/repository-codec-math-node-forms.eddgraph")
    linear = bp.read_blocks(root / "templates/linear-playback-node-forms.eddgraph")
    calls = bp.read_blocks(root / "snippets/activate-drone-view.eddgraph")
    quaternion_native = bp.read_blocks(root / "templates/trajectory-quaternion-native-node-forms.eddgraph")
    distance_forms = bp.read_blocks(root / "templates/path-preview-segment-node-forms.eddgraph")
    forms.update(
        camera_ref=bp.find_block(capture, r'MemberName="DroneCameraRef"'),
        component=bp.find_block(native, r'MemberName="DroneCamera"'),
        is_valid=bp.find_block(capture_live, r'MemberName="IsValid"'),
        actor_set=bp.find_block(linear, r'MemberName="K2_SetActorTransform"'),
        actor_get=bp.find_block(capture, r'MemberName="GetTransform"'),
        break_transform=bp.find_block(transform, r'MemberName="BreakTransform"'),
        make_transform=bp.find_block(transform, r'MemberName="MakeTransform"'),
        quat_rotator=bp.find_block(math_forms, r'MemberName="Quat_Rotator"'),
        rotator_quat=bp.find_block(math_forms, r'MemberName="Conv_RotatorToQuaternion"'),
        quat_equal=quat_equal_form(bp.find_block(quaternion_native, r'MemberName="Quat_Normalized"')),
        rotator_equal=rotator_equal_form(bp.find_block(quaternion_native, r'MemberName="Quat_Normalized"')),
        vector_distance=bp.find_block(distance_forms, r'MemberName="Vector_Distance"'),
        print_string=bp.find_block(linear, r'MemberName="PrintString"'),
        add_int=bp.find_block(capture, r'MemberName="Add_IntInt"'),
        self_call=bp.find_block(calls, r'MemberName="SwitchToDroneView"'),
    )
    builder = scalar.Builder(bp, forms, FUNCTION)

    def add_form(key: str, form: str, x: int, y: int):
        match = bp.BLOCK_RE.match(forms[form]); cls = match.group("class").rsplit(".", 1)[-1]
        index = builder.serial.get(cls, 0); builder.serial[cls] = index + 1
        node = bp.Node.clone(key, forms[form], f"{cls}_{index}", x, y)
        builder.nodes.append(node); return node

    def variable(node, name: str, kind: str) -> None:
        scalar.retarget_variable(node, name, "vector" if kind in ("quat", "rotator", "transform") else ("real" if kind == "int" else kind))
        pin_kind(node, name, kind)
        if "Output_Get" in node.pins: pin_kind(node, "Output_Get", kind)

    def get(name: str, kind: str, x: int, y: int):
        node = builder.add(f"get_{name}_{len(builder.nodes)}", "get", x, y); variable(node, name, kind); return node

    def set_value(name: str, kind: str, x: int, y: int, default: str):
        node = builder.add(f"set_{name}_{len(builder.nodes)}", "set", x, y); variable(node, name, kind); scalar.set_default(node, name, default); return node

    def self_call(name: str, x: int, y: int):
        node = add_form(f"call_{name}_{len(builder.nodes)}", "self_call", x, y)
        node.text = re.sub(r"FunctionReference=\([^\n]*\)", f'FunctionReference=(MemberName="{name}",bSelfContext=True)', node.text, 1)
        node.mutate_pin("self", lambda line: re.sub(r'PinType.PinSubCategoryObject="/Script/Engine.BlueprintGeneratedClass\'[^\']+\'"', f"PinType.PinSubCategoryObject={TARGET}", line, 1))
        return node

    def diagnostic(message: str, x: int, y: int):
        node = add_form(f"diagnostic_{len(builder.nodes)}", "print_string", x, y)
        scalar.set_default(node, "InString", message); scalar.set_default(node, "bPrintToScreen", "false"); scalar.set_default(node, "bPrintToLog", "true")
        return node

    def compare(member: str, left, left_pin: str, x: int, y: int, default: str):
        node = builder.add(f"{member}_{len(builder.nodes)}", "compare", x, y); scalar.retarget_function(node, member)
        for pin in ("A", "B"): pin_kind(node, pin, "real")
        pin_kind(node, "ReturnValue", "bool"); bp.connect(left, left_pin, node, "A"); scalar.set_default(node, "B", default); return node

    def combine(member: str, conditions, x: int, y: int):
        current, current_pin = conditions[0]
        for index, (other, other_pin) in enumerate(conditions[1:]):
            node = builder.add(f"{member}_{len(builder.nodes)}", "compare", x + index * 208, y); scalar.retarget_function(node, member)
            for pin in ("A", "B", "ReturnValue"): pin_kind(node, pin, "bool")
            bp.connect(current, current_pin, node, "A"); bp.connect(other, other_pin, node, "B"); current, current_pin = node, "ReturnValue"
        return current, current_pin

    invalidate = set_value("CameraPlaybackNativeResultValidV1", "bool", 256, 5440, "false")
    failure = set_value("CameraPlaybackNativeFailureCodeV1", "string", 480, 5440, "native_apply_failed")
    bp.connect(builder.entry, "then", invalidate, "execute"); bp.connect(invalidate, "then", failure, "execute")

    camera_ref = add_form("camera_ref", "camera_ref", 0, 0)
    component = add_form("component", "component", 256, 160)
    internal = 'VariableReference=(MemberName="DroneCamera",bSelfContext=True)'
    external = f'VariableReference=(MemberParent="{DRONE_CAMERA_CLASS}",MemberName="DroneCamera")'
    if component.text.count(internal) != 1: raise RuntimeError("unexpected component owner")
    component.text = component.text.replace(internal, external); bp.connect(camera_ref, "DroneCameraRef", component, "self")
    actor_valid = add_form("actor_valid", "is_valid", 256, 0); bp.connect(camera_ref, "DroneCameraRef", actor_valid, "Object")
    component_valid = add_form("component_valid", "is_valid", 512, 160); bp.connect(component, "DroneCamera", component_valid, "Object")
    authority = []
    for index, name in enumerate(("CameraPlaybackNativePreflightValidV1", "CameraPlaybackNativeSessionActiveV1", "CameraApplyScratchStageValidV1", "CameraApplySessionActiveV1")):
        source = get(name, "bool", 0, 480 + index * 160); authority.append((source, name))
    ready = combine("BooleanAND", [(actor_valid, "ReturnValue"), (component_valid, "ReturnValue"), *authority], 768, 720)
    apply_guard = builder.add("apply_guard", "branch", 704, 5440); bp.connect(failure, "then", apply_guard, "execute"); bp.connect(*ready, apply_guard, "Condition")

    position = get("CameraPlaybackNativeInputPositionV1", "vector", 0, 1280)
    body = get("CameraPlaybackNativeInputBodyWorldQuatV1", "quat", 0, 1440)
    relative = get("CameraPlaybackNativeInputGimbalRelativeQuatV1", "quat", 0, 1600)
    baseline_actor = get("CameraPlaybackNativeBaselineActorTransformV1", "transform", 0, 1920)
    break_actor = add_form("break_actor_baseline", "break_transform", 320, 1920); bp.connect(baseline_actor, "CameraPlaybackNativeBaselineActorTransformV1", break_actor, "InTransform")
    body_rotator = add_form("body_rotator", "quat_rotator", 320, 1440); collapse_pin(body_rotator, "Q"); bp.connect(body, "CameraPlaybackNativeInputBodyWorldQuatV1", body_rotator, "Q")
    relative_rotator = add_form("relative_rotator", "quat_rotator", 320, 1600); collapse_pin(relative_rotator, "Q"); bp.connect(relative, "CameraPlaybackNativeInputGimbalRelativeQuatV1", relative_rotator, "Q")
    desired_actor = add_form("desired_actor", "make_transform", 640, 1920)
    bp.connect(position, "CameraPlaybackNativeInputPositionV1", desired_actor, "Location"); bp.connect(body_rotator, "ReturnValue", desired_actor, "Rotation"); bp.connect(break_actor, "Scale", desired_actor, "Scale")

    actor_set = add_form("actor_set", "actor_set", 928, 5440); bp.connect(camera_ref, "DroneCameraRef", actor_set, "self"); bp.connect(desired_actor, "ReturnValue", actor_set, "NewTransform"); scalar.set_default(actor_set, "bTeleport", "true")
    bp.connect(apply_guard, "then", actor_set, "execute")

    component_set = add_form("component_set", "actor_set", 1376, 5440)
    component_set.text = component_set.text.replace('MemberParent="/Script/CoreUObject.Class\'/Script/Engine.Actor\'",MemberName="K2_SetActorTransform"', 'MemberParent="/Script/CoreUObject.Class\'/Script/Engine.SceneComponent\'",MemberName="K2_SetRelativeRotation"')
    component_set.mutate_pin("self", lambda line: re.sub(r'PinType.PinSubCategoryObject="/Script/CoreUObject.Class\'/Script/Engine.Actor\'"', 'PinType.PinSubCategoryObject="/Script/CoreUObject.Class\'/Script/Engine.SceneComponent\'"', line, 1))
    remove_pin(component_set, "ReturnValue"); rename_pin(component_set, "NewTransform", "NewRotation"); pin_kind(component_set, "NewRotation", "rotator"); bp.connect(component, "DroneCamera", component_set, "self"); bp.connect(relative_rotator, "ReturnValue", component_set, "NewRotation"); scalar.set_default(component_set, "bTeleport", "true")
    bp.connect(actor_set, "then", component_set, "execute")

    observed_actor = add_form("observed_actor", "actor_get", 960, 2240); bp.connect(camera_ref, "DroneCameraRef", observed_actor, "self")
    break_observed_actor = add_form("break_observed_actor", "break_transform", 1216, 2240); bp.connect(observed_actor, "ReturnValue", break_observed_actor, "InTransform")
    position_error = add_form("position_error", "vector_distance", 1472, 2240)
    bp.connect(break_observed_actor, "Location", position_error, "V1"); bp.connect(position, "CameraPlaybackNativeInputPositionV1", position_error, "V2")
    position_ready = compare("LessEqual_DoubleDouble", position_error, "ReturnValue", 1728, 2240, "0.001000")
    body_ready = add_form("body_ready", "rotator_equal", 1728, 2480)
    bp.connect(break_observed_actor, "Rotation", body_ready, "A"); bp.connect(body_rotator, "ReturnValue", body_ready, "B"); scalar.set_default(body_ready, "ErrorTolerance", "0.000100")

    observed = add_form("observed_component", "actor_get", 960, 2720)
    observed.text = observed.text.replace('MemberParent="/Script/CoreUObject.Class\'/Script/Engine.Actor\'",MemberName="GetTransform"', 'MemberParent="/Script/CoreUObject.Class\'/Script/Engine.SceneComponent\'",MemberName="GetRelativeTransform"')
    observed.mutate_pin("self", lambda line: re.sub(r'PinType.PinSubCategoryObject="/Script/CoreUObject.Class\'/Script/Engine.Actor\'"', 'PinType.PinSubCategoryObject="/Script/CoreUObject.Class\'/Script/Engine.SceneComponent\'"', line, 1)); bp.connect(component, "DroneCamera", observed, "self")
    observed.mutate_pin(
        "ReturnValue",
        lambda line: line.replace("PinType.bIsReference=True", "PinType.bIsReference=False").replace(
            "PinType.bIsConst=True", "PinType.bIsConst=False"
        ),
    )
    break_observed = add_form("break_observed", "break_transform", 1216, 2720); bp.connect(observed, "ReturnValue", break_observed, "InTransform")
    relative_ready = add_form("relative_ready", "rotator_equal", 1728, 2880)
    bp.connect(break_observed, "Rotation", relative_ready, "A"); bp.connect(relative_rotator, "ReturnValue", relative_ready, "B"); scalar.set_default(relative_ready, "ErrorTolerance", "0.000001")
    position_guard = builder.add("position_guard", "branch", 1600, 5440); bp.connect(component_set, "then", position_guard, "execute"); bp.connect(position_ready, "ReturnValue", position_guard, "Condition")
    body_guard = builder.add("body_guard", "branch", 1824, 5440); bp.connect(position_guard, "then", body_guard, "execute"); bp.connect(body_ready, "ReturnValue", body_guard, "Condition")
    relative_guard = builder.add("relative_guard", "branch", 2048, 5440); bp.connect(body_guard, "then", relative_guard, "execute"); bp.connect(relative_ready, "ReturnValue", relative_guard, "Condition")
    position_failure = diagnostic("EDD_CAMERA_PLAYBACK_NATIVE_APPLY|POSE_POSITION_READBACK_FAILED", 1824, 5760)
    body_failure = diagnostic("EDD_CAMERA_PLAYBACK_NATIVE_APPLY|POSE_BODY_READBACK_FAILED", 2048, 5920)
    relative_failure = diagnostic("EDD_CAMERA_PLAYBACK_NATIVE_APPLY|POSE_GIMBAL_READBACK_FAILED", 2272, 6080)
    bp.connect(position_guard, "else", position_failure, "execute"); bp.connect(body_guard, "else", body_failure, "execute"); bp.connect(relative_guard, "else", relative_failure, "execute")

    engine_apply = self_call("ApplyCameraEngineFrameV1", 2272, 5440); bp.connect(relative_guard, "then", engine_apply, "execute")
    engine_result = get("CameraApplyResultValidV1", "bool", 5120, 5120)
    engine_guard = builder.add("engine_guard", "branch", 2496, 5440); bp.connect(engine_apply, "then", engine_guard, "execute"); bp.connect(engine_result, "CameraApplyResultValidV1", engine_guard, "Condition")
    engine_failure = diagnostic("EDD_CAMERA_PLAYBACK_NATIVE_APPLY|ENGINE_READBACK_FAILED", 2720, 6240)
    restore = self_call("RestoreCameraPlaybackNativeStateV1", 2944, 6080)
    for failure_node in (position_failure, body_failure, relative_failure, engine_failure): bp.connect(failure_node, "then", restore, "execute")
    bp.connect(engine_guard, "else", engine_failure, "execute")

    count = get("CameraPlaybackNativeAppliedFrameCountV1", "int", 5120, 5280)
    increment = add_form("increment", "add_int", 5344, 5280)
    for pin in ("A", "B", "ReturnValue"): pin_kind(increment, pin, "int")
    scalar.set_default(increment, "B", "1"); bp.connect(count, "CameraPlaybackNativeAppliedFrameCountV1", increment, "A")
    count_set = builder.add("set_count", "set", 2272, 5440); variable(count_set, "CameraPlaybackNativeAppliedFrameCountV1", "int"); bp.connect(increment, "ReturnValue", count_set, "CameraPlaybackNativeAppliedFrameCountV1")
    clear = set_value("CameraPlaybackNativeFailureCodeV1", "string", 2496, 5440, "")
    publish = set_value("CameraPlaybackNativeResultValidV1", "bool", 2720, 5440, "true")
    bp.connect(engine_guard, "then", count_set, "execute"); bp.connect(count_set, "then", clear, "execute"); bp.connect(clear, "then", publish, "execute")

    args.output.parent.mkdir(parents=True, exist_ok=True); args.output.write_text("\n".join(node.text for node in builder.nodes) + "\n", encoding="utf-8")
    if args.paste_output:
        args.paste_output.parent.mkdir(parents=True, exist_ok=True); args.paste_output.write_text("\n".join(re.sub(r',LinkedTo=\(K2Node_FunctionEntry_0 [0-9A-F]{32},\)', "", node.text) for node in builder.nodes[1:]) + "\n", encoding="utf-8")


if __name__ == "__main__": main()
