"""Integrate Clean Frame restoration and the F7 cinematic shortcut.

The exit graph restores every Clean Frame-owned surface before preview teardown
and view restoration.  The client tick polls F7 after ownership, Drone Mode,
and camera-validity guards but before playback arbitration, so the toggle stays
available during playback without leaking outside the local drone session.
"""

from __future__ import annotations

import argparse
import importlib.util
import re
import sys
import uuid
from pathlib import Path


def load_module(path: Path, name: str):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load helpers: {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def set_explicit_default(h, block: str, pin_name: str, value: str) -> str:
    pin_id = h.pin_map(block)[pin_name]
    lines = block.splitlines()
    for index, line in enumerate(lines):
        if f"PinId={pin_id}" not in line:
            continue
        lines[index] = re.sub(
            r'(?<!Autogenerated)DefaultValue="[^"]*"',
            f'DefaultValue="{value}"',
            line,
            count=1,
        )
        return "\n".join(lines)
    raise RuntimeError(f"Could not set {h.block_name(block)}.{pin_name}")


def retarget_self_call(block: str, function_name: str) -> str:
    return re.sub(
        r"FunctionReference=\([^\r\n]+\)",
        f'FunctionReference=(MemberName="{function_name}",bSelfContext=True)',
        block,
        count=1,
    )


def remove_link(h, block: str, pin_name: str, other_name: str) -> str:
    pin_id = h.pin_map(block)[pin_name]
    lines = block.splitlines()
    for index, line in enumerate(lines):
        if f"PinId={pin_id}" not in line:
            continue
        linked = re.search(r",LinkedTo=\((?P<links>[^)]*)\)", line)
        if linked is None:
            raise RuntimeError(f"{h.block_name(block)}.{pin_name} has no link")
        links = re.findall(r"([A-Za-z0-9_]+) ([0-9A-F]{32}),", linked.group("links"))
        kept = [(name, identifier) for name, identifier in links if name != other_name]
        if len(kept) == len(links):
            raise RuntimeError(f"{h.block_name(block)}.{pin_name} is not linked to {other_name}")
        replacement = ""
        if kept:
            replacement = ",LinkedTo=(" + "".join(
                f"{name} {identifier}," for name, identifier in kept
            ) + ")"
        lines[index] = line[: linked.start()] + replacement + line[linked.end() :]
        return "\n".join(lines)
    raise RuntimeError(f"Could not find {h.block_name(block)}.{pin_name}")


def build_exit(root: Path, output: Path) -> None:
    preview = load_module(
        root / "tools" / "blueprint" / "Build-PathPreviewIntegrationGraphs.py",
        "edd_clean_frame_exit_helpers",
    )
    snippets = root / "tools" / "blueprint" / "snippets"
    graph = preview.Graph(
        "ExitDroneMode",
        preview.read_graph(snippets / "exit-drone-mode-preview.eddgraph"),
        preview.call_template(snippets),
    )
    if graph.calls("ExitCleanFrameV1"):
        raise RuntimeError("ExitDroneMode already contains Clean Frame restoration")
    destroy = graph.calls("DestroyPathPreviewV1")
    if len(destroy) != 1:
        raise RuntimeError(f"Expected one preview destroy call; found {len(destroy)}")
    inserted = graph.insert_after(graph.entry(), "ExitCleanFrameV1", shift_downstream=True)
    if preview.pin_links(graph.blocks[inserted], "then")[0][0] != destroy[0]:
        raise RuntimeError("Clean Frame restoration must precede preview destruction")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(graph.full_text(), encoding="utf-8")
    output.with_name(output.stem + "-paste.eddgraph").write_text(
        graph.paste_text(), encoding="utf-8"
    )


def build_dispatch(root: Path, output: Path) -> None:
    h = load_module(
        root / "tools" / "blueprint" / "Build-WaypointFeedbackDispatch.py",
        "edd_clean_frame_dispatch_helpers",
    )
    source = root / "tools" / "blueprint" / "snippets" / "client-director-event-graph.eddgraph"
    text = source.read_text(encoding="utf-8-sig")
    if 'DefaultValue="F7"' in text or 'MemberName="ToggleCleanFrameV1"' in text:
        raise RuntimeError("Input already contains a Clean Frame dispatch")
    source_blocks = [match.group(0) for match in h.BLOCK_RE.finditer(text)]
    blocks = {h.block_name(block): block for block in source_blocks}
    used_ids = set(re.findall(r"(?:NodeGuid=|PinId=)([0-9A-F]{32})", text))
    counter = 0

    def new_id() -> str:
        nonlocal counter
        while True:
            counter += 1
            candidate = uuid.uuid5(
                uuid.NAMESPACE_URL,
                f"exile-drone-director:clean-frame-dispatch:{counter}",
            ).hex.upper()
            if candidate not in used_ids:
                used_ids.add(candidate)
                return candidate

    h.new_id = new_id
    staged = text
    poll_name = h.next_name(staged, "K2Node_CallFunction")
    staged += f' Name="{poll_name}"'
    branch_name = h.next_name(staged, "K2Node_IfThenElse")
    staged += f' Name="{branch_name}"'
    toggle_name = h.next_name(staged, "K2Node_CallFunction")

    poll_template = h.find_one(source_blocks, 'DefaultValue="P"')
    branch_template = blocks["K2Node_IfThenElse_9"]
    call_template = h.find_one(source_blocks, 'MemberName="CaptureCurrentWaypoint"')
    poll = h.clone_node(poll_template, poll_name, 2144, -640)
    poll = set_explicit_default(h, poll, "Key", "F7")
    branch = h.clone_node(branch_template, branch_name, 2400, -640)
    toggle = h.clone_node(call_template, toggle_name, 2656, -768)
    toggle = retarget_self_call(toggle, "ToggleCleanFrameV1")
    blocks.update({poll_name: poll, branch_name: branch, toggle_name: toggle})

    controller = blocks["K2Node_CallFunction_15"]
    camera_guard = blocks["K2Node_IfThenElse_4"]
    playback_dispatch = blocks["K2Node_IfThenElse_9"]
    controller_name = h.block_name(controller)
    camera_name = h.block_name(camera_guard)
    playback_name = h.block_name(playback_dispatch)
    blocks[camera_name] = remove_link(h, blocks[camera_name], "then", playback_name)
    blocks[playback_name] = remove_link(h, blocks[playback_name], "execute", camera_name)

    h.connect(blocks, controller_name, "ReturnValue", poll_name, "self")
    h.connect(blocks, camera_name, "then", branch_name, "execute")
    h.connect(blocks, poll_name, "ReturnValue", branch_name, "Condition")
    h.connect(blocks, branch_name, "then", toggle_name, "execute")
    h.connect(blocks, branch_name, "else", playback_name, "execute")

    output.parent.mkdir(parents=True, exist_ok=True)
    ordered = [blocks[h.block_name(block)] for block in source_blocks]
    ordered.extend((blocks[poll_name], blocks[branch_name], blocks[toggle_name]))
    output.write_text("\n".join(ordered) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-root", type=Path, required=True)
    parser.add_argument("--exit-output", type=Path, required=True)
    parser.add_argument("--dispatch-output", type=Path, required=True)
    args = parser.parse_args()
    build_exit(args.project_root, args.exit_output)
    build_dispatch(args.project_root, args.dispatch_output)
    print("Built Clean Frame exit and F7 dispatch graphs")


if __name__ == "__main__":
    main()
