"""Generate strict staged Blueprint record-envelope decoder graphs.

The decoder preserves the complete source envelope, projects every field into
the repository actor's typed scratch members, then calls the accepted encoder
and commits ``ScratchValidV1`` only when the regenerated canonical text matches
byte-for-byte.  Optional published and attribution objects are isolated in
small helpers so null/object branching never needs an unsafe execution merge.
"""

from __future__ import annotations

import argparse
import copy
import importlib.util
from pathlib import Path
import re
import sys


def load_document_decoder(project_root: Path):
    path = project_root / "tools" / "blueprint" / "Build-RepositoryDocumentDecoderGraphs.py"
    spec = importlib.util.spec_from_file_location("edd_record_decoder_base", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load document decoder helpers: {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def load_templates(project_root: Path, bp, dec, enc) -> dict[str, str]:
    templates = dec.load_templates(project_root, bp, enc)
    forms = bp.read_blocks(
        project_root / "tools" / "blueprint" / "templates" / "repository-json-node-forms.eddgraph"
    )
    get_type_string = bp.find_block(forms, r'MemberName="IsNull"')
    get_type_string = get_type_string.replace('MemberName="IsNull"', 'MemberName="GetTypeString"')
    get_type_string = get_type_string.replace(
        'PinType.PinCategory="bool"', 'PinType.PinCategory="string"'
    ).replace('DefaultValue="false",AutogeneratedDefaultValue="false",', "")
    templates.update(
        {
            "json_GetField": bp.find_block(forms, r'MemberName="GetField"'),
            "json_GetTypeString": get_type_string,
            "json_IsNull": bp.find_block(forms, r'MemberName="IsNull"'),
        }
    )
    return templates


def connect_exec_chain(bp, nodes) -> None:
    for left, right in zip(nodes, nodes[1:]):
        bp.connect(left, "then", right, "execute")


def fold_record_paste_layout(nodes):
    """Keep the wide root decoder close to its native entry when pasted.

    Unreal centers a pasted selection on its bounding box.  The production
    record decoder is intentionally a long ordered chain, so its first node
    otherwise lands thousands of graph units away from the native function
    entry.  Fold only the paste representation into alternating rows; links
    and node identities remain byte-for-byte unchanged.
    """

    folded = copy.deepcopy(nodes)
    row_width = 1536
    row_height = 960
    for node in folded:
        x_match = re.search(r"(?m)^\s*NodePosX=(-?\d+)$", node.text)
        y_match = re.search(r"(?m)^\s*NodePosY=(-?\d+)$", node.text)
        if x_match is None or y_match is None:
            raise RuntimeError(f"Node {node.key} is missing layout coordinates")
        x = int(x_match.group(1))
        y = int(y_match.group(1))
        if x < 0:
            raise RuntimeError(f"Root decoder node {node.key} has negative X coordinate {x}")
        row, column_x = divmod(x, row_width)
        if row == 0:
            row_y = 0
        else:
            magnitude = ((row + 1) // 2) * row_height
            row_y = magnitude if row % 2 else -magnitude
        node.text = re.sub(r"(?m)^(\s*NodePosX=)-?\d+$", rf"\g<1>{column_x}", node.text)
        node.text = re.sub(r"(?m)^(\s*NodePosY=)-?\d+$", rf"\g<1>{y + row_y}", node.text)
    return folded


def field(enc, node, name: str) -> None:
    enc.field(node, name)


def build_published_fields(bp, templates: dict[str, str], enc):
    b = enc.Builder(bp, templates, "DecodeRecordPublishedFieldsV1")
    record = b.getter("ScratchRecordJsonV1", "json", 0, 480)
    published_value = b.json("GetField", 256, 480)
    field(enc, published_value, "published")
    is_null = b.json("IsNull", 512, 480)
    branch = b.add("published_null_branch", "branch", 768, 0)
    bp.connect(record, "ScratchRecordJsonV1", published_value, "self")
    bp.connect(published_value, "ReturnValue", is_null, "self")
    bp.connect(is_null, "ReturnValue", branch, "Condition")

    absent = b.setter("ScratchRecordHasPublishedRevisionV1", "bool", 1024, 320)
    enc.set_default(absent, "ScratchRecordHasPublishedRevisionV1", "false")

    present = b.setter("ScratchRecordHasPublishedRevisionV1", "bool", 1024, 0)
    enc.set_default(present, "ScratchRecordHasPublishedRevisionV1", "true")
    published_object = b.json("GetObjectField", 1024, 560)
    field(enc, published_object, "published")
    encode_document = b.json("EncodeJson", 1280, 560)
    encoded_document = b.setter("ScratchEncodedDocumentV1", "string", 1280, 0)
    decode_document = b.call("DecodeDocumentV1", 1536, 0)
    decoded_document = b.getter("ScratchDocumentV1", "document", 1536, 480)
    store_document = b.setter("ScratchRecordPublishedDocumentV1", "document", 1792, 0)
    revision = b.json("GetNumberField", 1792, 480)
    field(enc, revision, "publishedRevisionNumber")
    revision_int = b.add("published_revision_int", "float_to_int", 2048, 480)
    store_revision = b.setter("ScratchRecordPublishedRevisionNumberV1", "int", 2048, 0)

    bp.connect(record, "ScratchRecordJsonV1", published_object, "self")
    bp.connect(published_object, "ReturnValue", encode_document, "self")
    bp.connect(encode_document, "ReturnValue", encoded_document, "ScratchEncodedDocumentV1")
    bp.connect(decoded_document, "ScratchDocumentV1", store_document, "ScratchRecordPublishedDocumentV1")
    bp.connect(record, "ScratchRecordJsonV1", revision, "self")
    bp.connect(revision, "ReturnValue", revision_int, "A")
    bp.connect(revision_int, "ReturnValue", store_revision, "ScratchRecordPublishedRevisionNumberV1")

    bp.connect(b.entry, "then", branch, "execute")
    bp.connect(branch, "then", absent, "execute")
    bp.connect(branch, "else", present, "execute")
    connect_exec_chain(bp, [present, encoded_document, decode_document, store_document, store_revision])
    return b.nodes


def build_source_attribution(bp, templates: dict[str, str], enc):
    b = enc.Builder(bp, templates, "DecodeRecordSourceAttributionV1")
    record = b.getter("ScratchRecordJsonV1", "json", 0, 480)
    source_value = b.json("GetField", 256, 480)
    field(enc, source_value, "sourceAttribution")
    is_null = b.json("IsNull", 512, 480)
    branch = b.add("source_null_branch", "branch", 768, 0)
    bp.connect(record, "ScratchRecordJsonV1", source_value, "self")
    bp.connect(source_value, "ReturnValue", is_null, "self")
    bp.connect(is_null, "ReturnValue", branch, "Condition")

    absent = b.setter("ScratchRecordHasSourceAttributionV1", "bool", 1024, 320)
    enc.set_default(absent, "ScratchRecordHasSourceAttributionV1", "false")

    present = b.setter("ScratchRecordHasSourceAttributionV1", "bool", 1024, 0)
    enc.set_default(present, "ScratchRecordHasSourceAttributionV1", "true")
    source_object = b.json("GetObjectField", 1024, 560)
    field(enc, source_object, "sourceAttribution")
    store_source = b.setter("ScratchAttributionJsonV1", "json", 1280, 0)
    source = b.getter("ScratchAttributionJsonV1", "json", 1280, 560)
    bp.connect(record, "ScratchRecordJsonV1", source_object, "self")
    bp.connect(source_object, "ReturnValue", store_source, "ScratchAttributionJsonV1")

    stages = []
    x = 1536
    for json_name, variable_name in (
        ("flypathId", "ScratchRecordSourceFlypathIdV1"),
        ("title", "ScratchRecordSourceTitleV1"),
        ("creatorDisplayName", "ScratchRecordSourceCreatorDisplayNameV1"),
    ):
        getter = b.json("GetStringField", x, 480)
        field(enc, getter, json_name)
        setter = b.setter(variable_name, "string", x, 0)
        bp.connect(source, "ScratchAttributionJsonV1", getter, "self")
        bp.connect(getter, "ReturnValue", setter, variable_name)
        stages.append(setter)
        x += 256

    revision = b.json("GetNumberField", x, 480)
    field(enc, revision, "revisionNumber")
    revision_int = b.add("source_revision_int", "float_to_int", x + 256, 480)
    store_revision = b.setter("ScratchRecordSourceRevisionNumberV1", "int", x + 256, 0)
    bp.connect(source, "ScratchAttributionJsonV1", revision, "self")
    bp.connect(revision, "ReturnValue", revision_int, "A")
    bp.connect(revision_int, "ReturnValue", store_revision, "ScratchRecordSourceRevisionNumberV1")

    bp.connect(b.entry, "then", branch, "execute")
    bp.connect(branch, "then", absent, "execute")
    bp.connect(branch, "else", present, "execute")
    connect_exec_chain(bp, [present, store_source, *stages, store_revision])
    return b.nodes


def build_record(bp, templates: dict[str, str], enc):
    b = enc.Builder(bp, templates, "DecodeRecordV1")
    valid_reset = b.setter("ScratchValidV1", "bool", 0, 0)
    enc.set_default(valid_reset, "ScratchValidV1", "false")
    encoded_input = b.getter("ScratchEncodedRecordV1", "string", 0, 480)
    source_store = b.setter("ScratchSourceRecordJsonV1", "string", 256, 0)
    bp.connect(encoded_input, "ScratchEncodedRecordV1", source_store, "ScratchSourceRecordJsonV1")

    envelope = b.json("ConstructJsonObject", 256, 480)
    envelope_store = b.setter("ScratchEnvelopeJsonV1", "json", 512, 0)
    decode = b.json("DecodeJson", 768, 0)
    decode_guard = b.add("decode_guard", "branch", 1024, 0)
    bp.connect(envelope, "ReturnValue", envelope_store, "ScratchEnvelopeJsonV1")
    bp.connect(envelope_store, "Output_Get", decode, "self")
    bp.connect(source_store, "Output_Get", decode, "JsonString")
    bp.connect(decode, "ReturnValue", decode_guard, "Condition")

    envelope_source = b.getter("ScratchEnvelopeJsonV1", "json", 768, 640)
    record_value = b.json("GetField", 1280, 640)
    field(enc, record_value, "record")
    record_type = b.json("GetTypeString", 1536, 640)
    record_type_equal = b.add("record_type_equal", "equal_string", 1792, 480)
    enc.set_default(record_type_equal, "B", "Object")
    record_guard = b.add("record_object_guard", "branch", 2048, 0)
    bp.connect(envelope_source, "ScratchEnvelopeJsonV1", record_value, "self")
    bp.connect(record_value, "ReturnValue", record_type, "self")
    bp.connect(record_type, "ReturnValue", record_type_equal, "A")
    bp.connect(record_type_equal, "ReturnValue", record_guard, "Condition")

    record_object = b.json("GetObjectField", 2048, 640)
    field(enc, record_object, "record")
    record_store = b.setter("ScratchRecordJsonV1", "json", 2304, 0)
    record = b.getter("ScratchRecordJsonV1", "json", 2560, 640)
    bp.connect(envelope_source, "ScratchEnvelopeJsonV1", record_object, "self")
    bp.connect(record_object, "ReturnValue", record_store, "ScratchRecordJsonV1")

    chain = [record_store]
    x = 2560
    string_stages = (
        ("createdUtc", "ScratchRecordCreatedUtcV1"),
        ("description", "ScratchRecordDescriptionV1"),
    )
    for json_name, variable_name in string_stages:
        getter = b.json("GetStringField", x, 480)
        field(enc, getter, json_name)
        setter = b.setter(variable_name, "string", x, 0)
        bp.connect(record, "ScratchRecordJsonV1", getter, "self")
        bp.connect(getter, "ReturnValue", setter, variable_name)
        chain.append(setter)
        x += 256

    draft = b.json("GetObjectField", x, 640)
    field(enc, draft, "draft")
    draft_encode = b.json("EncodeJson", x + 256, 640)
    encoded_document = b.setter("ScratchEncodedDocumentV1", "string", x, 0)
    decode_document = b.call("DecodeDocumentV1", x + 256, 0)
    decoded_document = b.getter("ScratchDocumentV1", "document", x + 512, 640)
    store_document = b.setter("ScratchRecordDraftDocumentV1", "document", x + 512, 0)
    bp.connect(record, "ScratchRecordJsonV1", draft, "self")
    bp.connect(draft, "ReturnValue", draft_encode, "self")
    bp.connect(draft_encode, "ReturnValue", encoded_document, "ScratchEncodedDocumentV1")
    bp.connect(decoded_document, "ScratchDocumentV1", store_document, "ScratchRecordDraftDocumentV1")
    chain.extend((encoded_document, decode_document, store_document))
    x += 768

    draft_revision = b.json("GetNumberField", x, 480)
    field(enc, draft_revision, "draftRevisionNumber")
    draft_revision_int = b.add("draft_revision_int", "float_to_int", x + 256, 480)
    store_draft_revision = b.setter("ScratchRecordDraftRevisionNumberV1", "int", x + 256, 0)
    bp.connect(record, "ScratchRecordJsonV1", draft_revision, "self")
    bp.connect(draft_revision, "ReturnValue", draft_revision_int, "A")
    bp.connect(
        draft_revision_int,
        "ReturnValue",
        store_draft_revision,
        "ScratchRecordDraftRevisionNumberV1",
    )
    chain.append(store_draft_revision)
    x += 512

    for json_name, variable_name in (
        ("flypathId", "ScratchRecordFlypathIdV1"),
        ("ownerAccountId", "ScratchRecordOwnerAccountIdV1"),
        ("ownerDisplayName", "ScratchRecordOwnerDisplayNameV1"),
    ):
        getter = b.json("GetStringField", x, 480)
        field(enc, getter, json_name)
        setter = b.setter(variable_name, "string", x, 0)
        bp.connect(record, "ScratchRecordJsonV1", getter, "self")
        bp.connect(getter, "ReturnValue", setter, variable_name)
        chain.append(setter)
        x += 256

    published = b.call("DecodeRecordPublishedFieldsV1", x, 0)
    chain.append(published)
    x += 256

    region = b.json("GetStringField", x, 480)
    field(enc, region, "regionId")
    store_region = b.setter("ScratchRecordRegionIdV1", "string", x, 0)
    bp.connect(record, "ScratchRecordJsonV1", region, "self")
    bp.connect(region, "ReturnValue", store_region, "ScratchRecordRegionIdV1")
    chain.append(store_region)
    x += 256

    source = b.call("DecodeRecordSourceAttributionV1", x, 0)
    chain.append(source)
    x += 256

    for json_name, variable_name in (
        ("title", "ScratchRecordTitleV1"),
        ("updatedUtc", "ScratchRecordUpdatedUtcV1"),
        ("visibility", "ScratchRecordVisibilityV1"),
    ):
        getter = b.json("GetStringField", x, 480)
        field(enc, getter, json_name)
        setter = b.setter(variable_name, "string", x, 0)
        bp.connect(record, "ScratchRecordJsonV1", getter, "self")
        bp.connect(getter, "ReturnValue", setter, variable_name)
        chain.append(setter)
        x += 256

    encode_record = b.call("EncodeRecordV1", x, 0)
    source_record = b.getter("ScratchSourceRecordJsonV1", "string", x, 480)
    canonical_record = b.getter("ScratchEncodedRecordV1", "string", x + 256, 640)
    equal = b.add("canonical_record_equal", "equal_string", x + 512, 480)
    valid = b.setter("ScratchValidV1", "bool", x + 768, 0)
    bp.connect(source_record, "ScratchSourceRecordJsonV1", equal, "A")
    bp.connect(canonical_record, "ScratchEncodedRecordV1", equal, "B")
    bp.connect(equal, "ReturnValue", valid, "ScratchValidV1")
    chain.extend((encode_record, valid))

    bp.connect(b.entry, "then", valid_reset, "execute")
    connect_exec_chain(bp, [valid_reset, source_store, envelope_store, decode])
    bp.connect(decode, "then", decode_guard, "execute")
    bp.connect(decode_guard, "then", record_guard, "execute")
    bp.connect(record_guard, "then", chain[0], "execute")
    connect_exec_chain(bp, chain)
    return b.nodes


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-root", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--paste-dir", type=Path)
    args = parser.parse_args()

    dec = load_document_decoder(args.project_root)
    enc = dec.load_encoder(args.project_root)
    bp = enc.load_helpers(args.project_root)
    templates = load_templates(args.project_root, bp, dec, enc)
    graphs = {
        "decode-record-published-fields-v1.eddgraph": build_published_fields(bp, templates, enc),
        "decode-record-source-attribution-v1.eddgraph": build_source_attribution(bp, templates, enc),
        "decode-record-v1.eddgraph": build_record(bp, templates, enc),
    }
    for filename, nodes in graphs.items():
        enc.write(nodes, args.output_dir / filename, paste=False)
        if args.paste_dir:
            paste_name = filename.replace(".eddgraph", "-paste.eddgraph")
            paste_nodes = fold_record_paste_layout(nodes) if filename == "decode-record-v1.eddgraph" else nodes
            enc.write(paste_nodes, args.paste_dir / paste_name, paste=True)


if __name__ == "__main__":
    main()
