"""Add P-toggle linear playback arbitration and exit cleanup to the client tick."""

from __future__ import annotations

import argparse
import importlib.util
import re
import sys
import uuid
from pathlib import Path


def load_helpers():
    path = Path(__file__).with_name("Build-WaypointFeedbackDispatch.py")
    spec = importlib.util.spec_from_file_location("edd_dispatch_helpers", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load dispatch helpers: {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def remove_link(h, block: str, pin_name: str, other_name: str) -> str:
    pin_id = h.pin_map(block)[pin_name]
    lines = block.splitlines()
    for index, line in enumerate(lines):
        if f"PinId={pin_id}" not in line:
            continue
        linked = re.search(r",LinkedTo=\((?P<links>[^)]*)\)", line)
        if linked is None:
            raise RuntimeError(f"{h.block_name(block)}.{pin_name} has no link to remove")
        links = re.findall(r"([A-Za-z0-9_]+) ([0-9A-F]{32}),", linked.group("links"))
        filtered = [(name, identifier) for name, identifier in links if name != other_name]
        if len(filtered) == len(links):
            raise RuntimeError(f"{h.block_name(block)}.{pin_name} is not linked to {other_name}")
        replacement = ""
        if filtered:
            replacement = ",LinkedTo=(" + "".join(f"{name} {identifier}," for name, identifier in filtered) + ")"
        lines[index] = line[: linked.start()] + replacement + line[linked.end() :]
        return "\n".join(lines)
    raise RuntimeError(f"Could not find {h.block_name(block)}.{pin_name}")


def set_explicit_default(h, block: str, pin_name: str, value: str) -> str:
    pin_id = h.pin_map(block)[pin_name]
    lines = block.splitlines()
    for index, line in enumerate(lines):
        if f"PinId={pin_id}" not in line:
            continue
        lines[index] = re.sub(
            r'(?<!Autogenerated)DefaultValue="[^"]*"',
            f'DefaultValue="{value}"',
            line,
            count=1,
        )
        return "\n".join(lines)
    raise RuntimeError(f"Could not set {h.block_name(block)}.{pin_name}")


def retarget_self_call(block: str, function_name: str) -> str:
    return re.sub(
        r"FunctionReference=\([^\r\n]+\)",
        f'FunctionReference=(MemberName="{function_name}",bSelfContext=True)',
        block,
        count=1,
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    h = load_helpers()
    text = args.input.read_text(encoding="utf-8")

    # The shared helper's UUID stream was also used to build earlier graph
    # slices. Give this generator its own deterministic namespace and reject
    # any accidental collision with identifiers already present in the input.
    used_ids = set(re.findall(r"(?:NodeGuid=|PinId=)([0-9A-F]{32})", text))
    id_counter = 0

    def dispatch_id() -> str:
        nonlocal id_counter
        while True:
            id_counter += 1
            candidate = uuid.uuid5(
                uuid.NAMESPACE_URL,
                f"exile-drone-director:linear-playback-dispatch:{id_counter}",
            ).hex.upper()
            if candidate not in used_ids:
                used_ids.add(candidate)
                return candidate

    h.new_id = dispatch_id
    if 'DefaultValue="P"' in text and 'MemberName="UpdateLinearPlayback"' in text:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_bytes(args.input.read_bytes())
        print("Client graph already contains linear playback dispatch; output unchanged.")
        return
    if any(marker in text for marker in ('MemberName="StartLinearPlayback"', 'MemberName="StopLinearPlayback"', 'MemberName="UpdateLinearPlayback"')):
        raise RuntimeError("Input contains a partial or ambiguous playback dispatch")

    source_blocks = [match.group(0) for match in h.BLOCK_RE.finditer(text)]
    by_name = {h.block_name(block): block for block in source_blocks}
    required = {
        "camera_branch": "K2Node_IfThenElse_4",
        "speed": "K2Node_CallFunction_17",
        "controller": "K2Node_CallFunction_15",
        "mode_branch": "K2Node_IfThenElse_1",
        "f9_branch": "K2Node_IfThenElse_2",
        "manual_emergency": "K2Node_CallFunction_9",
        "invalid_emergency": "K2Node_CallFunction_11",
    }
    for label, name in required.items():
        if name not in by_name:
            raise RuntimeError(f"Input is missing {label}: {name}")

    h.find_one([by_name[required["speed"]]], 'MemberName="UpdateSpeedControls"')
    normal_exit = h.find_one(source_blocks, 'MemberName="ExitDroneMode"')
    required["normal_exit"] = h.block_name(normal_exit)
    h.find_one([by_name[required["manual_emergency"]]], 'MemberName="EmergencyExitDroneMode"')
    h.find_one([by_name[required["invalid_emergency"]]], 'MemberName="EmergencyExitDroneMode"')

    poll_template = h.find_one(source_blocks, 'DefaultValue="K"')
    branch_template = next(
        block for block in source_blocks
        if block.startswith("Begin Object Class=/Script/BlueprintGraph.K2Node_IfThenElse ")
    )
    call_template = h.find_one(source_blocks, 'MemberName="CaptureCurrentWaypoint"')
    playback_forms = [
        match.group(0)
        for match in h.BLOCK_RE.finditer(
            (Path(__file__).resolve().parent / "templates" / "linear-playback-node-forms.eddgraph").read_text(encoding="utf-8-sig")
        )
    ]
    active_template = next(
        block for block in playback_forms
        if block.startswith("Begin Object Class=/Script/BlueprintGraph.K2Node_VariableGet ")
        and 'MemberName="PlaybackActive"' in block
    )

    staged = text
    names = []
    prefixes = (
        "K2Node_CallFunction",  # P poll
        "K2Node_IfThenElse",   # P edge
        "K2Node_VariableGet",  # active
        "K2Node_IfThenElse",   # start/stop choice
        "K2Node_IfThenElse",   # update/manual choice
        "K2Node_CallFunction", # start
        "K2Node_CallFunction", # stop toggle
        "K2Node_CallFunction", # update
        "K2Node_CallFunction", # stop normal exit
        "K2Node_CallFunction", # stop manual emergency
        "K2Node_CallFunction", # stop invalid emergency
    )
    for prefix in prefixes:
        name = h.next_name(staged, prefix)
        staged += f' Name="{name}"'
        names.append(name)
    (
        poll_name,
        p_branch_name,
        active_name,
        toggle_branch_name,
        update_branch_name,
        start_name,
        stop_toggle_name,
        update_name,
        stop_normal_name,
        stop_manual_name,
        stop_invalid_name,
    ) = names

    additions = {
        poll_name: h.clone_node(poll_template, poll_name, 2208, -784),
        p_branch_name: h.clone_node(branch_template, p_branch_name, 2464, -1040),
        active_name: h.clone_node(active_template, active_name, 2464, -656, "StartLinearPlayback"),
        toggle_branch_name: h.clone_node(branch_template, toggle_branch_name, 2720, -1040),
        update_branch_name: h.clone_node(branch_template, update_branch_name, 2720, -784),
        start_name: retarget_self_call(h.clone_node(call_template, start_name, 2976, -912), "StartLinearPlayback"),
        stop_toggle_name: retarget_self_call(h.clone_node(call_template, stop_toggle_name, 2976, -1168), "StopLinearPlayback"),
        update_name: retarget_self_call(h.clone_node(call_template, update_name, 2976, -656), "UpdateLinearPlayback"),
        stop_normal_name: retarget_self_call(h.clone_node(call_template, stop_normal_name, 512, -320), "StopLinearPlayback"),
        stop_manual_name: retarget_self_call(h.clone_node(call_template, stop_manual_name, 1536, -192), "StopLinearPlayback"),
        stop_invalid_name: retarget_self_call(h.clone_node(call_template, stop_invalid_name, 2464, -400), "StopLinearPlayback"),
    }
    additions[poll_name] = set_explicit_default(h, additions[poll_name], "Key", "P")

    blocks = dict(by_name)
    blocks.update(additions)

    def disconnect(left: str, left_pin: str, right: str, right_pin: str) -> None:
        blocks[left] = remove_link(h, blocks[left], left_pin, right)
        blocks[right] = remove_link(h, blocks[right], right_pin, left)

    disconnect(required["camera_branch"], "then", required["speed"], "execute")
    disconnect(required["mode_branch"], "else", required["normal_exit"], "execute")
    disconnect(required["f9_branch"], "then", required["manual_emergency"], "execute")
    disconnect(required["camera_branch"], "else", required["invalid_emergency"], "execute")

    h.connect(blocks, required["camera_branch"], "then", p_branch_name, "execute")
    h.connect(blocks, required["controller"], "ReturnValue", poll_name, "self")
    h.connect(blocks, poll_name, "ReturnValue", p_branch_name, "Condition")
    h.connect(blocks, p_branch_name, "then", toggle_branch_name, "execute")
    h.connect(blocks, active_name, "PlaybackActive", toggle_branch_name, "Condition")
    h.connect(blocks, toggle_branch_name, "then", stop_toggle_name, "execute")
    h.connect(blocks, toggle_branch_name, "else", start_name, "execute")
    h.connect(blocks, p_branch_name, "else", update_branch_name, "execute")
    h.connect(blocks, active_name, "PlaybackActive", update_branch_name, "Condition")
    h.connect(blocks, update_branch_name, "then", update_name, "execute")
    h.connect(blocks, update_branch_name, "else", required["speed"], "execute")

    h.connect(blocks, required["mode_branch"], "else", stop_normal_name, "execute")
    h.connect(blocks, stop_normal_name, "then", required["normal_exit"], "execute")
    h.connect(blocks, required["f9_branch"], "then", stop_manual_name, "execute")
    h.connect(blocks, stop_manual_name, "then", required["manual_emergency"], "execute")
    h.connect(blocks, required["camera_branch"], "else", stop_invalid_name, "execute")
    h.connect(blocks, stop_invalid_name, "then", required["invalid_emergency"], "execute")

    original_names = set(by_name)
    output = [blocks[h.block_name(block)] for block in source_blocks]
    output.extend(blocks[name] for name in additions if name not in original_names)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(output) + "\n", encoding="utf-8")
    print("Added P-toggle linear playback arbitration and exit cleanup.")


if __name__ == "__main__":
    main()
