"""Build complete absolute-time camera channel assembly evaluation."""
from __future__ import annotations
import argparse,importlib.util,re,sys
from pathlib import Path
FUNCTION="EvaluateCameraChannelAssemblyV1";TARGET='"/Script/Engine.BlueprintGeneratedClass\'/Game/Mods/ExileDroneDirector/Core/Client/BPC_EDD_ClientDirector.BPC_EDD_ClientDirector_C\'"'
def load(root):p=root/"tools/blueprint/Build-TrajectoryScalarEvaluatorGraphs.py";s=importlib.util.spec_from_file_location("edd_camera_channel_evaluate_base",p);m=importlib.util.module_from_spec(s);sys.modules[s.name]=m;s.loader.exec_module(m);return m
def kind(n,p,k,array=False):
 cat,sub={"bool":("bool",""),"int":("int",""),"real":("real","double"),"string":("string","")}[k]
 def f(line):line=re.sub(r'PinType.PinCategory="[^"]*"',f'PinType.PinCategory="{cat}"',line,1);line=re.sub(r'PinType.PinSubCategory="[^"]*"',f'PinType.PinSubCategory="{sub}"',line,1);return re.sub(r'PinType.ContainerType=(?:None|Array)',f'PinType.ContainerType={"Array" if array else "None"}',line,1)
 n.mutate_pin(p,f)
def main():
 p=argparse.ArgumentParser();p.add_argument("--project-root",type=Path,required=True);p.add_argument("--output",type=Path,required=True);p.add_argument("--paste-output",type=Path);a=p.parse_args();s=load(a.project_root);bp=s.load_helpers(a.project_root);forms=s.load_templates(a.project_root,bp);b=s.Builder(bp,forms,FUNCTION);calls=bp.read_blocks(a.project_root/"tools/blueprint/snippets/activate-drone-view.eddgraph");loops=bp.read_blocks(a.project_root/"tools/blueprint/templates/adaptive-arc-forloop-node-form.eddgraph");edit=bp.read_blocks(a.project_root/"tools/blueprint/templates/waypoint-edit-node-forms.eddgraph");call_form=bp.find_block(calls,r'MemberName="SwitchToDroneView"');loop_form=bp.find_block(loops,r"StandardMacros:ForLoop");length_form=bp.find_block(edit,r'MemberName="Array_Length"')
 def addform(key,raw,x,y):m=bp.BLOCK_RE.match(raw);cls=m.group("class").rsplit(".",1)[-1];i=b.serial.get(cls,0);b.serial[cls]=i+1;n=bp.Node.clone(key,raw,f"{cls}_{i}",x,y);b.nodes.append(n);return n
 def var(n,name,k,array=False):s.retarget_variable(n,name,"real" if k=="int" else k);kind(n,name,k,array);kind(n,"Output_Get",k,array) if "Output_Get" in n.pins else None
 def get(name,k,x,y,array=False):n=b.add(f"get_{name}_{len(b.nodes)}","get",x,y);var(n,name,k,array);return n
 def setv(name,k,x,y,default=None):n=b.add(f"set_{name}_{len(b.nodes)}","set",x,y);var(n,name,k);s.set_default(n,name,default) if default is not None else None;return n
 def call(name,x,y):n=addform(f"call_{name}_{len(b.nodes)}",call_form,x,y);n.text=re.sub(r"FunctionReference=\([^\n]*\)",f'FunctionReference=(MemberName="{name}",bSelfContext=True)',n.text,1);n.mutate_pin("self",lambda line:re.sub(r'PinType.PinSubCategoryObject="/Script/Engine.BlueprintGeneratedClass\'[^\']+\'"',f"PinType.PinSubCategoryObject={TARGET}",line,1));return n
 def cmp(member,left,leftpin,x,y,right=None,rightpin=None,default=None,k="int"):n=b.add(f"cmp_{member}_{len(b.nodes)}","compare",x,y);s.retarget_function(n,member);kind(n,"A",k);kind(n,"B",k);kind(n,"ReturnValue","bool");bp.connect(left,leftpin,n,"A");bp.connect(right,rightpin,n,"B") if right is not None else s.set_default(n,"B",default);return n
 def math(member,left,leftpin,x,y,default):n=b.math("Add_IntInt",x,y);s.retarget_function(n,member);[kind(n,pin,"int") for pin in ("A","B","ReturnValue")];bp.connect(left,leftpin,n,"A");s.set_default(n,"B",default);return n
 def length(src,pin,x,y):n=addform(f"len_{pin}",length_form,x,y);kind(n,"TargetArray","real",True);kind(n,"ReturnValue","int");bp.connect(src,pin,n,"TargetArray");return n
 reset=call("ResetCameraChannelResultV1",256,1600);bp.connect(b.entry,"then",reset,"execute");compiled=get("CameraChannelCompileValidV1","bool",0,0);query=get("CameraChannelQueryTimeV1","real",0,160);finite=b.finite(query,"CameraChannelQueryTimeV1",256,160);ready=cmp("BooleanAND",compiled,"CameraChannelCompileValidV1",480,80,finite,"ReturnValue",k="bool");guard=b.add("ready_guard","branch",512,1600);bp.connect(reset,"then",guard,"execute");bp.connect(ready,"ReturnValue",guard,"Condition")
 loop=addform("channel_loop",loop_form,768,1600);s.set_default(loop,"FirstIndex","0");s.set_default(loop,"LastIndex","12");bp.connect(guard,"then",loop,"execute");set_index=setv("CameraChannelScratchChannelIndexV1","int",1024,1600);bp.connect(loop,"Index",set_index,"CameraChannelScratchChannelIndexV1");bp.connect(loop,"LoopBody",set_index,"execute");stage=call("StageCompiledCameraChannelV1",1280,1600);publish=call("PublishCameraChannelSampleV1",1536,1600);bp.connect(set_index,"then",stage,"execute");bp.connect(stage,"then",publish,"execute");stage_valid=get("CameraChannelScratchValidV1","bool",1536,480);success_branch=b.add("success_branch","branch",1792,1600);bp.connect(publish,"then",success_branch,"execute");bp.connect(stage_valid,"CameraChannelScratchValidV1",success_branch,"Condition");success_count=get("CameraChannelScratchKeyIndexV1","int",1792,640);increment=math("Add_IntInt",success_count,"CameraChannelScratchKeyIndexV1",2016,640,"1");store_count=setv("CameraChannelScratchKeyIndexV1","int",2016,1600);bp.connect(increment,"ReturnValue",store_count,"CameraChannelScratchKeyIndexV1");bp.connect(success_branch,"then",store_count,"execute")
 result_arrays=[get(name,"real",0,960+i*160,True) for i,name in enumerate(("CameraChannelResultValuesV1","CameraChannelResultVelocitiesV1","CameraChannelResultAccelerationsV1"))];result_lengths=[length(node,name,256,960+i*160) for i,(node,name) in enumerate(zip(result_arrays,("CameraChannelResultValuesV1","CameraChannelResultVelocitiesV1","CameraChannelResultAccelerationsV1")))];final_count=get("CameraChannelScratchKeyIndexV1","int",2240,640);conditions=[cmp("EqualEqual_IntInt",final_count,"CameraChannelScratchKeyIndexV1",2240,960,default="13")];conditions.extend(cmp("EqualEqual_IntInt",node,"ReturnValue",2464+i*224,960,default="13") for i,node in enumerate(result_lengths));final=conditions[0]
 for condition in conditions[1:]:final=cmp("BooleanAND",final,"ReturnValue",3136,960,condition,"ReturnValue",k="bool")
 final_guard=b.add("final_guard","branch",3360,1600);bp.connect(loop,"Completed",final_guard,"execute");bp.connect(final,"ReturnValue",final_guard,"Condition");publications=[]
 for i,(source,target,k) in enumerate((("CameraChannelCompiledFilmbackPresetIdV1","CameraChannelResultFilmbackPresetIdV1","string"),("CameraChannelCompiledFilmbackSensorWidthMmV1","CameraChannelResultFilmbackSensorWidthMmV1","real"),("CameraChannelCompiledFilmbackSensorHeightMmV1","CameraChannelResultFilmbackSensorHeightMmV1","real"))):g=get(source,k,0,1440+i*160);n=setv(target,k,3616+i*256,1600);bp.connect(g,source,n,target);publications.append(n)
 valid=setv("CameraChannelResultValidV1","bool",4384,1600,"true");publications.append(valid);bp.connect(final_guard,"then",publications[0],"execute");[bp.connect(left,"then",right,"execute") for left,right in zip(publications,publications[1:])]
 full="\n".join(n.text for n in b.nodes)+"\n";a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(full,encoding="utf-8")
 if a.paste_output:a.paste_output.parent.mkdir(parents=True,exist_ok=True);a.paste_output.write_text("\n".join(re.sub(r',LinkedTo=\(K2Node_FunctionEntry_0 [0-9A-F]{32},\)',"",n.text) for n in b.nodes[1:])+"\n",encoding="utf-8")
if __name__=="__main__":main()

