"""Build atomic carrier-frame tangent/quaternion track publication."""
from __future__ import annotations
import argparse,importlib.util,re,sys
from pathlib import Path
FUNCTION="CommitCompiledCarrierFrameTransportV1"
def load(root):
 p=root/"tools/blueprint/Build-TrajectoryScalarEvaluatorGraphs.py";s=importlib.util.spec_from_file_location("edd_carrier_commit_base",p);m=importlib.util.module_from_spec(s);sys.modules[s.name]=m;s.loader.exec_module(m);return m
def kind(n,p,k,array=False):
 c,sc,o={"bool":("bool","","None"),"int":("int","","None"),"real":("real","double","None"),"string":("string","","None"),"vector":("struct","",'"/Script/CoreUObject.ScriptStruct\'/Script/CoreUObject.Vector\'"'),"quat":("struct","",'"/Script/CoreUObject.ScriptStruct\'/Script/CoreUObject.Quat\'"')}[k]
 def f(l):l=re.sub(r'PinType.PinCategory="[^"]*"',f'PinType.PinCategory="{c}"',l,1);l=re.sub(r'PinType.PinSubCategory="[^"]*"',f'PinType.PinSubCategory="{sc}"',l,1);l=re.sub(r'PinType.PinSubCategoryObject=(?:None|"[^"]*")',f"PinType.PinSubCategoryObject={o}",l,1);return re.sub(r'PinType.ContainerType=(?:None|Array)',f'PinType.ContainerType={"Array" if array else "None"}',l,1)
 n.mutate_pin(p,f)
def main():
 p=argparse.ArgumentParser();p.add_argument("--project-root",type=Path,required=True);p.add_argument("--output",type=Path,required=True);p.add_argument("--paste-output",type=Path);a=p.parse_args();s=load(a.project_root);bp=s.load_helpers(a.project_root);forms=s.load_templates(a.project_root,bp)
 raw=bp.read_blocks(a.project_root/"tools/blueprint/templates/waypoint-struct-sync-node-forms.eddgraph");edit=bp.read_blocks(a.project_root/"tools/blueprint/templates/waypoint-edit-node-forms.eddgraph");play=bp.read_blocks(a.project_root/"tools/blueprint/snippets/update-linear-playback.eddgraph");air=bp.read_blocks(a.project_root/"tools/blueprint/templates/airframe-gimbal-native-node-forms.eddgraph");qc=bp.read_blocks(a.project_root/"tools/blueprint/templates/orientation-compiler-native-node-forms.eddgraph");qn=bp.read_blocks(a.project_root/"tools/blueprint/templates/trajectory-quaternion-native-node-forms.eddgraph");bq=bp.read_blocks(a.project_root/"tools/blueprint/templates/repository-codec-break-quat-node-form.eddgraph");translation=bp.read_blocks(a.project_root/"tools/blueprint/snippets/apply-translation-input.eddgraph")
 forms.update(foreach=bp.find_block(raw,r"K2Node_MacroInstance"),length=bp.find_block(edit,r'MemberName="Array_Length"'),item=bp.find_block(play,r"^Begin Object Class=/Script/BlueprintGraph.K2Node_GetArrayItem"),quat_finite=bp.find_block(qn,r'MemberName="Quat_IsFinite"'),quat_size=bp.find_block(qc,r'MemberName="Quat_Size"'),axis_x=bp.find_block(air,r'MemberName="Quat_GetAxisX"'),break_quat=bp.find_block(bq,r'MemberName="BreakQuat"'),vsize=bp.find_block(qc,r'MemberName="VSize"'),vector_math=bp.find_block(translation,r'MemberName="Multiply_VectorVector"'))
 b=s.Builder(bp,forms,FUNCTION)
 def var(n,name,k,array=False):s.retarget_variable(n,name,"vector" if k=="quat" else ("real" if k=="int" else k));kind(n,name,k,array);kind(n,"Output_Get",k,array) if "Output_Get" in n.pins else None
 def get(name,k,X,Y,array=False):n=b.add(f"get_{name}_{len(b.nodes)}","get",X,Y);var(n,name,k,array);return n
 def set_(name,k,X,Y,src=None,pin=None,default=None,array=False):n=b.add(f"set_{name}_{len(b.nodes)}","set",X,Y);var(n,name,k,array);bp.connect(src,pin,n,name) if src else s.set_default(n,name,default);return n
 def ret(n,name,kinds):s.retarget_function(n,name);[kind(n,p,k) for p,k in kinds.items()];return n
 def compare(name,l,lp,X,Y,r=None,rp=None,default=None,k="real"):
  n=b.add(f"cmp_{name}_{len(b.nodes)}","compare",X,Y);ret(n,name,{"A":k,"B":k,"ReturnValue":"bool"});bp.connect(l,lp,n,"A");bp.connect(r,rp,n,"B") if r else s.set_default(n,"B",default);return n
 def and_all(items,X,Y):
  cur,pin=items[0]
  for i,(other,op) in enumerate(items[1:]):cur=compare("BooleanAND",cur,pin,X+i*208,Y,other,op,k="bool");pin="ReturnValue"
  return cur,pin
 def addform(form,X,Y):
  block=forms[form];m=bp.BLOCK_RE.match(block);cls=m.group("class").rsplit(".",1)[-1];i=b.serial.get(cls,0);b.serial[cls]=i+1;n=bp.Node.clone(f"{form}_{len(b.nodes)}",block,f"{cls}_{i}",X,Y);b.nodes.append(n);return n
 def length(src,sp,k,X,Y):n=addform("length",X,Y);kind(n,"TargetArray",k,True);kind(n,"ReturnValue","int");bp.connect(src,sp,n,"TargetArray");return n
 def item(src,sp,index,ip,k,X,Y):n=addform("item",X,Y);kind(n,"Array",k,True);kind(n,"Output",k);bp.connect(src,sp,n,"Array");bp.connect(index,ip,n,"Dimension 1");return n
 tangents=get("CarrierFrameCandidateTangentsV1","vector",0,0,True);quats=get("CarrierFrameCandidateQuatsV1","quat",0,192,True);positions=get("CarrierFrameInputPositionsV1","vector",0,384,True);stage=get("CarrierFrameScratchValidV1","bool",0,576);total=get("CarrierFrameInputTotalSecondsV1","real",0,768);step=get("CarrierFrameInputFixedStepSecondsV1","real",0,960);tc=length(tangents,"CarrierFrameCandidateTangentsV1","vector",320,0);qc_count=length(quats,"CarrierFrameCandidateQuatsV1","quat",320,192);pc=length(positions,"CarrierFrameInputPositionsV1","vector",320,384)
 shape=[(stage,"CarrierFrameScratchValidV1"),(compare("GreaterEqual_IntInt",tc,"ReturnValue",640,0,default="2",k="int"),"ReturnValue"),(compare("LessEqual_IntInt",tc,"ReturnValue",640,128,default="65536",k="int"),"ReturnValue"),(compare("EqualEqual_IntInt",tc,"ReturnValue",640,256,qc_count,"ReturnValue",k="int"),"ReturnValue"),(compare("EqualEqual_IntInt",tc,"ReturnValue",640,384,pc,"ReturnValue",k="int"),"ReturnValue")];shape_ok,shape_pin=and_all(shape,1024,512);invalidate=set_("CarrierFrameCompileValidV1","bool",256,3200,default="false");guard=b.add("shape_guard","branch",2048,3200);bp.connect(b.entry,"then",invalidate,"execute");bp.connect(invalidate,"then",guard,"execute");bp.connect(shape_ok,shape_pin,guard,"Condition");shape_valid=set_("CarrierFrameScratchValidV1","bool",2304,3120,default="true");shape_fail_valid=set_("CarrierFrameScratchValidV1","bool",2304,3280,default="false");shape_fail=set_("CarrierFrameFailureCodeV1","string",2560,3280,default="candidate_invalid");bp.connect(guard,"then",shape_valid,"execute");bp.connect(guard,"else",shape_fail_valid,"execute");bp.connect(shape_fail_valid,"then",shape_fail,"execute")
 loop=addform("foreach",2816,3200);kind(loop,"Array","vector",True);kind(loop,"Array Element","vector");kind(loop,"Array Index","int");bp.connect(tangents,"CarrierFrameCandidateTangentsV1",loop,"Array");bp.connect(shape_valid,"then",loop,"Exec");q=item(quats,"CarrierFrameCandidateQuatsV1",loop,"Array Index","quat",2816,640);ts=addform("vsize",3040,480);kind(ts,"A","vector");kind(ts,"ReturnValue","real");bp.connect(loop,"Array Element",ts,"A");tl=compare("GreaterEqual_DoubleDouble",ts,"ReturnValue",3264,400,default="0.999999");tu=compare("LessEqual_DoubleDouble",ts,"ReturnValue",3264,560,default="1.000001");qfinite=addform("quat_finite",3040,720);kind(qfinite,"Q","quat");kind(qfinite,"ReturnValue","bool");bp.connect(q,"Output",qfinite,"Q");qs=addform("quat_size",3040,880);kind(qs,"Q","quat");kind(qs,"ReturnValue","real");bp.connect(q,"Output",qs,"Q");ql=compare("GreaterEqual_DoubleDouble",qs,"ReturnValue",3264,800,default="0.999999");qu=compare("LessEqual_DoubleDouble",qs,"ReturnValue",3264,960,default="1.000001");axis=addform("axis_x",3040,1120);kind(axis,"Q","quat");kind(axis,"ReturnValue","vector");bp.connect(q,"Output",axis,"Q");delta=addform("vector_math",3264,1120);ret(delta,"Subtract_VectorVector",{"A":"vector","B":"vector","ReturnValue":"vector"});bp.connect(axis,"ReturnValue",delta,"A");bp.connect(loop,"Array Element",delta,"B");ds=addform("vsize",3488,1120);kind(ds,"A","vector");kind(ds,"ReturnValue","real");bp.connect(delta,"ReturnValue",ds,"A");aligned=compare("LessEqual_DoubleDouble",ds,"ReturnValue",3712,1120,default="0.000001");common,common_pin=and_all(((tl,"ReturnValue"),(tu,"ReturnValue"),(qfinite,"ReturnValue"),(ql,"ReturnValue"),(qu,"ReturnValue"),(aligned,"ReturnValue")),3936,1280);common_guard=b.add("common_guard","branch",5184,3200);bp.connect(loop,"LoopBody",common_guard,"execute");bp.connect(common,common_pin,common_guard,"Condition");reject=set_("CarrierFrameScratchValidV1","bool",5440,3360,default="false");reject_code=set_("CarrierFrameFailureCodeV1","string",5696,3360,default="candidate_invalid");bp.connect(common_guard,"else",reject,"execute");bp.connect(reject,"then",reject_code,"execute");first=compare("EqualEqual_IntInt",loop,"Array Index",5184,1440,default="0",k="int");first_guard=b.add("first_guard","branch",5440,3120);bp.connect(common_guard,"then",first_guard,"execute");bp.connect(first,"ReturnValue",first_guard,"Condition")
 prev_index=b.add("previous_index","math",5440,1600);ret(prev_index,"Subtract_IntInt",{"A":"int","B":"int","ReturnValue":"int"});bp.connect(loop,"Array Index",prev_index,"A");s.set_default(prev_index,"B","1");previous=item(quats,"CarrierFrameCandidateQuatsV1",prev_index,"ReturnValue","quat",5664,1600);breaks=[]
 for name,source,Y in (("previous",previous,1440),("current",q,1760)):
  n=addform("break_quat",5888,Y);kind(n,"InQuat","quat");[kind(n,p,"real") for p in "XYZW"];bp.connect(source,"Output",n,"InQuat");breaks.append(n)
 products=[]
 for i,pin in enumerate("XYZW"):
  n=b.add(f"product_{pin}","math",6112,1440+i*128);ret(n,"Multiply_DoubleDouble",{"A":"real","B":"real","ReturnValue":"real"});bp.connect(breaks[0],pin,n,"A");bp.connect(breaks[1],pin,n,"B");products.append(n)
 sums=[]
 for i,(l,r) in enumerate(((products[0],products[1]),(products[2],products[3]))):n=b.add(f"sum_{i}","math",6336,1504+i*256);ret(n,"Add_DoubleDouble",{"A":"real","B":"real","ReturnValue":"real"});bp.connect(l,"ReturnValue",n,"A");bp.connect(r,"ReturnValue",n,"B");sums.append(n)
 qdot=b.add("quat_dot","math",6560,1632);ret(qdot,"Add_DoubleDouble",{"A":"real","B":"real","ReturnValue":"real"});bp.connect(sums[0],"ReturnValue",qdot,"A");bp.connect(sums[1],"ReturnValue",qdot,"B");hemisphere=compare("GreaterEqual_DoubleDouble",qdot,"ReturnValue",6784,1632,default="-0.000001");hemisphere_guard=b.add("hemisphere_guard","branch",5696,3120);bp.connect(first_guard,"else",hemisphere_guard,"execute");bp.connect(hemisphere,"ReturnValue",hemisphere_guard,"Condition");bp.connect(hemisphere_guard,"else",reject,"execute")
 result=get("CarrierFrameScratchValidV1","bool",7008,1632);result_guard=b.add("result_guard","branch",5952,3200);bp.connect(loop,"Completed",result_guard,"execute");bp.connect(result,"CarrierFrameScratchValidV1",result_guard,"Condition");compiled_t=set_("CarrierFrameCompiledTangentsV1","vector",6208,3120,tangents,"CarrierFrameCandidateTangentsV1",array=True);compiled_q=set_("CarrierFrameCompiledQuatsV1","quat",6464,3120,quats,"CarrierFrameCandidateQuatsV1",array=True);compiled_total=set_("CarrierFrameCompiledTotalSecondsV1","real",6720,3120,total,"CarrierFrameInputTotalSecondsV1");compiled_step=set_("CarrierFrameCompiledFixedStepSecondsV1","real",6976,3120,step,"CarrierFrameInputFixedStepSecondsV1");clear_failure=set_("CarrierFrameFailureCodeV1","string",7232,3120,default="");publish=set_("CarrierFrameCompileValidV1","bool",7488,3120,default="true");chain=(compiled_t,compiled_q,compiled_total,compiled_step,clear_failure,publish);bp.connect(result_guard,"then",chain[0],"execute");[bp.connect(l,"then",r,"execute") for l,r in zip(chain,chain[1:])]
 full="\n".join(n.text for n in b.nodes)+"\n";a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(full,encoding="utf-8")
 if a.paste_output:a.paste_output.parent.mkdir(parents=True,exist_ok=True);a.paste_output.write_text("\n".join(re.sub(r',LinkedTo=\(K2Node_FunctionEntry_0 [0-9A-F]{32},\)',"",n.text) for n in b.nodes[1:])+"\n",encoding="utf-8")
if __name__=="__main__":main()
