"""Evaluate one staged scalar channel and append its camera-frame sample."""
from __future__ import annotations
import argparse,importlib.util,re,sys
from pathlib import Path
FUNCTION="PublishCameraChannelSampleV1";TARGET='"/Script/Engine.BlueprintGeneratedClass\'/Game/Mods/ExileDroneDirector/Core/Client/BPC_EDD_ClientDirector.BPC_EDD_ClientDirector_C\'"'
def load(root):p=root/"tools/blueprint/Build-TrajectoryScalarEvaluatorGraphs.py";s=importlib.util.spec_from_file_location("edd_camera_channel_publish_base",p);m=importlib.util.module_from_spec(s);sys.modules[s.name]=m;s.loader.exec_module(m);return m
def kind(n,p,k,array=False):
 cat,sub={"bool":("bool",""),"int":("int",""),"real":("real","double")}[k]
 def f(line):line=re.sub(r'PinType.PinCategory="[^"]*"',f'PinType.PinCategory="{cat}"',line,1);line=re.sub(r'PinType.PinSubCategory="[^"]*"',f'PinType.PinSubCategory="{sub}"',line,1);return re.sub(r'PinType.ContainerType=(?:None|Array)',f'PinType.ContainerType={"Array" if array else "None"}',line,1)
 n.mutate_pin(p,f)
def main():
 p=argparse.ArgumentParser();p.add_argument("--project-root",type=Path,required=True);p.add_argument("--output",type=Path,required=True);p.add_argument("--paste-output",type=Path);a=p.parse_args();s=load(a.project_root);bp=s.load_helpers(a.project_root);forms=s.load_templates(a.project_root,bp);b=s.Builder(bp,forms,FUNCTION);capture=bp.read_blocks(a.project_root/"tools/blueprint/templates/waypoint-capture-node-forms.eddgraph");calls=bp.read_blocks(a.project_root/"tools/blueprint/snippets/activate-drone-view.eddgraph");public=bp.read_blocks(a.project_root/"tools/blueprint/live-snippets/list-public-v1.eddgraph");add_form=bp.find_block(capture,r'MemberName="Array_Add"');call_form=bp.find_block(calls,r'MemberName="SwitchToDroneView"');select_form=bp.find_block(public,r"^Begin Object Class=/Script/BlueprintGraph.K2Node_Select ")
 def addform(key,raw,x,y):m=bp.BLOCK_RE.match(raw);cls=m.group("class").rsplit(".",1)[-1];i=b.serial.get(cls,0);b.serial[cls]=i+1;n=bp.Node.clone(key,raw,f"{cls}_{i}",x,y);b.nodes.append(n);return n
 def var(n,name,k,array=False):s.retarget_variable(n,name,"real" if k=="int" else k);kind(n,name,k,array);kind(n,"Output_Get",k,array) if "Output_Get" in n.pins else None
 def get(name,k,x,y,array=False):n=b.add(f"get_{name}_{len(b.nodes)}","get",x,y);var(n,name,k,array);return n
 def setv(name,k,x,y,default=None):n=b.add(f"set_{name}_{len(b.nodes)}","set",x,y);var(n,name,k);s.set_default(n,name,default) if default is not None else None;return n
 def cmp(member,left,leftpin,x,y,right=None,rightpin=None,default=None):n=b.add(f"cmp_{member}_{len(b.nodes)}","compare",x,y);s.retarget_function(n,member);[kind(n,pin,"bool") for pin in ("A","B","ReturnValue")];bp.connect(left,leftpin,n,"A");bp.connect(right,rightpin,n,"B") if right is not None else s.set_default(n,"B",default);return n
 def intcmp(member,left,leftpin,x,y,default):n=b.add(f"cmp_{member}_{len(b.nodes)}","compare",x,y);s.retarget_function(n,member);kind(n,"A","int");kind(n,"B","int");kind(n,"ReturnValue","bool");bp.connect(left,leftpin,n,"A");s.set_default(n,"B",default);return n
 def add(src,srcpin,value,valuepin,x,y):n=addform(f"add_{srcpin}_{len(b.nodes)}",add_form,x,y);kind(n,"TargetArray","real",True);kind(n,"NewItem","real");kind(n,"ReturnValue","int");bp.connect(src,srcpin,n,"TargetArray");bp.connect(value,valuepin,n,"NewItem");return n
 def call(name,x,y):n=addform(f"call_{name}",call_form,x,y);n.text=re.sub(r"FunctionReference=\([^\n]*\)",f'FunctionReference=(MemberName="{name}",bSelfContext=True)',n.text,1);n.mutate_pin("self",lambda line:re.sub(r'PinType.PinSubCategoryObject="/Script/Engine.BlueprintGeneratedClass\'[^\']+\'"',f"PinType.PinSubCategoryObject={TARGET}",line,1));return n
 stage=get("CameraChannelScratchValidV1","bool",0,0);guard=b.add("stage_guard","branch",256,1280);bp.connect(b.entry,"then",guard,"execute");bp.connect(stage,"CameraChannelScratchValidV1",guard,"Condition");query=get("CameraChannelQueryTimeV1","real",0,160);set_query=setv("CameraScalarTrackQueryTimeV1","real",512,1280);bp.connect(query,"CameraChannelQueryTimeV1",set_query,"CameraScalarTrackQueryTimeV1");bp.connect(guard,"then",set_query,"execute");evaluate=call("EvaluateCameraScalarTrackV1",768,1280);bp.connect(set_query,"then",evaluate,"execute");scalar_valid=get("CameraScalarTrackResultValidV1","bool",768,320);result_guard=b.add("result_guard","branch",1024,1280);bp.connect(evaluate,"then",result_guard,"execute");bp.connect(scalar_valid,"CameraScalarTrackResultValidV1",result_guard,"Condition");reject=setv("CameraChannelScratchValidV1","bool",1280,1504,"false");bp.connect(result_guard,"else",reject,"execute")
 targets=[get(name,"real",0,560+i*160,True) for i,name in enumerate(("CameraChannelResultValuesV1","CameraChannelResultVelocitiesV1","CameraChannelResultAccelerationsV1"))];samples=[get(name,"real",768,560+i*160) for i,name in enumerate(("CameraScalarTrackResultValueV1","CameraScalarTrackResultVelocityV1","CameraScalarTrackResultAccelerationV1"))];adds=[add(target,name,sample,scalar_name,1280+i*256,1280) for i,(target,name,sample,scalar_name) in enumerate(zip(targets,("CameraChannelResultValuesV1","CameraChannelResultVelocitiesV1","CameraChannelResultAccelerationsV1"),samples,("CameraScalarTrackResultValueV1","CameraScalarTrackResultVelocityV1","CameraScalarTrackResultAccelerationV1")))];bp.connect(result_guard,"then",adds[0],"execute");[bp.connect(left,"then",right,"execute") for left,right in zip(adds,adds[1:])]
 index=get("CameraChannelScratchChannelIndexV1","int",0,1120);first=intcmp("EqualEqual_IntInt",index,"CameraChannelScratchChannelIndexV1",256,1120,"0");prior=get("CameraChannelResultCompleteV1","bool",512,960);scalar_complete=get("CameraScalarTrackResultCompleteV1","bool",768,960);folded=cmp("BooleanAND",prior,"CameraChannelResultCompleteV1",1024,960,scalar_complete,"CameraScalarTrackResultCompleteV1");select=addform("complete_select",select_form,1792,960);kind(select,"Index","bool");[kind(select,pin,"bool") for pin in ("Option 0","Option 1","ReturnValue")];bp.connect(first,"ReturnValue",select,"Index");bp.connect(folded,"ReturnValue",select,"Option 0");bp.connect(scalar_complete,"CameraScalarTrackResultCompleteV1",select,"Option 1");store=setv("CameraChannelResultCompleteV1","bool",2048,1280);bp.connect(select,"ReturnValue",store,"CameraChannelResultCompleteV1");bp.connect(adds[-1],"then",store,"execute")
 full="\n".join(n.text for n in b.nodes)+"\n";a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(full,encoding="utf-8")
 if a.paste_output:a.paste_output.parent.mkdir(parents=True,exist_ok=True);a.paste_output.write_text("\n".join(re.sub(r',LinkedTo=\(K2Node_FunctionEntry_0 [0-9A-F]{32},\)',"",n.text) for n in b.nodes[1:])+"\n",encoding="utf-8")
if __name__=="__main__":main()

