"""Build result-only reset for camera channel assembly evaluation."""
from __future__ import annotations
import argparse,importlib.util,re,sys
from pathlib import Path
FUNCTION="ResetCameraChannelResultV1";ARRAYS=(("CameraChannelResultValuesV1","real"),("CameraChannelResultVelocitiesV1","real"),("CameraChannelResultAccelerationsV1","real"));SCALARS=(("CameraChannelResultFilmbackPresetIdV1","string",""),("CameraChannelResultFilmbackSensorWidthMmV1","real","0.0"),("CameraChannelResultFilmbackSensorHeightMmV1","real","0.0"),("CameraChannelResultCompleteV1","bool","false"),("CameraChannelResultValidV1","bool","false"),("CameraChannelScratchChannelIndexV1","int","0"),("CameraChannelScratchKeyIndexV1","int","0"),("CameraChannelScratchValidV1","bool","false"))
def load(root):p=root/"tools/blueprint/Build-CameraChannelCompileResetGraph.py";s=importlib.util.spec_from_file_location("edd_camera_channel_result_reset_base",p);m=importlib.util.module_from_spec(s);sys.modules[s.name]=m;s.loader.exec_module(m);return m
def main():
 a=argparse.ArgumentParser();a.add_argument("--project-root",type=Path,required=True);a.add_argument("--output",type=Path,required=True);a.add_argument("--paste-output",type=Path);x=a.parse_args();helpers=load(x.project_root);reset=helpers.load(x.project_root);bp=reset.load(x.project_root);bp.TARGET_GRAPH=FUNCTION;capture=bp.read_blocks(x.project_root/"tools/blueprint/templates/waypoint-capture-node-forms.eddgraph");sync=bp.read_blocks(x.project_root/"tools/blueprint/snippets/sync-draft-waypoints-v1.eddgraph");start=bp.read_blocks(x.project_root/"tools/blueprint/snippets/start-linear-playback.eddgraph");entry=bp.Node.clone("entry",bp.find_block(capture,r"K2Node_FunctionEntry"),"K2Node_FunctionEntry_0",0,0);entry.text=re.sub(r'FunctionReference=\(MemberName="[^"]+"\)',f'FunctionReference=(MemberName="{FUNCTION}")',entry.text,1);array_form=bp.find_block(sync,r'MemberName="DraftWaypointIds"');clear_form=bp.find_block(sync,r'MemberName="Array_Clear"');setter_form=bp.find_block(start,r'K2Node_VariableSet.*MemberName="PlaybackActive"');nodes=[entry];chain=[]
 for i,(name,kind) in enumerate(ARRAYS):g=bp.Node.clone(f"get_{i}",array_form,f"K2Node_VariableGet_{i}",256+i*416,256);reset.variable(g,"DraftWaypointIds",name,kind,True);c=bp.Node.clone(f"clear_{i}",clear_form,f"K2Node_CallArrayFunction_{i}",256+i*416,0);reset.pin_kind(c,"TargetArray",kind,True);bp.connect(g,name,c,"TargetArray");nodes.extend((g,c));chain.append(c)
 for i,(name,kind,value) in enumerate(SCALARS):n=bp.Node.clone(f"set_{i}",setter_form,f"K2Node_VariableSet_{i}",256+(len(ARRAYS)+i)*416,0);helpers.string_variable(n,"PlaybackActive",name) if kind=="string" else reset.variable(n,"PlaybackActive",name,kind);reset.default(n,name,value);nodes.append(n);chain.append(n)
 bp.connect(entry,"then",chain[0],"execute");[bp.connect(left,"then",right,"execute") for left,right in zip(chain,chain[1:])];full="\n".join(n.text for n in nodes)+"\n";x.output.parent.mkdir(parents=True,exist_ok=True);x.output.write_text(full,encoding="utf-8")
 if x.paste_output:x.paste_output.parent.mkdir(parents=True,exist_ok=True);x.paste_output.write_text("\n".join(re.sub(r',LinkedTo=\(K2Node_FunctionEntry_0 [0-9A-F]{32},\)',"",n.text) for n in nodes[1:])+"\n",encoding="utf-8")
if __name__=="__main__":main()
