"""Build independent twist-minimizing carrier-frame quaternion samples."""
from __future__ import annotations
import argparse, importlib.util, re, sys
from pathlib import Path

FUNCTION="BuildCarrierFrameTransportSamplesV1"
def load(root):
 p=root/"tools/blueprint/Build-TrajectoryScalarEvaluatorGraphs.py";s=importlib.util.spec_from_file_location("edd_carrier_transport_base",p);m=importlib.util.module_from_spec(s);sys.modules[s.name]=m;s.loader.exec_module(m);return m
def kind(n,p,k,array=False):
 c,sc,o={"bool":("bool","","None"),"int":("int","","None"),"real":("real","double","None"),"string":("string","","None"),"vector":("struct","",'"/Script/CoreUObject.ScriptStruct\'/Script/CoreUObject.Vector\'"'),"quat":("struct","",'"/Script/CoreUObject.ScriptStruct\'/Script/CoreUObject.Quat\'"'),"rotator":("struct","",'"/Script/CoreUObject.ScriptStruct\'/Script/CoreUObject.Rotator\'"')}[k]
 def f(line):
  line=re.sub(r'PinType.PinCategory="[^"]*"',f'PinType.PinCategory="{c}"',line,1);line=re.sub(r'PinType.PinSubCategory="[^"]*"',f'PinType.PinSubCategory="{sc}"',line,1);line=re.sub(r'PinType.PinSubCategoryObject=(?:None|"[^"]*")',f"PinType.PinSubCategoryObject={o}",line,1);return re.sub(r'PinType.ContainerType=(?:None|Array)',f'PinType.ContainerType={"Array" if array else "None"}',line,1)
 n.mutate_pin(p,f)
def main():
 a=argparse.ArgumentParser();a.add_argument("--project-root",type=Path,required=True);a.add_argument("--output",type=Path,required=True);a.add_argument("--paste-output",type=Path);x=a.parse_args();s=load(x.project_root);bp=s.load_helpers(x.project_root);forms=s.load_templates(x.project_root,bp)
 capture=bp.read_blocks(x.project_root/"tools/blueprint/templates/waypoint-capture-node-forms.eddgraph");edit=bp.read_blocks(x.project_root/"tools/blueprint/templates/waypoint-edit-node-forms.eddgraph");playback=bp.read_blocks(x.project_root/"tools/blueprint/snippets/update-linear-playback.eddgraph");reset=bp.read_blocks(x.project_root/"tools/blueprint/snippets/reset-carrier-frame-transport-v1.eddgraph");loops=bp.read_blocks(x.project_root/"tools/blueprint/templates/adaptive-arc-for-loop-with-break-node-form.eddgraph");marker=bp.read_blocks(x.project_root/"tools/blueprint/templates/path-preview-marker-node-forms.eddgraph");translation=bp.read_blocks(x.project_root/"tools/blueprint/snippets/apply-translation-input.eddgraph");air=bp.read_blocks(x.project_root/"tools/blueprint/templates/airframe-gimbal-native-node-forms.eddgraph");horizon=bp.read_blocks(x.project_root/"tools/blueprint/templates/horizon-node-forms.eddgraph");qn=bp.read_blocks(x.project_root/"tools/blueprint/templates/trajectory-quaternion-native-node-forms.eddgraph");qc=bp.read_blocks(x.project_root/"tools/blueprint/templates/orientation-compiler-native-node-forms.eddgraph");bq=bp.read_blocks(x.project_root/"tools/blueprint/templates/repository-codec-break-quat-node-form.eddgraph");vc=bp.read_blocks(x.project_root/"tools/blueprint/templates/repository-codec-vector-node-forms.eddgraph")
 forms.update(array_add=bp.find_block(capture,r'MemberName="Array_Add"'),array_clear=bp.find_block(reset,r'MemberName="Array_Clear"'),array_length=bp.find_block(edit,r'MemberName="Array_Length"'),array_item=bp.find_block(playback,r"^Begin Object Class=/Script/BlueprintGraph.K2Node_GetArrayItem"),loop=bp.find_block(loops,r"StandardMacros:ForLoopWithBreak"),make_vector=bp.find_block(marker,r'MemberName="MakeVector"'),vector_math=bp.find_block(translation,r'MemberName="Multiply_VectorVector"'),vector_size=bp.find_block(qc,r'MemberName="VSize"'),cross=bp.find_block(air,r'MemberName="Cross_VectorVector"'),dot=bp.find_block(air,r'MemberName="Dot_VectorVector"'),rotate=bp.find_block(air,r'MemberName="Quat_RotateVector"'),make_rot=bp.find_block(horizon,r'MemberName="MakeRotFromXZ"'),to_quat=bp.find_block(air,r'MemberName="Conv_RotatorToQuaternion"'),quat_normal=bp.find_block(qn,r'MemberName="Quat_Normalized"'),quat_set=bp.find_block(qc,r'MemberName="Quat_SetComponents"'),break_quat=bp.find_block(bq,r'MemberName="BreakQuat"'),break_vector=bp.find_block(vc,r'MemberName="BreakVector"'))
 b=s.Builder(bp,forms,FUNCTION)
 def var(n,name,k,array=False):s.retarget_variable(n,name,"vector" if k=="quat" else ("real" if k=="int" else k));kind(n,name,k,array);kind(n,"Output_Get",k,array) if "Output_Get" in n.pins else None
 def get(name,k,X,Y,array=False):n=b.add(f"get_{name}_{len(b.nodes)}","get",X,Y);var(n,name,k,array);return n
 def set_(name,k,X,Y,src=None,pin=None,default=None):n=b.add(f"set_{name}_{len(b.nodes)}","set",X,Y);var(n,name,k);bp.connect(src,pin,n,name) if src else s.set_default(n,name,default);return n
 def ret(n,name,kinds):s.retarget_function(n,name);[kind(n,p,k) for p,k in kinds.items()];return n
 def compare(name,l,lp,X,Y,r=None,rp=None,default=None,k="real"):
  n=b.add(f"cmp_{name}_{len(b.nodes)}","compare",X,Y);ret(n,name,{"A":k,"B":k,"ReturnValue":"bool"});bp.connect(l,lp,n,"A");bp.connect(r,rp,n,"B") if r else s.set_default(n,"B",default);return n
 def math(name,l,lp,X,Y,r=None,rp=None,default=None,k="real"):
  n=b.add(f"math_{name}_{len(b.nodes)}","math",X,Y);ret(n,name,{"A":k,"B":k,"ReturnValue":k});bp.connect(l,lp,n,"A");bp.connect(r,rp,n,"B") if r else s.set_default(n,"B",default);return n
 def call(form,name,kinds,links,X,Y):
  n=b.add(f"{form}_{len(b.nodes)}",form,X,Y);ret(n,name,kinds)
  for p,src,sp in links:bp.connect(src,sp,n,p)
  return n
 def arr(form,src,sp,k,X,Y):
  n=b.add(f"{form}_{len(b.nodes)}",form,X,Y);tp="Array" if form=="array_item" else "TargetArray";kind(n,tp,k,True);bp.connect(src,sp,n,tp)
  if form=="array_item":kind(n,"Output",k)
  elif form=="array_add":kind(n,"NewItem",k);kind(n,"ReturnValue","int")
  elif form=="array_length":kind(n,"ReturnValue","int")
  return n
 def item(src,sp,idx,ip,k,X,Y):n=arr("array_item",src,sp,k,X,Y);bp.connect(idx,ip,n,"Dimension 1");return n
 def vmath(name,l,lp,r,rp,X,Y):return call("vector_math",name,{"A":"vector","B":"vector","ReturnValue":"vector"},[("A",l,lp),("B",r,rp)],X,Y)
 def dot(l,lp,r,rp,X,Y):return call("dot","Dot_VectorVector",{"A":"vector","B":"vector","ReturnValue":"real"},[("A",l,lp)]+([] if r is None else [("B",r,rp)]),X,Y)
 def cross(l,lp,r,rp,X,Y):return call("cross","Cross_VectorVector",{"A":"vector","B":"vector","ReturnValue":"vector"},[("A",l,lp),("B",r,rp)],X,Y)
 def vsize(v,p,X,Y):return call("vector_size","VSize",{"A":"vector","ReturnValue":"real"},[("A",v,p)],X,Y)
 def scalar_vector(v,p,X,Y):
  n=b.add(f"scalar_vector_{len(b.nodes)}","make_vector",X,Y);[kind(n,a,"real") for a in "XYZ"];kind(n,"ReturnValue","vector");[bp.connect(v,p,n,a) for a in "XYZ"];return n
 def normalize(v,p,X,Y):m=vsize(v,p,X,Y);d=scalar_vector(m,"ReturnValue",X+224,Y);return vmath("Divide_VectorVector",v,p,d,"ReturnValue",X+448,Y)
 def breakv(v,p,X,Y):n=b.add(f"breakv_{len(b.nodes)}","break_vector",X,Y);kind(n,"InVec","vector");[kind(n,a,"real") for a in "XYZ"];bp.connect(v,p,n,"InVec");return n
 def setq(exec_source,exec_pin,v,p,w,wp,X,Y):
  br=breakv(v,p,X,Y);storage=get("CarrierFrameScratchQuatV1","quat",X,Y+192);n=b.add(f"setq_{len(b.nodes)}","quat_set",X+224,Y);kind(n,"Q","quat");[kind(n,a,"real") for a in "XYZW"];bp.connect(storage,"CarrierFrameScratchQuatV1",n,"Q");[bp.connect(br,a,n,a) for a in "XYZ"];bp.connect(w,wp,n,"W") if w else s.set_default(n,"W",wp);bp.connect(exec_source,exec_pin,n,"execute");return n
 def normq(q,p,X,Y):n=b.add(f"normq_{len(b.nodes)}","quat_normal",X,Y);kind(n,"Q","quat");kind(n,"ReturnValue","quat");bp.connect(q,p,n,"Q");s.set_default(n,"Tolerance","1e-9");return n
 def basis(f,fp,u,up,X,Y):
  r=b.add(f"basis_rot_{len(b.nodes)}","make_rot",X,Y);kind(r,"X","vector");kind(r,"Z","vector");kind(r,"ReturnValue","rotator");bp.connect(f,fp,r,"X");bp.connect(u,up,r,"Z");q=b.add(f"basis_quat_{len(b.nodes)}","to_quat",X+224,Y);kind(q,"InRot","rotator");kind(q,"ReturnValue","quat");bp.connect(r,"ReturnValue",q,"InRot");return normq(q,"ReturnValue",X+448,Y)
 tangents=get("CarrierFrameCandidateTangentsV1","vector",0,0,True);quats=get("CarrierFrameCandidateQuatsV1","quat",0,192,True);ready=get("CarrierFrameScratchValidV1","bool",0,384);count=arr("array_length",tangents,"CarrierFrameCandidateTangentsV1","vector",320,0);last=math("Subtract_IntInt",count,"ReturnValue",320,128,default="1",k="int");clear=arr("array_clear",quats,"CarrierFrameCandidateQuatsV1","quat",256,3200);guard=b.add("ready_guard","branch",512,3200);bp.connect(b.entry,"then",clear,"execute");bp.connect(clear,"then",guard,"execute");bp.connect(ready,"CarrierFrameScratchValidV1",guard,"Condition");loop=b.add("sample_loop","loop",768,3200);s.set_default(loop,"FirstIndex","0");bp.connect(last,"ReturnValue",loop,"LastIndex");bp.connect(guard,"then",loop,"Execute");store_i=set_("CarrierFrameScratchIndexV1","int",1024,3200,loop,"Index");bp.connect(loop,"LoopBody",store_i,"execute");idx=get("CarrierFrameScratchIndexV1","int",1024,640);tangent=item(tangents,"CarrierFrameCandidateTangentsV1",idx,"CarrierFrameScratchIndexV1","vector",1280,640);is_first=compare("EqualEqual_IntInt",idx,"CarrierFrameScratchIndexV1",1280,800,default="0",k="int");first_guard=b.add("first_guard","branch",1536,3200);bp.connect(store_i,"then",first_guard,"execute");bp.connect(is_first,"ReturnValue",first_guard,"Condition")
 world_dot=dot(tangent,"Output",None,None,1536,640);s.set_default(world_dot,"B","0, 0, 1");pos=compare("GreaterEqual_DoubleDouble",world_dot,"ReturnValue",1760,560,default="0.999999");neg=compare("LessEqual_DoubleDouble",world_dot,"ReturnValue",1760,720,default="-0.999999");vertical=compare("BooleanOR",pos,"ReturnValue",1984,640,neg,"ReturnValue",k="bool");vertical_guard=b.add("vertical_guard","branch",1792,3040);bp.connect(first_guard,"then",vertical_guard,"execute");bp.connect(vertical,"ReturnValue",vertical_guard,"Condition");set_world=set_("CarrierFrameScratchUpV1","vector",2048,2880,default="0, 0, 1");bp.connect(vertical_guard,"else",set_world,"execute")
 dx=dot(tangent,"Output",None,None,1984,960);s.set_default(dx,"B","1, 0, 0");dy=dot(tangent,"Output",None,None,1984,1120);s.set_default(dy,"B","0, 1, 0");dx2=math("Multiply_DoubleDouble",dx,"ReturnValue",2208,960,dx,"ReturnValue");dy2=math("Multiply_DoubleDouble",dy,"ReturnValue",2208,1120,dy,"ReturnValue");xbest=compare("LessEqual_DoubleDouble",dx2,"ReturnValue",2432,1040,dy2,"ReturnValue");axis_guard=b.add("axis_guard","branch",2048,3200);bp.connect(vertical_guard,"then",axis_guard,"execute");bp.connect(xbest,"ReturnValue",axis_guard,"Condition");set_x=set_("CarrierFrameScratchUpV1","vector",2304,3120,default="1, 0, 0");set_y=set_("CarrierFrameScratchUpV1","vector",2304,3280,default="0, 1, 0");bp.connect(axis_guard,"then",set_x,"execute");bp.connect(axis_guard,"else",set_y,"execute")
 hint=get("CarrierFrameScratchUpV1","vector",2560,640);initial_right=normalize(cross(hint,"CarrierFrameScratchUpV1",tangent,"Output",2784,640),"ReturnValue",3008,640);initial_up=normalize(cross(tangent,"Output",initial_right,"ReturnValue",3680,640),"ReturnValue",3904,640);initial_q=basis(tangent,"Output",initial_up,"ReturnValue",4576,640);store_r=set_("CarrierFrameScratchRightV1","vector",2784,2880,initial_right,"ReturnValue");store_u=set_("CarrierFrameScratchUpV1","vector",3040,2880,initial_up,"ReturnValue");store_f=set_("CarrierFrameScratchForwardV1","vector",3296,2880,tangent,"Output");store_q=set_("CarrierFrameScratchQuatV1","quat",3552,2880,initial_q,"ReturnValue");[bp.connect(l,"then",r,"execute") for l,r in zip((set_world,set_x,set_y),(store_r,store_r,store_r))];bp.connect(store_r,"then",store_u,"execute");bp.connect(store_u,"then",store_f,"execute");bp.connect(store_f,"then",store_q,"execute")
 prev_f=get("CarrierFrameScratchForwardV1","vector",5120,640);prev_u=get("CarrierFrameScratchUpV1","vector",5120,800);prev_r=get("CarrierFrameScratchRightV1","vector",5120,960);cosine=dot(prev_f,"CarrierFrameScratchForwardV1",tangent,"Output",5344,640);parallel=compare("GreaterEqual_DoubleDouble",cosine,"ReturnValue",5568,560,default="0.999999999");anti=compare("LessEqual_DoubleDouble",cosine,"ReturnValue",5568,720,default="-0.999999999");parallel_guard=b.add("parallel_guard","branch",5120,3200);bp.connect(first_guard,"else",parallel_guard,"execute");bp.connect(parallel,"ReturnValue",parallel_guard,"Condition");identity=set_("CarrierFrameScratchQuatV1","quat",5376,3040,default="0, 0, 0, 1");bp.connect(parallel_guard,"then",identity,"execute");anti_guard=b.add("anti_guard","branch",5376,3360);bp.connect(parallel_guard,"else",anti_guard,"execute");bp.connect(anti,"ReturnValue",anti_guard,"Condition");set_anti=setq(anti_guard,"then",prev_u,"CarrierFrameScratchUpV1",None,"0.0",5792,960);axis=cross(prev_f,"CarrierFrameScratchForwardV1",tangent,"Output",5792,640);one_plus=math("Add_DoubleDouble",cosine,"ReturnValue",6016,800,default="1.0");set_general_components=setq(anti_guard,"else",axis,"ReturnValue",one_plus,"ReturnValue",6240,640);general_read=get("CarrierFrameScratchQuatV1","quat",6688,640);general_q=normq(general_read,"CarrierFrameScratchQuatV1",6912,640);set_general=set_("CarrierFrameScratchQuatV1","quat",5632,3440,general_q,"ReturnValue");bp.connect(set_general_components,"then",set_general,"execute")
 delta=get("CarrierFrameScratchQuatV1","quat",7136,640);transported=call("rotate","Quat_RotateVector",{"Q":"quat","V":"vector","ReturnValue":"vector"},[("Q",delta,"CarrierFrameScratchQuatV1"),("V",prev_u,"CarrierFrameScratchUpV1")],7360,640);store_trans=set_("CarrierFrameScratchUpV1","vector",5888,3200,transported,"ReturnValue");[bp.connect(n,"then",store_trans,"execute") for n in (identity,set_anti,set_general)];trans=get("CarrierFrameScratchUpV1","vector",7808,640);projection_dot=dot(trans,"CarrierFrameScratchUpV1",tangent,"Output",8032,640);projection_scale=scalar_vector(projection_dot,"ReturnValue",8256,640);along=vmath("Multiply_VectorVector",tangent,"Output",projection_scale,"ReturnValue",8480,640);projected=vmath("Subtract_VectorVector",trans,"CarrierFrameScratchUpV1",along,"ReturnValue",8704,640);projected_size=vsize(projected,"ReturnValue",8928,640);projected_ok=compare("Greater_DoubleDouble",projected_size,"ReturnValue",9152,640,default="1e-9");project_guard=b.add("projection_guard","branch",6144,3200);bp.connect(store_trans,"then",project_guard,"execute");bp.connect(projected_ok,"ReturnValue",project_guard,"Condition");projected_unit=normalize(projected,"ReturnValue",9376,560);fallback_unit=normalize(cross(tangent,"Output",prev_r,"CarrierFrameScratchRightV1",9376,800),"ReturnValue",9600,800);set_projected=set_("CarrierFrameScratchUpV1","vector",6400,3120,projected_unit,"ReturnValue");set_fallback=set_("CarrierFrameScratchUpV1","vector",6400,3280,fallback_unit,"ReturnValue");bp.connect(project_guard,"then",set_projected,"execute");bp.connect(project_guard,"else",set_fallback,"execute")
 transported_up=get("CarrierFrameScratchUpV1","vector",10272,640);right=normalize(cross(transported_up,"CarrierFrameScratchUpV1",tangent,"Output",10496,640),"ReturnValue",10720,640);final_up=normalize(cross(tangent,"Output",right,"ReturnValue",11392,640),"ReturnValue",11616,640);raw_q=basis(tangent,"Output",final_up,"ReturnValue",12288,640);prev_index=math("Subtract_IntInt",idx,"CarrierFrameScratchIndexV1",12736,480,default="1",k="int");previous_q=item(quats,"CarrierFrameCandidateQuatsV1",prev_index,"ReturnValue","quat",12960,480);br_prev=b.add("break_previous","break_quat",13200,400);br_raw=b.add("break_raw","break_quat",13200,720);kind(br_prev,"InQuat","quat");kind(br_raw,"InQuat","quat");[kind(n,p,"real") for n in (br_prev,br_raw) for p in "XYZW"];bp.connect(previous_q,"Output",br_prev,"InQuat");bp.connect(raw_q,"ReturnValue",br_raw,"InQuat");products=[math("Multiply_DoubleDouble",br_prev,p,13424,400+i*128,br_raw,p) for i,p in enumerate("XYZW")];sum0=math("Add_DoubleDouble",products[0],"ReturnValue",13648,464,products[1],"ReturnValue");sum1=math("Add_DoubleDouble",products[2],"ReturnValue",13648,720,products[3],"ReturnValue");qdot=math("Add_DoubleDouble",sum0,"ReturnValue",13872,592,sum1,"ReturnValue");flip=compare("Less_DoubleDouble",qdot,"ReturnValue",14096,592,default="0.0");store_raw=set_("CarrierFrameScratchQuatV1","quat",6400,3200,raw_q,"ReturnValue");flip_guard=b.add("flip_guard","branch",6656,3200);[bp.connect(n,"then",store_raw,"execute") for n in (set_projected,set_fallback)];bp.connect(store_raw,"then",flip_guard,"execute");bp.connect(flip,"ReturnValue",flip_guard,"Condition");neg_components=[math("Multiply_DoubleDouble",br_raw,p,14320,400+i*128,default="-1.0") for i,p in enumerate("XYZW")];scratch_for_flip=get("CarrierFrameScratchQuatV1","quat",14544,912);neg_q=b.add("negated_quat","quat_set",14544,592);kind(neg_q,"Q","quat");[kind(neg_q,p,"real") for p in "XYZW"];bp.connect(scratch_for_flip,"CarrierFrameScratchQuatV1",neg_q,"Q");[bp.connect(n,"ReturnValue",neg_q,p) for n,p in zip(neg_components,"XYZW")];bp.connect(flip_guard,"then",neg_q,"execute");set_final_r=set_("CarrierFrameScratchRightV1","vector",7168,3200,right,"ReturnValue");set_final_u=set_("CarrierFrameScratchUpV1","vector",7424,3200,final_up,"ReturnValue");set_final_f=set_("CarrierFrameScratchForwardV1","vector",7680,3200,tangent,"Output");bp.connect(neg_q,"then",set_final_r,"execute");bp.connect(flip_guard,"else",set_final_r,"execute");bp.connect(set_final_r,"then",set_final_u,"execute");bp.connect(set_final_u,"then",set_final_f,"execute")
 current_q=get("CarrierFrameScratchQuatV1","quat",7936,2720);append=arr("array_add",quats,"CarrierFrameCandidateQuatsV1","quat",8192,3200);bp.connect(current_q,"CarrierFrameScratchQuatV1",append,"NewItem");bp.connect(store_q,"then",append,"execute");bp.connect(set_final_f,"then",append,"execute");qcount=arr("array_length",quats,"CarrierFrameCandidateQuatsV1","quat",14768,640);count_ok=compare("EqualEqual_IntInt",qcount,"ReturnValue",14992,640,count,"ReturnValue",k="int");complete=b.add("complete_guard","branch",8448,3200);bp.connect(loop,"Completed",complete,"execute");bp.connect(count_ok,"ReturnValue",complete,"Condition");clear_failure=set_("CarrierFrameFailureCodeV1","string",8704,3120,default="");publish=set_("CarrierFrameScratchValidV1","bool",8960,3120,default="true");bp.connect(complete,"then",clear_failure,"execute");bp.connect(clear_failure,"then",publish,"execute");fail_valid=set_("CarrierFrameScratchValidV1","bool",8704,3280,default="false");fail_code=set_("CarrierFrameFailureCodeV1","string",8960,3280,default="transport_build_failed");bp.connect(complete,"else",fail_valid,"execute");bp.connect(fail_valid,"then",fail_code,"execute")
 full="\n".join(n.text for n in b.nodes)+"\n";x.output.parent.mkdir(parents=True,exist_ok=True);x.output.write_text(full,encoding="utf-8")
 if x.paste_output:x.paste_output.parent.mkdir(parents=True,exist_ok=True);x.paste_output.write_text("\n".join(re.sub(r',LinkedTo=\(K2Node_FunctionEntry_0 [0-9A-F]{32},\)',"",n.text) for n in b.nodes[1:])+"\n",encoding="utf-8")
if __name__=="__main__":main()
