"""Add Ctrl+Z/Ctrl+Y history dispatch and stable diagnostics to the client tick."""

from __future__ import annotations

import argparse
import importlib.util
import re
import sys
import uuid
from pathlib import Path


UNDO_APPLIED = "[EDD] Undo applied"
UNDO_EMPTY = "[EDD] Undo ignored: history empty"
REDO_APPLIED = "[EDD] Redo applied"
REDO_EMPTY = "[EDD] Redo ignored: history empty"


def load_helpers():
    path = Path(__file__).with_name("Build-WaypointFeedbackDispatch.py")
    spec = importlib.util.spec_from_file_location("edd_history_dispatch_helpers", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load dispatch helpers: {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def remove_link(h, block: str, pin_name: str, other_name: str) -> str:
    pin_id = h.pin_map(block)[pin_name]
    lines = block.splitlines()
    for index, line in enumerate(lines):
        if f"PinId={pin_id}" not in line:
            continue
        linked = re.search(r",LinkedTo=\((?P<links>[^)]*)\)", line)
        if linked is None:
            raise RuntimeError(f"{h.block_name(block)}.{pin_name} has no link to remove")
        links = re.findall(r"([A-Za-z0-9_]+) ([0-9A-F]{32}),", linked.group("links"))
        filtered = [(name, identifier) for name, identifier in links if name != other_name]
        if len(filtered) == len(links):
            raise RuntimeError(f"{h.block_name(block)}.{pin_name} is not linked to {other_name}")
        replacement = ""
        if filtered:
            replacement = ",LinkedTo=(" + "".join(
                f"{name} {identifier}," for name, identifier in filtered
            ) + ")"
        lines[index] = line[: linked.start()] + replacement + line[linked.end() :]
        return "\n".join(lines)
    raise RuntimeError(f"Could not find {h.block_name(block)}.{pin_name}")


def set_explicit_default(h, block: str, pin_name: str, value: str) -> str:
    pin_id = h.pin_map(block)[pin_name]
    lines = block.splitlines()
    for index, line in enumerate(lines):
        if f"PinId={pin_id}" not in line:
            continue
        lines[index] = re.sub(
            r'(?<!Autogenerated)DefaultValue="[^"]*"',
            f'DefaultValue="{value}"',
            line,
            count=1,
        )
        return "\n".join(lines)
    raise RuntimeError(f"Could not set {h.block_name(block)}.{pin_name}")


def retarget_self_call(block: str, function_name: str) -> str:
    return re.sub(
        r"FunctionReference=\([^\r\n]+\)",
        f'FunctionReference=(MemberName="{function_name}",bSelfContext=True)',
        block,
        count=1,
    )


def blocks_from(h, path: Path) -> list[str]:
    return [match.group(0) for match in h.BLOCK_RE.finditer(path.read_text(encoding="utf-8-sig"))]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    h = load_helpers()
    text = args.input.read_text(encoding="utf-8")

    if UNDO_APPLIED in text and REDO_APPLIED in text and 'MemberName="UndoDraftV1"' in text:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_bytes(args.input.read_bytes())
        print("Client graph already contains draft history dispatch; output unchanged.")
        return
    if any(marker in text for marker in (UNDO_APPLIED, REDO_APPLIED, 'MemberName="UndoDraftV1"', 'MemberName="RedoDraftV1"')):
        raise RuntimeError("Input contains a partial or ambiguous draft history dispatch")

    used_ids = set(re.findall(r"(?:NodeGuid=|PinId=)([0-9A-F]{32})", text))
    id_counter = 0

    def dispatch_id() -> str:
        nonlocal id_counter
        while True:
            id_counter += 1
            candidate = uuid.uuid5(
                uuid.NAMESPACE_URL,
                f"exile-drone-director:draft-history-dispatch:{id_counter}",
            ).hex.upper()
            if candidate not in used_ids:
                used_ids.add(candidate)
                return candidate

    h.new_id = dispatch_id
    source_blocks = [match.group(0) for match in h.BLOCK_RE.finditer(text)]
    by_name = {h.block_name(block): block for block in source_blocks}

    # The playback builder reuses CallFunction_15 for all local tick polling.
    controller_candidates = [
        block for block in source_blocks
        if 'MemberName="GetPlayerController"' in block and h.block_name(block) == "K2Node_CallFunction_15"
    ]
    if len(controller_candidates) != 1:
        raise RuntimeError("Expected the playback dispatch local-controller getter")
    controller = controller_candidates[0]
    speed = h.find_one(source_blocks, 'MemberName="UpdateSpeedControls"')
    call_template = h.find_one(source_blocks, 'MemberName="CaptureCurrentWaypoint"')
    print_template = next(block for block in source_blocks if 'MemberName="PrintString"' in block)
    poll_template = h.find_one(source_blocks, 'DefaultValue="K"')
    branch_template = next(
        block for block in source_blocks
        if block.startswith("Begin Object Class=/Script/BlueprintGraph.K2Node_IfThenElse ")
    )
    status_builder = h.find_one(source_blocks, f'DefaultValue="{h.FEEDBACK_SEPARATOR}"')

    playback_active = h.find_one(source_blocks, 'VariableReference=(MemberName="PlaybackActive"')
    playback_branches = [
        block for block in source_blocks
        if block.startswith("Begin Object Class=/Script/BlueprintGraph.K2Node_IfThenElse ")
        and h.block_name(playback_active) in block
    ]
    update_branch = next(
        block for block in playback_branches
        if h.block_name(speed) in block
    )

    speed_forms = blocks_from(h, Path(__file__).resolve().parent / "snippets" / "update-speed-controls.eddgraph")
    ctrl_template = next(
        block for block in speed_forms
        if 'MemberName="IsInputKeyDown"' in block and 'DefaultValue="LeftControl"' in block
    )
    undo_forms = blocks_from(h, Path(__file__).resolve().parent / "snippets" / "undo-draft-v1.eddgraph")
    redo_forms = blocks_from(h, Path(__file__).resolve().parent / "snippets" / "redo-draft-v1.eddgraph")
    undo_documents_template = h.find_one(undo_forms, 'VariableReference=(MemberName="UndoDocumentsV1"')
    redo_documents_template = h.find_one(redo_forms, 'VariableReference=(MemberName="RedoDocumentsV1"')
    length_template = h.find_one(undo_forms, 'MemberName="Array_Length"')
    greater_template = h.find_one(undo_forms, 'MemberName="Greater_IntInt"')

    staged = text
    specs = (
        ("K2Node_CallFunction", "left_ctrl"),
        ("K2Node_CallFunction", "right_ctrl"),
        ("K2Node_CallFunction", "z_poll"),
        ("K2Node_CallFunction", "y_poll"),
        ("K2Node_IfThenElse", "left_branch"),
        ("K2Node_IfThenElse", "right_branch"),
        ("K2Node_IfThenElse", "z_branch"),
        ("K2Node_IfThenElse", "y_branch"),
        ("K2Node_VariableGet", "undo_documents"),
        ("K2Node_VariableGet", "redo_documents"),
        ("K2Node_CallArrayFunction", "undo_length"),
        ("K2Node_CallArrayFunction", "redo_length"),
        ("K2Node_CallFunction", "undo_available"),
        ("K2Node_CallFunction", "redo_available"),
        ("K2Node_IfThenElse", "undo_available_branch"),
        ("K2Node_IfThenElse", "redo_available_branch"),
        ("K2Node_CallFunction", "undo_call"),
        ("K2Node_CallFunction", "redo_call"),
        ("K2Node_CallFunction", "undo_applied"),
        ("K2Node_CallFunction", "undo_empty"),
        ("K2Node_CallFunction", "redo_applied"),
        ("K2Node_CallFunction", "redo_empty"),
        ("K2Node_CallFunction", "undo_status"),
        ("K2Node_CallFunction", "redo_status"),
    )
    names: dict[str, str] = {}
    for prefix, label in specs:
        name = h.next_name(staged, prefix)
        staged += f' Name="{name}"'
        names[label] = name

    def clone(template: str, label: str, x: int, y: int, source_graph: str | None = None) -> str:
        return h.clone_node(template, names[label], x, y, source_graph)

    additions = {
        names["left_ctrl"]: clone(ctrl_template, "left_ctrl", 4016, -32, "UpdateSpeedControls"),
        names["right_ctrl"]: clone(ctrl_template, "right_ctrl", 4016, 144, "UpdateSpeedControls"),
        names["z_poll"]: clone(poll_template, "z_poll", 4272, -32),
        names["y_poll"]: clone(poll_template, "y_poll", 4528, 144),
        names["left_branch"]: clone(branch_template, "left_branch", 4272, -400),
        names["right_branch"]: clone(branch_template, "right_branch", 4272, -208),
        names["z_branch"]: clone(branch_template, "z_branch", 4528, -400),
        names["y_branch"]: clone(branch_template, "y_branch", 4784, -208),
        names["undo_documents"]: clone(undo_documents_template, "undo_documents", 4784, -32, "UndoDraftV1"),
        names["redo_documents"]: clone(redo_documents_template, "redo_documents", 5040, 320, "RedoDraftV1"),
        names["undo_length"]: clone(length_template, "undo_length", 5040, -32, "UndoDraftV1"),
        names["redo_length"]: clone(length_template, "redo_length", 5296, 320, "UndoDraftV1"),
        names["undo_available"]: clone(greater_template, "undo_available", 5296, -32, "UndoDraftV1"),
        names["redo_available"]: clone(greater_template, "redo_available", 5552, 320, "UndoDraftV1"),
        names["undo_available_branch"]: clone(branch_template, "undo_available_branch", 5296, -400),
        names["redo_available_branch"]: clone(branch_template, "redo_available_branch", 5552, -208),
        names["undo_call"]: retarget_self_call(clone(call_template, "undo_call", 5552, -528), "UndoDraftV1"),
        names["redo_call"]: retarget_self_call(clone(call_template, "redo_call", 5808, -336), "RedoDraftV1"),
        names["undo_applied"]: clone(print_template, "undo_applied", 5808, -528),
        names["undo_empty"]: clone(print_template, "undo_empty", 5552, -720),
        names["redo_applied"]: clone(print_template, "redo_applied", 6064, -336),
        names["redo_empty"]: clone(print_template, "redo_empty", 5808, -144),
        names["undo_status"]: clone(print_template, "undo_status", 6064, -528),
        names["redo_status"]: clone(print_template, "redo_status", 6320, -336),
    }
    additions[names["left_ctrl"]] = set_explicit_default(h, additions[names["left_ctrl"]], "Key", "LeftControl")
    additions[names["right_ctrl"]] = set_explicit_default(h, additions[names["right_ctrl"]], "Key", "RightControl")
    additions[names["z_poll"]] = set_explicit_default(h, additions[names["z_poll"]], "Key", "Z")
    additions[names["y_poll"]] = set_explicit_default(h, additions[names["y_poll"]], "Key", "Y")
    for label, value in (
        ("undo_applied", UNDO_APPLIED),
        ("undo_empty", UNDO_EMPTY),
        ("redo_applied", REDO_APPLIED),
        ("redo_empty", REDO_EMPTY),
    ):
        additions[names[label]] = set_explicit_default(h, additions[names[label]], "InString", value)

    blocks = dict(by_name)
    blocks.update(additions)
    update_name = h.block_name(update_branch)
    speed_name = h.block_name(speed)
    blocks[update_name] = remove_link(h, blocks[update_name], "else", speed_name)
    blocks[speed_name] = remove_link(h, blocks[speed_name], "execute", update_name)

    def c(left: str, left_pin: str, right: str, right_pin: str) -> None:
        h.connect(blocks, left, left_pin, right, right_pin)

    controller_name = h.block_name(controller)
    c(controller_name, "ReturnValue", names["left_ctrl"], "self")
    c(controller_name, "ReturnValue", names["right_ctrl"], "self")
    c(controller_name, "ReturnValue", names["z_poll"], "self")
    c(controller_name, "ReturnValue", names["y_poll"], "self")
    c(update_name, "else", names["left_branch"], "execute")
    c(names["left_ctrl"], "ReturnValue", names["left_branch"], "Condition")
    c(names["left_branch"], "then", names["z_branch"], "execute")
    c(names["left_branch"], "else", names["right_branch"], "execute")
    c(names["right_ctrl"], "ReturnValue", names["right_branch"], "Condition")
    c(names["right_branch"], "then", names["z_branch"], "execute")
    c(names["right_branch"], "else", speed_name, "execute")
    c(names["z_poll"], "ReturnValue", names["z_branch"], "Condition")
    c(names["z_branch"], "then", names["undo_available_branch"], "execute")
    c(names["z_branch"], "else", names["y_branch"], "execute")
    c(names["y_poll"], "ReturnValue", names["y_branch"], "Condition")
    c(names["y_branch"], "then", names["redo_available_branch"], "execute")
    c(names["y_branch"], "else", speed_name, "execute")

    for side in ("undo", "redo"):
        c(names[f"{side}_documents"], f"{side.title()}DocumentsV1", names[f"{side}_length"], "TargetArray")
        c(names[f"{side}_length"], "ReturnValue", names[f"{side}_available"], "A")
        c(names[f"{side}_available"], "ReturnValue", names[f"{side}_available_branch"], "Condition")
        c(names[f"{side}_available_branch"], "then", names[f"{side}_call"], "execute")
        c(names[f"{side}_available_branch"], "else", names[f"{side}_empty"], "execute")
        c(names[f"{side}_call"], "then", names[f"{side}_applied"], "execute")
        c(names[f"{side}_applied"], "then", names[f"{side}_status"], "execute")
        c(h.block_name(status_builder), "ReturnValue", names[f"{side}_status"], "InString")

    original_names = set(by_name)
    output = [blocks[h.block_name(block)] for block in source_blocks]
    output.extend(blocks[name] for name in additions if name not in original_names)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(output) + "\n", encoding="utf-8")
    print("Added Ctrl+Z/Ctrl+Y draft history dispatch and diagnostics.")


if __name__ == "__main__":
    main()
