"""Build the minimal native-node probe needed by repository decoders.

These clipboard forms are derived only from editor-harvested siblings.  They
remain probe material until Unreal reconstructs, compiles, and exports them from
the disposable JSON-node Blueprint.  Production decoder builders consume only
the accepted exported fixture, never this speculative output directly.
"""

from __future__ import annotations

import argparse
import importlib.util
import re
import sys
from pathlib import Path


TARGET_ASSET = (
    "/Game/Mods/ExileDroneDirector/Developer/Automation/"
    "BP_EDD_JsonNodeProbe.BP_EDD_JsonNodeProbe"
)
TARGET_GRAPH = "ProbeJsonNodesV1"


def load_helpers(project_root: Path):
    path = project_root / "tools" / "blueprint" / "Build-WaypointCaptureGraph.py"
    spec = importlib.util.spec_from_file_location("edd_decoder_native_probe_base", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load graph helpers: {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    module.TARGET_ASSET = TARGET_ASSET
    module.TARGET_GRAPH = TARGET_GRAPH
    return module


def mutate_pin(node, pin_name: str, mutate) -> None:
    node.mutate_pin(pin_name, mutate)


def float_pin(line: str) -> str:
    line = line.replace('PinType.PinSubCategory="double"', 'PinType.PinSubCategory="float"')
    return line


def string_pin(line: str) -> str:
    line = line.replace('PinType.PinCategory="real"', 'PinType.PinCategory="string"')
    line = line.replace('PinType.PinSubCategory="double"', 'PinType.PinSubCategory=""')
    line = re.sub(r',DefaultValue="[^"]*"', '', line)
    line = re.sub(r',AutogeneratedDefaultValue="[^"]*"', '', line)
    return line


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-root", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    bp = load_helpers(args.project_root)
    root = args.project_root / "tools" / "blueprint"
    sync = bp.read_blocks(root / "snippets" / "sync-draft-waypoints-v1.eddgraph")
    math = bp.read_blocks(root / "templates" / "repository-codec-math-node-forms.eddgraph")

    array_item = bp.Node.clone(
        "float_array_item",
        bp.find_block(
            sync,
            r'^Begin Object Class=/Script/BlueprintGraph\.K2Node_GetArrayItem ',
        ),
        "K2Node_GetArrayItem_200",
        4096,
        1024,
    )
    for pin_name in ("Array", "Output"):
        mutate_pin(array_item, pin_name, float_pin)
    # A standalone probe must use a deterministic literal index.
    bp.set_pin_default(array_item, "Dimension 1", "0")

    equal_string = bp.Node.clone(
        "equal_string",
        bp.find_block(sync, r'MemberName="EqualEqual_DoubleDouble"'),
        "K2Node_CallFunction_200",
        4352,
        1024,
    )
    equal_string.text = equal_string.text.replace(
        "/Script/Engine.KismetMathLibrary", "/Script/Engine.KismetStringLibrary"
    )
    equal_string.text = equal_string.text.replace(
        'MemberName="EqualEqual_DoubleDouble"', 'MemberName="EqualEqual_StrStr"'
    )
    equal_string.text = equal_string.text.replace(
        "/Script/Engine.Default__KismetMathLibrary",
        "/Script/Engine.Default__KismetStringLibrary",
    )
    for pin_name in ("A", "B"):
        mutate_pin(equal_string, pin_name, string_pin)

    quat_rotator = bp.Node.clone(
        "quat_rotator",
        bp.find_block(math, r'MemberName="Quat_Rotator"'),
        "K2Node_CallFunction_201",
        4608,
        1024,
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        "\n".join(node.text for node in (array_item, equal_string, quat_rotator)) + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
