"""Build scrub-safe absolute-time evaluation of a compiled position route."""
from __future__ import annotations
import argparse, importlib.util, re, sys
from pathlib import Path

FUNCTION = "EvaluateCompiledPositionRouteV1"
TARGET_CLASS = '"/Script/Engine.BlueprintGeneratedClass\'/Game/Mods/ExileDroneDirector/Core/Client/BPC_EDD_ClientDirector.BPC_EDD_ClientDirector_C\'"'

def load(root):
    path=root/"tools/blueprint/Build-TrajectoryScalarEvaluatorGraphs.py";spec=importlib.util.spec_from_file_location("edd_position_eval_base",path);module=importlib.util.module_from_spec(spec);sys.modules[spec.name]=module;spec.loader.exec_module(module);return module

def kind(node,pin,value,array=False):
    category,subcategory,obj={"bool":("bool","","None"),"int":("int","","None"),"real":("real","double","None"),"string":("string","","None"),"vector":("struct","",'"/Script/CoreUObject.ScriptStruct\'/Script/CoreUObject.Vector\'"')}[value]
    def mutate(line):
        line=re.sub(r'PinType.PinCategory="[^"]*"',f'PinType.PinCategory="{category}"',line,1);line=re.sub(r'PinType.PinSubCategory="[^"]*"',f'PinType.PinSubCategory="{subcategory}"',line,1);line=re.sub(r'PinType.PinSubCategoryObject=(?:None|"[^"]*")',f'PinType.PinSubCategoryObject={obj}',line,1);return re.sub(r'PinType.ContainerType=(?:None|Array)',f'PinType.ContainerType={"Array" if array else "None"}',line,1)
    node.mutate_pin(pin,mutate)

def variable(scalar,node,name,value,array=False):
    scalar.retarget_variable(node,name,"real" if value=="int" else value);kind(node,name,value,array)
    if "Output_Get" in node.pins:kind(node,"Output_Get",value)

def main():
    p=argparse.ArgumentParser();p.add_argument("--project-root",type=Path,required=True);p.add_argument("--output",type=Path,required=True);p.add_argument("--paste-output",type=Path);a=p.parse_args();s=load(a.project_root);bp=s.load_helpers(a.project_root);forms=s.load_templates(a.project_root,bp);b=s.Builder(bp,forms,FUNCTION)
    sync=bp.read_blocks(a.project_root/"tools/blueprint/templates/waypoint-struct-sync-node-forms.eddgraph");edit=bp.read_blocks(a.project_root/"tools/blueprint/templates/waypoint-edit-node-forms.eddgraph");play=bp.read_blocks(a.project_root/"tools/blueprint/snippets/update-linear-playback.eddgraph");repo=bp.read_blocks(a.project_root/"tools/blueprint/live-snippets/create-private-flypath-v1.eddgraph");marker=bp.read_blocks(a.project_root/"tools/blueprint/templates/path-preview-marker-node-forms.eddgraph");translation=bp.read_blocks(a.project_root/"tools/blueprint/snippets/apply-translation-input.eddgraph")
    raw={"foreach":bp.find_block(sync,r"^Begin Object Class=/Script/BlueprintGraph.K2Node_MacroInstance"),"length":bp.find_block(edit,r'MemberName="Array_Length"'),"item":bp.find_block(play,r"^Begin Object Class=/Script/BlueprintGraph.K2Node_GetArrayItem"),"call":bp.find_block(repo,r'MemberName="ValidateRecordV1"'),"make_vector":bp.find_block(marker,r'MemberName="MakeVector"'),"vector_math":bp.find_block(translation,r'MemberName="Multiply_VectorVector"')}
    def add(key,form,x,y):
        text=raw[form];m=bp.BLOCK_RE.match(text);cls=m.group("class").rsplit(".",1)[-1];i=b.serial.get(cls,0);b.serial[cls]=i+1;n=bp.Node.clone(key,text,f"{cls}_{i}",x,y);b.nodes.append(n);return n
    def get(name,value,x,y,array=False):n=b.get(name,"real" if value=="int" else value,x,y);variable(s,n,name,value,array);return n
    def setv(name,value,x,y,default=None):n=b.set(name,"real" if value=="int" else value,x,y,default);variable(s,n,name,value);return n
    def length(source,pin,value,x,y,key):n=add(key,"length",x,y);kind(n,"TargetArray",value,True);bp.connect(source,pin,n,"TargetArray");return n
    def item(source,pin,value,index,index_pin,x,y,key):n=add(key,"item",x,y);kind(n,"Array",value,True);kind(n,"Output",value);bp.connect(source,pin,n,"Array");bp.connect(index,index_pin,n,"Dimension 1");return n
    def compare(member,left,left_pin,right,right_pin,x,y,value):
        n=b.add(f"cmp_{len(b.nodes)}","compare",x,y);s.retarget_function(n,member)
        for pin in ("A","B"):kind(n,pin,value)
        kind(n,"ReturnValue","bool");bp.connect(left,left_pin,n,"A")
        if right is None:s.set_default(n,"B",right_pin)
        else:bp.connect(right,right_pin,n,"B")
        return n
    def boolop(member,left,right,x,y):return compare(member,left,"ReturnValue",right,"ReturnValue",x,y,"bool")
    def math(member,left,left_pin,right,right_pin,x,y,value="real"):
        n=b.math(member,x,y);s.retarget_function(n,member)
        for pin in ("A","B","ReturnValue"):kind(n,pin,value)
        bp.connect(left,left_pin,n,"A")
        if right is None:s.set_default(n,"B",right_pin)
        else:bp.connect(right,right_pin,n,"B")
        return n
    def call(member,x,y):
        n=add(f"call_{member}_{len(b.nodes)}","call",x,y);n.text=re.sub(r'FunctionReference=\([^\n]*\)',f'FunctionReference=(MemberName="{member}",bSelfContext=True)',n.text,1);n.mutate_pin("self",lambda line:re.sub(r'PinType.PinSubCategoryObject="/Script/Engine.BlueprintGeneratedClass\'[^\']+\'"',f"PinType.PinSubCategoryObject={TARGET_CLASS}",line,1));return n
    def vecmath(member,left,left_pin,right,right_pin,x,y,key):
        n=add(key,"vector_math",x,y);s.retarget_function(n,member)
        for pin in ("A","B","ReturnValue"):kind(n,pin,"vector")
        bp.connect(left,left_pin,n,"A");bp.connect(right,right_pin,n,"B");return n
    def make_scalar_vector(source,pin,x,y,key):
        n=add(key,"make_vector",x,y)
        for axis in "XYZ":bp.connect(source,pin,n,axis)
        return n
    def failure(root,root_pin,x,y):
        chain=[setv("PositionRouteResultSegmentIndexV1","int",x,y,"-1"),setv("PositionRouteResultLocalTimeAlphaV1","real",x+256,y,"0.0"),setv("PositionRouteResultDistanceAlphaV1","real",x+512,y,"0.0"),setv("PositionRouteResultCurveUV1","real",x+768,y,"0.0"),setv("PositionRouteResultPositionV1","vector",x+1024,y,"0, 0, 0"),setv("PositionRouteResultCompleteV1","bool",x+1280,y,"false"),setv("PositionRouteResultValidV1","bool",x+1536,y,"false"),setv("TrajectoryResultValidV1","bool",x+1792,y,"false"),setv("TrajectoryArcResultValidV1","bool",x+2048,y,"false"),setv("TrajectoryResultVectorValidV1","bool",x+2304,y,"false")];bp.connect(root,root_pin,chain[0],"execute")
        for left,right in zip(chain,chain[1:]):bp.connect(left,"then",right,"execute")

    results=(("PositionRouteResultSegmentIndexV1","int","-1"),("PositionRouteResultLocalTimeAlphaV1","real","0.0"),("PositionRouteResultDistanceAlphaV1","real","0.0"),("PositionRouteResultCurveUV1","real","0.0"),("PositionRouteResultPositionV1","vector","0, 0, 0"),("PositionRouteResultCompleteV1","bool","false"),("PositionRouteResultValidV1","bool","false"))
    reset=[setv(name,value,256+i*256,2048,default) for i,(name,value,default) in enumerate(results)];bp.connect(b.entry,"then",reset[0],"execute")
    for left,right in zip(reset,reset[1:]):bp.connect(left,"then",right,"execute")
    primitive_resets=[setv("TrajectoryResultValidV1","bool",2048,2048,"false"),setv("TrajectoryArcResultValidV1","bool",2304,2048,"false"),setv("TrajectoryResultVectorValidV1","bool",2560,2048,"false")];bp.connect(reset[-1],"then",primitive_resets[0],"execute")
    for left,right in zip(primitive_resets,primitive_resets[1:]):bp.connect(left,"then",right,"execute")

    elapsed=get("PositionRouteInputElapsedSecondsV1","real",0,0);compile_valid=get("PositionRouteCompileValidV1","bool",0,160);positions=get("PositionRouteCompiledWaypointPositionsV1","vector",0,320,True);durations=get("PositionRouteCompiledDurationsV1","real",0,480,True);curves=get("PositionRouteCompiledSpatialCurveTypesV1","string",0,640,True);profiles=get("PositionRouteCompiledTimeProfilesV1","string",0,800,True);velocities=get("PositionRouteCompiledWaypointVelocitiesV1","vector",0,960,True);starts=get("PositionRouteCompiledSegmentStartsV1","real",0,1120,True);arc_starts=get("PositionRouteCompiledArcSampleStartsV1","int",0,1280,True);arc_counts=get("PositionRouteCompiledArcSampleCountsV1","int",0,1440,True);arc_us=get("PositionRouteCompiledArcUsV1","real",0,1600,True);arc_ds=get("PositionRouteCompiledArcDistancesV1","real",0,1760,True);lengths=get("PositionRouteCompiledSegmentLengthsV1","real",0,1920,True);total=get("PositionRouteCompiledTotalSecondsV1","real",0,2080)
    specs=((positions,"PositionRouteCompiledWaypointPositionsV1","vector"),(durations,"PositionRouteCompiledDurationsV1","real"),(curves,"PositionRouteCompiledSpatialCurveTypesV1","string"),(profiles,"PositionRouteCompiledTimeProfilesV1","string"),(velocities,"PositionRouteCompiledWaypointVelocitiesV1","vector"),(starts,"PositionRouteCompiledSegmentStartsV1","real"),(arc_starts,"PositionRouteCompiledArcSampleStartsV1","int"),(arc_counts,"PositionRouteCompiledArcSampleCountsV1","int"),(arc_us,"PositionRouteCompiledArcUsV1","real"),(arc_ds,"PositionRouteCompiledArcDistancesV1","real"),(lengths,"PositionRouteCompiledSegmentLengthsV1","real"))
    lens=[length(*spec,320+i*224,0+(i%4)*160,f"len_{i}") for i,spec in enumerate(specs)];segment_count=lens[1];plus_one=math("Add_IntInt",segment_count,"ReturnValue",None,"1",992,640,"int")
    guards=[b.finite(elapsed,"PositionRouteInputElapsedSecondsV1",320,2240),compare("Greater_IntInt",segment_count,"ReturnValue",None,"0",544,2240,"int"),compare("EqualEqual_IntInt",lens[0],"ReturnValue",plus_one,"ReturnValue",768,2240,"int"),compare("EqualEqual_IntInt",lens[2],"ReturnValue",segment_count,"ReturnValue",992,2240,"int"),compare("EqualEqual_IntInt",lens[3],"ReturnValue",segment_count,"ReturnValue",1216,2240,"int"),compare("EqualEqual_IntInt",lens[4],"ReturnValue",plus_one,"ReturnValue",1440,2240,"int"),compare("EqualEqual_IntInt",lens[5],"ReturnValue",segment_count,"ReturnValue",1664,2240,"int"),compare("EqualEqual_IntInt",lens[6],"ReturnValue",segment_count,"ReturnValue",1888,2240,"int"),compare("EqualEqual_IntInt",lens[7],"ReturnValue",segment_count,"ReturnValue",2112,2240,"int"),compare("EqualEqual_IntInt",lens[8],"ReturnValue",lens[9],"ReturnValue",2336,2240,"int"),compare("EqualEqual_IntInt",lens[10],"ReturnValue",segment_count,"ReturnValue",2560,2240,"int"),b.finite(total,"PositionRouteCompiledTotalSecondsV1",2784,2240),compare("Greater_DoubleDouble",total,"PositionRouteCompiledTotalSecondsV1",None,"0.0",3008,2240,"real")]
    wrapped=b.add("compile_wrap","compare",320,2448);s.retarget_function(wrapped,"BooleanAND");[kind(wrapped,p,"bool") for p in ("A","B","ReturnValue")];bp.connect(compile_valid,"PositionRouteCompileValidV1",wrapped,"A");s.set_default(wrapped,"B","true");combined=wrapped
    for i,g in enumerate(guards):combined=boolop("BooleanAND",combined,g,544+i*208,2448)
    outer=b.add("outer","branch",3456,2048);bp.connect(primitive_resets[-1],"then",outer,"execute");bp.connect(combined,"ReturnValue",outer,"Condition")
    clamped=b.add("clamped_elapsed","clamp",3456,1760);s.set_default(clamped,"Min","0.0");bp.connect(elapsed,"PositionRouteInputElapsedSecondsV1",clamped,"Value");bp.connect(total,"PositionRouteCompiledTotalSecondsV1",clamped,"Max")
    complete_cmp=compare("GreaterEqual_DoubleDouble",elapsed,"PositionRouteInputElapsedSecondsV1",total,"PositionRouteCompiledTotalSecondsV1",3680,1760,"real");complete_branch=b.add("complete_branch","branch",3680,2048);bp.connect(outer,"then",complete_branch,"execute");bp.connect(complete_cmp,"ReturnValue",complete_branch,"Condition")
    last_index=math("Subtract_IntInt",segment_count,"ReturnValue",None,"1",3904,1440,"int");last_position=item(positions,"PositionRouteCompiledWaypointPositionsV1","vector",segment_count,"ReturnValue",3904,1600,"last_position")
    complete=[setv("PositionRouteResultSegmentIndexV1","int",3904,2048),setv("PositionRouteResultLocalTimeAlphaV1","real",4160,2048,"1.0"),setv("PositionRouteResultDistanceAlphaV1","real",4416,2048,"1.0"),setv("PositionRouteResultCurveUV1","real",4672,2048,"1.0"),setv("PositionRouteResultPositionV1","vector",4928,2048),setv("PositionRouteResultCompleteV1","bool",5184,2048,"true"),setv("PositionRouteResultValidV1","bool",5440,2048,"true")];bp.connect(complete_branch,"then",complete[0],"execute");bp.connect(last_index,"ReturnValue",complete[0],"PositionRouteResultSegmentIndexV1");bp.connect(last_position,"Output",complete[4],"PositionRouteResultPositionV1")
    for left,right in zip(complete,complete[1:]):bp.connect(left,"then",right,"execute")

    scan_valid_set=setv("TrajectoryArcScratchValidV1","bool",3648,2688,"true");loop=add("segment_loop","foreach",3904,2688);kind(loop,"Array","real",True);kind(loop,"Array Element","real");bp.connect(durations,"PositionRouteCompiledDurationsV1",loop,"Array");bp.connect(complete_branch,"else",scan_valid_set,"execute");bp.connect(scan_valid_set,"then",loop,"Exec")
    scan_duration_ok=boolop("BooleanAND",b.finite(loop,"Array Element",4160,2848),compare("Greater_DoubleDouble",loop,"Array Element",None,"0.0",4384,2848,"real"),4608,2848);scan_duration_guard=b.add("scan_duration_guard","branch",4832,2688);bp.connect(loop,"LoopBody",scan_duration_guard,"execute");bp.connect(scan_duration_ok,"ReturnValue",scan_duration_guard,"Condition");scan_invalid=setv("TrajectoryArcScratchValidV1","bool",5056,3008,"false");bp.connect(scan_duration_guard,"else",scan_invalid,"execute")
    start=item(starts,"PositionRouteCompiledSegmentStartsV1","real",loop,"Array Index",4160,2528,"start");end=math("Add_DoubleDouble",start,"Output",loop,"Array Element",4416,2528);before=compare("Less_DoubleDouble",clamped,"ReturnValue",end,"ReturnValue",4672,2528,"real");selected=get("PositionRouteResultSegmentIndexV1","int",4160,3200);unset=compare("EqualEqual_IntInt",selected,"PositionRouteResultSegmentIndexV1",None,"-1",4416,3200,"int");choose=boolop("BooleanAND",before,unset,4928,2528);choose_branch=b.add("choose_branch","branch",5184,2528);bp.connect(scan_duration_guard,"then",choose_branch,"execute");bp.connect(choose,"ReturnValue",choose_branch,"Condition");store_index=setv("PositionRouteResultSegmentIndexV1","int",5440,2528);bp.connect(choose_branch,"then",store_index,"execute");bp.connect(loop,"Array Index",store_index,"PositionRouteResultSegmentIndexV1")
    chosen=get("PositionRouteResultSegmentIndexV1","int",5184,3200);found=compare("GreaterEqual_IntInt",chosen,"PositionRouteResultSegmentIndexV1",None,"0",5440,3200,"int");scan_valid=get("TrajectoryArcScratchValidV1","bool",5440,3360);found_valid=b.add("found_valid","compare",5696,3200);s.retarget_function(found_valid,"BooleanAND");[kind(found_valid,p,"bool") for p in ("A","B","ReturnValue")];bp.connect(found,"ReturnValue",found_valid,"A");bp.connect(scan_valid,"TrajectoryArcScratchValidV1",found_valid,"B");found_branch=b.add("found_branch","branch",5952,2688);bp.connect(loop,"Completed",found_branch,"execute");bp.connect(found_valid,"ReturnValue",found_branch,"Condition");failure(found_branch,"else",6208,4480)
    selected_start=item(starts,"PositionRouteCompiledSegmentStartsV1","real",chosen,"PositionRouteResultSegmentIndexV1",6208,3200,"selected_start");duration=item(durations,"PositionRouteCompiledDurationsV1","real",chosen,"PositionRouteResultSegmentIndexV1",6208,3360,"selected_duration");profile=item(profiles,"PositionRouteCompiledTimeProfilesV1","string",chosen,"PositionRouteResultSegmentIndexV1",6208,3520,"profile");curve=item(curves,"PositionRouteCompiledSpatialCurveTypesV1","string",chosen,"PositionRouteResultSegmentIndexV1",6208,3680,"curve");next_index=math("Add_IntInt",chosen,"PositionRouteResultSegmentIndexV1",None,"1",6464,3840,"int");p0=item(positions,"PositionRouteCompiledWaypointPositionsV1","vector",chosen,"PositionRouteResultSegmentIndexV1",6720,3200,"p0");p1=item(positions,"PositionRouteCompiledWaypointPositionsV1","vector",next_index,"ReturnValue",6720,3360,"p1");v0=item(velocities,"PositionRouteCompiledWaypointVelocitiesV1","vector",chosen,"PositionRouteResultSegmentIndexV1",6720,3520,"v0");v1=item(velocities,"PositionRouteCompiledWaypointVelocitiesV1","vector",next_index,"ReturnValue",6720,3680,"v1")
    duration_ok=boolop("BooleanAND",b.finite(duration,"Output",6464,4000),compare("Greater_DoubleDouble",duration,"Output",None,"0.0",6720,4000,"real"),6976,4000);duration_branch=b.add("duration_branch","branch",6976,2688);bp.connect(found_branch,"then",duration_branch,"execute");bp.connect(duration_ok,"ReturnValue",duration_branch,"Condition");failure(duration_branch,"else",7232,4640)
    relative=math("Subtract_DoubleDouble",clamped,"ReturnValue",selected_start,"Output",6720,3200);local=math("Divide_DoubleDouble",relative,"ReturnValue",duration,"Output",6976,3200);stage_profile=setv("TrajectoryInputProfileV1","string",6720,2688);stage_alpha=setv("TrajectoryInputAlphaV1","real",6976,2688);bp.connect(duration_branch,"then",stage_profile,"execute");bp.connect(profile,"Output",stage_profile,"TrajectoryInputProfileV1");bp.connect(stage_profile,"then",stage_alpha,"execute");bp.connect(local,"ReturnValue",stage_alpha,"TrajectoryInputAlphaV1");time_call=call("EvaluateTimeProfileV1",7232,2688);bp.connect(stage_alpha,"then",time_call,"execute");time_valid=get("TrajectoryResultValidV1","bool",7232,2400);time_guard=b.add("time_guard","branch",7488,2688);bp.connect(time_call,"then",time_guard,"execute");bp.connect(time_valid,"TrajectoryResultValidV1",time_guard,"Condition");failure(time_guard,"else",7744,4800)
    distance=get("TrajectoryResultValueV1","real",7488,2400);distance_clamped=b.add("distance_clamped","clamp",7744,2400);s.set_default(distance_clamped,"Min","0.0");s.set_default(distance_clamped,"Max","1.0");bp.connect(distance,"TrajectoryResultValueV1",distance_clamped,"Value");store_local=setv("PositionRouteResultLocalTimeAlphaV1","real",7744,2688);store_distance=setv("PositionRouteResultDistanceAlphaV1","real",8000,2688);bp.connect(time_guard,"then",store_local,"execute");bp.connect(local,"ReturnValue",store_local,"PositionRouteResultLocalTimeAlphaV1");bp.connect(store_local,"then",store_distance,"execute");bp.connect(distance_clamped,"ReturnValue",store_distance,"PositionRouteResultDistanceAlphaV1");slice_call=call("StagePositionRouteArcSliceV1",8256,2688);bp.connect(store_distance,"then",slice_call,"execute");slice_valid=get("TrajectoryArcResultValidV1","bool",8256,2400);slice_guard=b.add("slice_guard","branch",8512,2688);bp.connect(slice_call,"then",slice_guard,"execute");bp.connect(slice_valid,"TrajectoryArcResultValidV1",slice_guard,"Condition");failure(slice_guard,"else",8768,4960)
    invert_call=call("InvertArcLengthTableV1",8768,2688);bp.connect(slice_guard,"then",invert_call,"execute");arc_valid=get("TrajectoryArcResultValidV1","bool",8768,2400);arc_guard=b.add("arc_guard","branch",9024,2688);bp.connect(invert_call,"then",arc_guard,"execute");bp.connect(arc_valid,"TrajectoryArcResultValidV1",arc_guard,"Condition");failure(arc_guard,"else",9280,5120);u=get("TrajectoryArcResultUV1","real",9024,2400)
    is_linear=b.equal_string(9280,3200,"linear");bp.connect(curve,"Output",is_linear,"A");is_auto=b.equal_string(9280,3360,"auto_cinematic");bp.connect(curve,"Output",is_auto,"A");curve_known=boolop("BooleanOR",is_linear,is_auto,9536,3280);curve_guard=b.add("curve_guard","branch",9536,2688);bp.connect(arc_guard,"then",curve_guard,"execute");bp.connect(curve_known,"ReturnValue",curve_guard,"Condition");failure(curve_guard,"else",9792,5280);linear_branch=b.add("linear_branch","branch",9792,2688);bp.connect(curve_guard,"then",linear_branch,"execute");bp.connect(is_linear,"ReturnValue",linear_branch,"Condition")
    delta=vecmath("Subtract_VectorVector",p1,"Output",p0,"Output",10048,3040,"delta");uvec=make_scalar_vector(u,"TrajectoryArcResultUV1",10048,3200,"u_vector");scaled=vecmath("Multiply_VectorVector",delta,"ReturnValue",uvec,"ReturnValue",10304,3040,"scaled");linear_position=vecmath("Add_VectorVector",p0,"Output",scaled,"ReturnValue",10560,3040,"linear_position")
    duration_vec=make_scalar_vector(duration,"Output",10048,3520,"duration_vector");sv0=vecmath("Multiply_VectorVector",v0,"Output",duration_vec,"ReturnValue",10304,3520,"scaled_v0");sv1=vecmath("Multiply_VectorVector",v1,"Output",duration_vec,"ReturnValue",10304,3680,"scaled_v1")
    staged=[]
    for name,value,source,pin,default in (("TrajectoryInputStartPositionVectorV1","vector",p0,"Output",None),("TrajectoryInputStartVelocityUVectorV1","vector",sv0,"ReturnValue",None),("TrajectoryInputStartAccelerationUVectorV1","vector",None,"","0, 0, 0"),("TrajectoryInputEndPositionVectorV1","vector",p1,"Output",None),("TrajectoryInputEndVelocityUVectorV1","vector",sv1,"ReturnValue",None),("TrajectoryInputEndAccelerationUVectorV1","vector",None,"","0, 0, 0"),("TrajectoryInputAlphaV1","real",u,"TrajectoryArcResultUV1",None)):
        n=setv(name,value,10048+len(staged)*256,2880,default)
        if source is not None:bp.connect(source,pin,n,name)
        staged.append(n)
    bp.connect(linear_branch,"else",staged[0],"execute")
    for left,right in zip(staged,staged[1:]):bp.connect(left,"then",right,"execute")
    vector_call=call("EvaluateQuinticVectorV1",11840,2880);bp.connect(staged[-1],"then",vector_call,"execute");vector_valid=get("TrajectoryResultVectorValidV1","bool",11840,2560);vector_guard=b.add("vector_guard","branch",12096,2880);bp.connect(vector_call,"then",vector_guard,"execute");bp.connect(vector_valid,"TrajectoryResultVectorValidV1",vector_guard,"Condition");failure(vector_guard,"else",12352,5440);vector_position=get("TrajectoryResultPositionVectorV1","vector",12096,2560)
    def accept(root,root_pin,position,position_pin,x,y):
        chain=[setv("PositionRouteResultCurveUV1","real",x,y),setv("PositionRouteResultPositionV1","vector",x+256,y),setv("PositionRouteResultCompleteV1","bool",x+512,y,"false"),setv("PositionRouteResultValidV1","bool",x+768,y,"true")];bp.connect(root,root_pin,chain[0],"execute");bp.connect(u,"TrajectoryArcResultUV1",chain[0],"PositionRouteResultCurveUV1");bp.connect(position,position_pin,chain[1],"PositionRouteResultPositionV1")
        for left,right in zip(chain,chain[1:]):bp.connect(left,"then",right,"execute")
    accept(linear_branch,"then",linear_position,"ReturnValue",10816,2688);accept(vector_guard,"then",vector_position,"TrajectoryResultPositionVectorV1",12352,2880)
    full="\n".join(n.text for n in b.nodes)+"\n";a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(full,encoding="utf-8")
    if a.paste_output:
        body=[re.sub(r',LinkedTo=\(K2Node_FunctionEntry_0 [0-9A-F]{32},\)',"",n.text) for n in b.nodes[1:]];a.paste_output.parent.mkdir(parents=True,exist_ok=True);a.paste_output.write_text("\n".join(body)+"\n",encoding="utf-8")

if __name__=="__main__":main()
