"""Build client-owned path-preview refresh and teardown Blueprint graphs.

The lifecycle is intentionally small and idempotent. Refresh reuses a valid
preview actor or spawns exactly one replacement, then copies the typed draft
document and rebuilds it. Destroy clears the pools, destroys a valid actor, and
always resets the client reference.
"""

from __future__ import annotations

import argparse
import importlib.util
import re
import sys
from pathlib import Path


CLIENT_ASSET = (
    "/Game/Mods/ExileDroneDirector/Core/Client/"
    "BPC_EDD_ClientDirector.BPC_EDD_ClientDirector"
)
CLIENT_CLASS = (
    "/Script/Engine.BlueprintGeneratedClass'"
    "/Game/Mods/ExileDroneDirector/Core/Client/"
    "BPC_EDD_ClientDirector.BPC_EDD_ClientDirector_C'"
)
PREVIEW_CLASS = (
    "/Script/Engine.BlueprintGeneratedClass'"
    "/Game/Mods/ExileDroneDirector/Trajectory/"
    "BP_EDD_PathPreview.BP_EDD_PathPreview_C'"
)
PREVIEW_CLASS_OBJECT = (
    "/Game/Mods/ExileDroneDirector/Trajectory/"
    "BP_EDD_PathPreview.BP_EDD_PathPreview_C"
)
DOCUMENT_STRUCT = (
    "/Script/CoreUObject.UserDefinedStruct'"
    "/Game/Mods/ExileDroneDirector/Data/Structs/"
    "ST_EDD_FlypathDocument.ST_EDD_FlypathDocument'"
)
PREVIEW_REFERENCE_GUID = "FF2D60F147CBC731A2FB40871C8D696C"
PREVIEW_DOCUMENT_GUID = "44C509A84FDB416D84C4259C700C5C2D"
CLEAR_PREVIEW_GUID = "3D24364D45F3786EA8BA478D3FB63FB2"


def load_helpers(project_root: Path):
    path = project_root / "tools" / "blueprint" / "Build-WaypointCaptureGraph.py"
    spec = importlib.util.spec_from_file_location("edd_preview_lifecycle_base", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load shared graph builder: {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def set_function_entry(node, function_name: str) -> None:
    node.text = re.sub(
        r'FunctionReference=\(MemberName="[^"]+"\)',
        f'FunctionReference=(MemberName="{function_name}")',
        node.text,
        count=1,
    )


def set_pin_object_type(node, pin_name: str, object_type: str, *, hidden: bool | None = None) -> None:
    def mutate(line: str) -> str:
        line = re.sub(r'PinType\.PinCategory="[^"]+"', 'PinType.PinCategory="object"', line, count=1)
        line = re.sub(
            r'PinType\.PinSubCategoryObject=(?:None|"[^"]+")',
            f'PinType.PinSubCategoryObject="{object_type}"',
            line,
            count=1,
        )
        if hidden is not None:
            line = re.sub(r'bHidden=(?:True|False)', f'bHidden={str(hidden)}', line, count=1)
        return line

    node.mutate_pin(pin_name, mutate)


def set_pin_document_type(node, pin_name: str) -> None:
    def mutate(line: str) -> str:
        line = re.sub(r'PinType\.PinCategory="[^"]+"', 'PinType.PinCategory="struct"', line, count=1)
        line = re.sub(
            r'PinType\.PinSubCategoryObject=(?:None|"[^"]+")',
            f'PinType.PinSubCategoryObject="{DOCUMENT_STRUCT}"',
            line,
            count=1,
        )
        line = re.sub(r',DefaultValue="[^"]*"', '', line)
        line = re.sub(r',AutogeneratedDefaultValue="[^"]*"', '', line)
        return line

    node.mutate_pin(pin_name, mutate)


def retarget_preview_reference(node) -> None:
    node.text = re.sub(
        r'VariableReference=\(MemberName="DroneCameraRef"[^)]*\)',
        'VariableReference=(MemberName="PathPreviewActorV1",'
        f'MemberGuid={PREVIEW_REFERENCE_GUID},bSelfContext=True)',
        node.text,
        count=1,
    )
    node.text = node.text.replace('PinName="DroneCameraRef"', 'PinName="PathPreviewActorV1"')
    node.pins["PathPreviewActorV1"] = node.pins.pop("DroneCameraRef")
    set_pin_object_type(node, "PathPreviewActorV1", PREVIEW_CLASS)
    if "Output_Get" in node.pins:
        set_pin_object_type(node, "Output_Get", PREVIEW_CLASS)


def retarget_draft_document_getter(node) -> None:
    node.text = re.sub(
        r'VariableReference=\(MemberName="DroneCameraRef"[^)]*\)',
        'VariableReference=(MemberName="DraftDocumentV1",bSelfContext=True)',
        node.text,
        count=1,
    )
    node.text = node.text.replace('PinName="DroneCameraRef"', 'PinName="DraftDocumentV1"')
    node.pins["DraftDocumentV1"] = node.pins.pop("DroneCameraRef")
    set_pin_document_type(node, "DraftDocumentV1")


def retarget_external_document_setter(node) -> None:
    node.text = re.sub(
        r'VariableReference=\(MemberName="DroneCameraRef"[^)]*\)',
        'VariableReference=(MemberParent="'
        + PREVIEW_CLASS
        + '",MemberName="PreviewDocumentV1",MemberGuid='
        + PREVIEW_DOCUMENT_GUID
        + ')',
        node.text,
        count=1,
    )
    node.text = node.text.replace('PinName="DroneCameraRef"', 'PinName="PreviewDocumentV1"')
    node.pins["PreviewDocumentV1"] = node.pins.pop("DroneCameraRef")
    set_pin_document_type(node, "PreviewDocumentV1")
    set_pin_document_type(node, "Output_Get")
    set_pin_object_type(node, "self", PREVIEW_CLASS, hidden=False)


def retarget_external_preview_call(node, function_name: str, function_guid: str | None = None) -> None:
    pieces = [f'MemberParent="{PREVIEW_CLASS}"', f'MemberName="{function_name}"']
    if function_guid:
        pieces.append(f"MemberGuid={function_guid}")
    node.text = re.sub(
        r'FunctionReference=\([^)]*\)',
        f'FunctionReference=({",".join(pieces)})',
        node.text,
        count=1,
    )
    set_pin_object_type(node, "self", PREVIEW_CLASS, hidden=False)


def retarget_destroy_actor(node) -> None:
    node.text = re.sub(
        r'FunctionReference=\([^)]*\)',
        'FunctionReference=(MemberParent="/Script/CoreUObject.Class\'/Script/Engine.Actor\'",'
        'MemberName="K2_DestroyActor")',
        node.text,
        count=1,
    )
    set_pin_object_type(
        node,
        "self",
        "/Script/CoreUObject.Class'/Script/Engine.Actor'",
        hidden=False,
    )


def retarget_spawn(node) -> None:
    node.mutate_pin(
        "Class",
        lambda line: re.sub(
            r'DefaultObject="[^"]+"',
            f'DefaultObject="{PREVIEW_CLASS_OBJECT}"',
            line,
            count=1,
        ),
    )
    set_pin_object_type(node, "ReturnValue", PREVIEW_CLASS)
    node.mutate_pin(
        "CollisionHandlingOverride",
        lambda line: re.sub(
            r'DefaultValue="[^"]*"',
            'DefaultValue="AlwaysSpawn"',
            line,
            count=1,
        ),
    )


def build(project_root: Path, graph_name: str):
    bp = load_helpers(project_root)
    bp.TARGET_ASSET = CLIENT_ASSET
    bp.TARGET_GRAPH = graph_name

    snippets = project_root / "tools" / "blueprint" / "snippets"
    forms = project_root / "tools" / "blueprint" / "templates"
    enter = bp.read_blocks(snippets / "enter-drone-mode.eddgraph")
    capture = bp.read_blocks(forms / "waypoint-capture-node-forms.eddgraph")
    clear = bp.read_blocks(snippets / "clear-path-preview-v1.eddgraph")
    templates = {
        "entry": bp.find_block(capture, r"^Begin Object Class=/Script/BlueprintGraph\.K2Node_FunctionEntry\b"),
        "branch": bp.find_block(enter, r"^Begin Object Class=/Script/BlueprintGraph\.K2Node_IfThenElse\b"),
        "valid": bp.find_block(enter, r"^Begin Object Class=/Script/BlueprintGraph\.K2Node_CallFunction\b.*MemberName=\"IsValid\""),
        "spawn": bp.find_block(enter, r"^Begin Object Class=/Script/BlueprintGraph\.K2Node_SpawnActorFromClass\b"),
        "make_transform": bp.find_block(enter, r"^Begin Object Class=/Script/BlueprintGraph\.K2Node_CallFunction\b.*MemberName=\"MakeTransform\""),
        "ref_get": bp.find_block(enter, r"^Begin Object Class=/Script/BlueprintGraph\.K2Node_VariableGet\b.*MemberName=\"DroneCameraRef\""),
        "ref_set": bp.find_block(enter, r"^Begin Object Class=/Script/BlueprintGraph\.K2Node_VariableSet\b.*MemberName=\"DroneCameraRef\""),
        "preview_call": bp.find_block(clear, r"^Begin Object Class=/Script/BlueprintGraph\.K2Node_CallFunction\b.*MemberName=\"ClearInstances\""),
    }
    nodes = {}

    def add(key: str, template: str, name: str, x: int, y: int):
        node = bp.Node.clone(key, templates[template], name, x, y)
        nodes[key] = node
        return node

    entry = add("entry", "entry", "K2Node_FunctionEntry_0", 0, 0)
    set_function_entry(entry, graph_name)
    ref_get = add("ref_get", "ref_get", "K2Node_VariableGet_0", 0, 256)
    retarget_preview_reference(ref_get)
    valid = add("valid", "valid", "K2Node_CallFunction_0", 256, 256)
    branch = add("branch", "branch", "K2Node_IfThenElse_0", 512, 0)
    bp.connect(entry, "then", branch, "execute")
    bp.connect(ref_get, "PathPreviewActorV1", valid, "Object")
    bp.connect(valid, "ReturnValue", branch, "Condition")

    if graph_name == "RefreshPathPreviewV1":
        document = add("document", "ref_get", "K2Node_VariableGet_1", 512, 320)
        retarget_draft_document_getter(document)

        set_existing = add("set_existing", "ref_set", "K2Node_VariableSet_0", 768, 0)
        retarget_external_document_setter(set_existing)
        rebuild_existing = add("rebuild_existing", "preview_call", "K2Node_CallFunction_1", 1056, 0)
        retarget_external_preview_call(rebuild_existing, "RebuildPreviewV1")

        spawn = add("spawn", "spawn", "K2Node_SpawnActorFromClass_0", 768, 432)
        retarget_spawn(spawn)
        spawn_transform = add("spawn_transform", "make_transform", "K2Node_CallFunction_3", 512, 720)
        ref_set = add("ref_set", "ref_set", "K2Node_VariableSet_1", 1056, 432)
        retarget_preview_reference(ref_set)
        set_spawned = add("set_spawned", "ref_set", "K2Node_VariableSet_2", 1344, 432)
        retarget_external_document_setter(set_spawned)
        rebuild_spawned = add("rebuild_spawned", "preview_call", "K2Node_CallFunction_2", 1632, 432)
        retarget_external_preview_call(rebuild_spawned, "RebuildPreviewV1")

        bp.connect(branch, "then", set_existing, "execute")
        bp.connect(ref_get, "PathPreviewActorV1", set_existing, "self")
        bp.connect(document, "DraftDocumentV1", set_existing, "PreviewDocumentV1")
        bp.connect(set_existing, "then", rebuild_existing, "execute")
        bp.connect(ref_get, "PathPreviewActorV1", rebuild_existing, "self")

        bp.connect(branch, "else", spawn, "execute")
        bp.connect(spawn_transform, "ReturnValue", spawn, "SpawnTransform")
        bp.connect(spawn, "then", ref_set, "execute")
        bp.connect(spawn, "ReturnValue", ref_set, "PathPreviewActorV1")
        bp.connect(ref_set, "then", set_spawned, "execute")
        bp.connect(ref_set, "Output_Get", set_spawned, "self")
        bp.connect(document, "DraftDocumentV1", set_spawned, "PreviewDocumentV1")
        bp.connect(set_spawned, "then", rebuild_spawned, "execute")
        bp.connect(ref_set, "Output_Get", rebuild_spawned, "self")
    elif graph_name == "DestroyPathPreviewV1":
        clear_call = add("clear", "preview_call", "K2Node_CallFunction_1", 768, 0)
        retarget_external_preview_call(clear_call, "ClearPreviewV1", CLEAR_PREVIEW_GUID)
        destroy = add("destroy", "preview_call", "K2Node_CallFunction_2", 1056, 0)
        retarget_destroy_actor(destroy)
        reset_valid = add("reset_valid", "ref_set", "K2Node_VariableSet_0", 1344, 0)
        retarget_preview_reference(reset_valid)
        reset_invalid = add("reset_invalid", "ref_set", "K2Node_VariableSet_1", 768, 352)
        retarget_preview_reference(reset_invalid)

        bp.connect(branch, "then", clear_call, "execute")
        bp.connect(ref_get, "PathPreviewActorV1", clear_call, "self")
        bp.connect(clear_call, "then", destroy, "execute")
        bp.connect(ref_get, "PathPreviewActorV1", destroy, "self")
        bp.connect(destroy, "then", reset_valid, "execute")
        bp.connect(branch, "else", reset_invalid, "execute")
    else:
        raise RuntimeError(f"Unsupported graph: {graph_name}")
    return bp, list(nodes.values())


def write_graph(bp, nodes, output: Path, paste_output: Path | None) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(node.text for node in nodes) + "\n", encoding="utf-8")
    if paste_output is None:
        return
    blocks = []
    for node in nodes:
        if node.key == "entry":
            continue
        blocks.append(
            re.sub(
                r",LinkedTo=\(K2Node_FunctionEntry_0 [0-9A-F]{32},\)",
                "",
                node.text,
            )
        )
    paste_output.parent.mkdir(parents=True, exist_ok=True)
    paste_output.write_text("\n".join(blocks) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-root", type=Path, required=True)
    parser.add_argument("--refresh-output", type=Path, required=True)
    parser.add_argument("--refresh-paste-output", type=Path)
    parser.add_argument("--destroy-output", type=Path, required=True)
    parser.add_argument("--destroy-paste-output", type=Path)
    args = parser.parse_args()

    bp, refresh = build(args.project_root, "RefreshPathPreviewV1")
    write_graph(bp, refresh, args.refresh_output, args.refresh_paste_output)
    bp, destroy = build(args.project_root, "DestroyPathPreviewV1")
    write_graph(bp, destroy, args.destroy_output, args.destroy_paste_output)


if __name__ == "__main__":
    main()
