"""Build fail-closed validation for the common authored camera scalar track."""
from __future__ import annotations
import argparse,importlib.util,re,sys
from pathlib import Path
FUNCTION="ValidateCameraScalarTrackInputsV1"
ARRAYS=(("CameraScalarTrackInputKeyTimesV1","real"),("CameraScalarTrackInputKeyValuesV1","real"),("CameraScalarTrackInputInterpolationModesV1","string"),("CameraScalarTrackInputArriveTangentsV1","real"),("CameraScalarTrackInputLeaveTangentsV1","real"))
def load(root):
 p=root/"tools/blueprint/Build-TrajectoryScalarEvaluatorGraphs.py";s=importlib.util.spec_from_file_location("edd_camera_scalar_validation_base",p);m=importlib.util.module_from_spec(s);sys.modules[s.name]=m;s.loader.exec_module(m);return m
def pin_kind(node,pin,kind,array=False):
 category,subcategory,obj={"bool":("bool","","None"),"int":("int","","None"),"real":("real","double","None"),"string":("string","","None")}[kind]
 def mutate(line):
  line=re.sub(r'PinType.PinCategory="[^"]*"',f'PinType.PinCategory="{category}"',line,1);line=re.sub(r'PinType.PinSubCategory="[^"]*"',f'PinType.PinSubCategory="{subcategory}"',line,1);line=re.sub(r'PinType.PinSubCategoryObject=(?:None|"[^"]*")',f'PinType.PinSubCategoryObject={obj}',line,1);return re.sub(r'PinType.ContainerType=(?:None|Array)',f'PinType.ContainerType={"Array" if array else "None"}',line,1)
 node.mutate_pin(pin,mutate)
def main():
 a=argparse.ArgumentParser();a.add_argument("--project-root",type=Path,required=True);a.add_argument("--output",type=Path,required=True);a.add_argument("--paste-output",type=Path);x=a.parse_args();scalar=load(x.project_root);bp=scalar.load_helpers(x.project_root);forms=scalar.load_templates(x.project_root,bp);sync=bp.read_blocks(x.project_root/"tools/blueprint/templates/waypoint-struct-sync-node-forms.eddgraph");edit=bp.read_blocks(x.project_root/"tools/blueprint/templates/waypoint-edit-node-forms.eddgraph");play=bp.read_blocks(x.project_root/"tools/blueprint/snippets/update-linear-playback.eddgraph");forms.update({"foreach":bp.find_block(sync,r"K2Node_MacroInstance"),"length":bp.find_block(edit,r'MemberName="Array_Length"'),"item":bp.find_block(play,r"^Begin Object Class=/Script/BlueprintGraph.K2Node_GetArrayItem")});b=scalar.Builder(bp,forms,FUNCTION)
 def variable(node,name,kind,array=False):scalar.retarget_variable(node,name,kind);pin_kind(node,name,kind,array);pin_kind(node,"Output_Get",kind) if "Output_Get" in node.pins else None
 def get(name,kind,x,y,array=False):n=b.add(f"get_{name}_{len(b.nodes)}","get",x,y);variable(n,name,kind,array);return n
 def set_(name,kind,x,y,value=None):n=b.add(f"set_{name}_{len(b.nodes)}","set",x,y);variable(n,name,kind);scalar.set_default(n,name,value) if value is not None else None;return n
 def add_form(key,form,x,y):
  match=bp.BLOCK_RE.match(forms[form]);cls=match.group("class").rsplit(".",1)[-1];i=b.serial.get(cls,0);b.serial[cls]=i+1;n=bp.Node.clone(key,forms[form],f"{cls}_{i}",x,y);b.nodes.append(n);return n
 def length(source,pin,kind,x,y):n=add_form(f"length_{pin}_{len(b.nodes)}","length",x,y);pin_kind(n,"TargetArray",kind,True);pin_kind(n,"ReturnValue","int");bp.connect(source,pin,n,"TargetArray");return n
 def foreach(source,pin,kind,x,y):n=add_form(f"foreach_{pin}_{len(b.nodes)}","foreach",x,y);pin_kind(n,"Array",kind,True);pin_kind(n,"Array Element",kind);pin_kind(n,"Array Index","int");bp.connect(source,pin,n,"Array");return n
 def item(source,pin,kind,index,index_pin,x,y):n=add_form(f"item_{pin}_{len(b.nodes)}","item",x,y);pin_kind(n,"Array",kind,True);pin_kind(n,"Output",kind);bp.connect(source,pin,n,"Array");bp.connect(index,index_pin,n,"Dimension 1") if index is not None else scalar.set_default(n,"Dimension 1",index_pin);return n
 def retarget(node,member,kinds):scalar.retarget_function(node,member);[pin_kind(node,p,k) for p,k in kinds.items()];return node
 def compare(member,left,left_pin,x,y,right=None,right_pin=None,default=None,kind="real"):
  n=b.add(f"{member}_{len(b.nodes)}","compare",x,y);retarget(n,member,{"A":kind,"B":kind,"ReturnValue":"bool"});bp.connect(left,left_pin,n,"A");bp.connect(right,right_pin,n,"B") if right is not None else scalar.set_default(n,"B",default);return n
 def math(member,left,left_pin,x,y,right=None,right_pin=None,default=None,kind="int"):
  n=b.math("Add_DoubleDouble",x,y);retarget(n,member,{"A":kind,"B":kind,"ReturnValue":kind});bp.connect(left,left_pin,n,"A");bp.connect(right,right_pin,n,"B") if right is not None else scalar.set_default(n,"B",default);return n
 def op(member,left,right,x,y):return compare(member,left,"ReturnValue",x,y,right,"ReturnValue",kind="bool")
 def and_all(values,x,y):
  current=values[0]
  for i,value in enumerate(values[1:]):current=op("BooleanAND",current,value,x+i*208,y)
  return current
 def or_all(values,x,y):
  current=values[0]
  for i,value in enumerate(values[1:]):current=op("BooleanOR",current,value,x+i*208,y)
  return current
 def equal_string(source,pin,value,x,y):n=b.equal_string(x,y,value);bp.connect(source,pin,n,"A");return n

 stage_false=set_("CameraScalarTrackScratchValidV1","bool",256,2560,"false");failure=set_("CameraScalarTrackFailureCodeV1","string",480,2560,"validation_failed");bp.connect(b.entry,"then",stage_false,"execute");bp.connect(stage_false,"then",failure,"execute")
 arrays={name:get(name,kind,0,i*160,True) for i,(name,kind) in enumerate(ARRAYS)};lengths={name:length(arrays[name],name,kind,256,i*160) for i,(name,kind) in enumerate(ARRAYS)};count=lengths[ARRAYS[0][0]];segments=math("Subtract_IntInt",count,"ReturnValue",480,0,default="1")
 duration=get("CameraScalarTrackInputDurationV1","real",0,960);domain=get("CameraScalarTrackInputDomainV1","string",0,1120);has_min=get("CameraScalarTrackInputHasMinimumV1","bool",0,1280);minimum=get("CameraScalarTrackInputMinimumV1","real",0,1440);has_max=get("CameraScalarTrackInputHasMaximumV1","bool",0,1600);maximum=get("CameraScalarTrackInputMaximumV1","real",0,1760)
 single=compare("EqualEqual_IntInt",count,"ReturnValue",704,0,default="1",kind="int");duration_pos=compare("Greater_DoubleDouble",duration,"CameraScalarTrackInputDurationV1",704,960,default="0.0");duration_rule=or_all([single,duration_pos],928,960);linear=equal_string(domain,"CameraScalarTrackInputDomainV1","linear",704,1120);reciprocal=equal_string(domain,"CameraScalarTrackInputDomainV1","reciprocal",704,1200);domain_valid=op("BooleanOR",linear,reciprocal,928,1120);no_min=compare("EqualEqual_BoolBool",has_min,"CameraScalarTrackInputHasMinimumV1",704,1280,default="false",kind="bool");min_finite=b.finite(minimum,"CameraScalarTrackInputMinimumV1",704,1440);min_valid=op("BooleanOR",no_min,min_finite,1120,1360);no_max=compare("EqualEqual_BoolBool",has_max,"CameraScalarTrackInputHasMaximumV1",704,1600,default="false",kind="bool");max_finite=b.finite(maximum,"CameraScalarTrackInputMaximumV1",704,1760);max_valid=op("BooleanOR",no_max,max_finite,1120,1680);both_bounds=compare("BooleanAND",has_min,"CameraScalarTrackInputHasMinimumV1",704,1920,has_max,"CameraScalarTrackInputHasMaximumV1",kind="bool");not_both=compare("EqualEqual_BoolBool",both_bounds,"ReturnValue",928,1920,default="false",kind="bool");ordered_bounds=compare("LessEqual_DoubleDouble",minimum,"CameraScalarTrackInputMinimumV1",928,2080,maximum,"CameraScalarTrackInputMaximumV1");bounds_valid=op("BooleanOR",not_both,ordered_bounds,1152,2000)
 shape=[compare("GreaterEqual_IntInt",count,"ReturnValue",704,160,default="1",kind="int"),compare("LessEqual_IntInt",count,"ReturnValue",704,320,default="512",kind="int"),compare("EqualEqual_IntInt",lengths[ARRAYS[1][0]],"ReturnValue",704,480,count,"ReturnValue",kind="int"),compare("EqualEqual_IntInt",lengths[ARRAYS[2][0]],"ReturnValue",704,640,segments,"ReturnValue",kind="int"),compare("EqualEqual_IntInt",lengths[ARRAYS[3][0]],"ReturnValue",928,480,count,"ReturnValue",kind="int"),compare("EqualEqual_IntInt",lengths[ARRAYS[4][0]],"ReturnValue",928,640,count,"ReturnValue",kind="int"),b.finite(duration,"CameraScalarTrackInputDurationV1",480,960),compare("GreaterEqual_DoubleDouble",duration,"CameraScalarTrackInputDurationV1",480,1040,default="0.0"),duration_rule,domain_valid,min_valid,max_valid,bounds_valid]
 shape_valid=and_all(shape,1568,1280);shape_branch=b.add("shape_branch","branch",4272,2560);bp.connect(failure,"then",shape_branch,"execute");bp.connect(shape_valid,"ReturnValue",shape_branch,"Condition");stage_true=set_("CameraScalarTrackScratchValidV1","bool",4496,2560,"true");bp.connect(shape_branch,"then",stage_true,"execute")
 zero_index=math("Subtract_IntInt",count,"ReturnValue",4496,0,default="1");first_time=item(arrays[ARRAYS[0][0]],ARRAYS[0][0],"real",None,"0",4720,0);last_time=item(arrays[ARRAYS[0][0]],ARRAYS[0][0],"real",zero_index,"ReturnValue",4720,160);first_arrive=item(arrays[ARRAYS[3][0]],ARRAYS[3][0],"real",None,"0",4720,320);last_leave=item(arrays[ARRAYS[4][0]],ARRAYS[4][0],"real",zero_index,"ReturnValue",4720,480)
 endpoints=and_all([compare("EqualEqual_DoubleDouble",first_time,"Output",4944,0,default="0.0"),compare("EqualEqual_DoubleDouble",last_time,"Output",4944,160,duration,"CameraScalarTrackInputDurationV1"),compare("EqualEqual_DoubleDouble",first_arrive,"Output",4944,320,default="0.0"),compare("EqualEqual_DoubleDouble",last_leave,"Output",4944,480,default="0.0")],5168,240);endpoint_branch=b.add("endpoint_branch","branch",5840,2560);bp.connect(stage_true,"then",endpoint_branch,"execute");bp.connect(endpoints,"ReturnValue",endpoint_branch,"Condition");endpoint_reject=set_("CameraScalarTrackScratchValidV1","bool",6064,2720,"false");bp.connect(endpoint_branch,"else",endpoint_reject,"execute")
 key_loop=foreach(arrays[ARRAYS[0][0]],ARRAYS[0][0],"real",6064,2560);bp.connect(endpoint_branch,"then",key_loop,"Exec");value=item(arrays[ARRAYS[1][0]],ARRAYS[1][0],"real",key_loop,"Array Index",6320,1280);arrive=item(arrays[ARRAYS[3][0]],ARRAYS[3][0],"real",key_loop,"Array Index",6320,1440);leave=item(arrays[ARRAYS[4][0]],ARRAYS[4][0],"real",key_loop,"Array Index",6320,1600);previous_index=math("Subtract_IntInt",key_loop,"Array Index",6320,1760,default="1");clamped_previous=math("Max_IntInt",previous_index,"ReturnValue",6544,1760,default="0");previous_time=item(arrays[ARRAYS[0][0]],ARRAYS[0][0],"real",clamped_previous,"ReturnValue",6768,1760);is_first=compare("EqualEqual_IntInt",key_loop,"Array Index",6544,1920,default="0",kind="int");increasing=compare("Greater_DoubleDouble",key_loop,"Array Element",6992,1760,previous_time,"Output");ordered=op("BooleanOR",is_first,increasing,7216,1840);above=compare("GreaterEqual_DoubleDouble",value,"Output",6544,2080,minimum,"CameraScalarTrackInputMinimumV1");min_policy=op("BooleanOR",no_min,above,6768,2080);below=compare("LessEqual_DoubleDouble",value,"Output",6544,2240,maximum,"CameraScalarTrackInputMaximumV1");max_policy=op("BooleanOR",no_max,below,6768,2240);positive=compare("Greater_DoubleDouble",value,"Output",6544,2400,default="0.0");domain_policy=op("BooleanOR",linear,positive,6768,2400)
 key_valid=and_all([b.finite(key_loop,"Array Element",6320,640),b.finite(value,"Output",6320,800),b.finite(arrive,"Output",6320,960),b.finite(leave,"Output",6320,1120),ordered,min_policy,max_policy,domain_policy],7440,1440);key_branch=b.add("key_branch","branch",9008,2560);bp.connect(key_loop,"LoopBody",key_branch,"execute");bp.connect(key_valid,"ReturnValue",key_branch,"Condition");key_reject=set_("CameraScalarTrackScratchValidV1","bool",9232,2720,"false");bp.connect(key_branch,"else",key_reject,"execute")
 mode_loop=foreach(arrays[ARRAYS[2][0]],ARRAYS[2][0],"string",9456,2560);bp.connect(key_loop,"Completed",mode_loop,"Exec");mode_checks=[equal_string(mode_loop,"Array Element",name,9680,640+i*112) for i,name in enumerate(("hold","linear","smooth","cinematic","hermite"))];supported=or_all(mode_checks,9904,864);is_hermite=mode_checks[-1];next_index=math("Add_IntInt",mode_loop,"Array Index",9680,1280,default="1");mode_leave=item(arrays[ARRAYS[4][0]],ARRAYS[4][0],"real",mode_loop,"Array Index",9904,1280);mode_arrive=item(arrays[ARRAYS[3][0]],ARRAYS[3][0],"real",next_index,"ReturnValue",9904,1440);leave_zero=compare("EqualEqual_DoubleDouble",mode_leave,"Output",10128,1280,default="0.0");arrive_zero=compare("EqualEqual_DoubleDouble",mode_arrive,"Output",10128,1440,default="0.0");zeros=op("BooleanAND",leave_zero,arrive_zero,10352,1360);tangents=op("BooleanOR",is_hermite,zeros,10576,1360);mode_valid=op("BooleanAND",supported,tangents,10784,1120);mode_branch=b.add("mode_branch","branch",11008,2560);bp.connect(mode_loop,"LoopBody",mode_branch,"execute");bp.connect(mode_valid,"ReturnValue",mode_branch,"Condition");mode_reject=set_("CameraScalarTrackScratchValidV1","bool",11232,2720,"false");bp.connect(mode_branch,"else",mode_reject,"execute")
 final_stage=get("CameraScalarTrackScratchValidV1","bool",11456,2240);final_branch=b.add("final_branch","branch",11680,2560);bp.connect(mode_loop,"Completed",final_branch,"execute");bp.connect(final_stage,"CameraScalarTrackScratchValidV1",final_branch,"Condition");clear_failure=set_("CameraScalarTrackFailureCodeV1","string",11904,2560,"");bp.connect(final_branch,"then",clear_failure,"execute")
 full="\n".join(n.text for n in b.nodes)+"\n";x.output.parent.mkdir(parents=True,exist_ok=True);x.output.write_text(full,encoding="utf-8")
 if x.paste_output:x.paste_output.parent.mkdir(parents=True,exist_ok=True);x.paste_output.write_text("\n".join(re.sub(r',LinkedTo=\(K2Node_FunctionEntry_0 [0-9A-F]{32},\)',"",n.text) for n in b.nodes[1:])+"\n",encoding="utf-8")
if __name__=="__main__":main()
