"""Stage one owned compiled camera channel into scalar evaluation scratch."""
from __future__ import annotations
import argparse,importlib.util,re,sys
from pathlib import Path
FUNCTION="StageCompiledCameraChannelV1";COPIES=(("CameraChannelCompiledKeyTimesV1","CameraScalarTrackCandidateKeyTimesV1","real"),("CameraChannelCompiledDomainValuesV1","CameraScalarTrackCandidateDomainValuesV1","real"),("CameraChannelCompiledArriveTangentsV1","CameraScalarTrackCandidateArriveTangentsV1","real"),("CameraChannelCompiledLeaveTangentsV1","CameraScalarTrackCandidateLeaveTangentsV1","real"))
def load(root):p=root/"tools/blueprint/Build-TrajectoryScalarEvaluatorGraphs.py";s=importlib.util.spec_from_file_location("edd_camera_channel_stage_base",p);m=importlib.util.module_from_spec(s);sys.modules[s.name]=m;s.loader.exec_module(m);return m
def kind(n,p,k,array=False):
 cat,sub={"bool":("bool",""),"int":("int",""),"real":("real","double"),"string":("string","")}[k]
 def f(line):line=re.sub(r'PinType.PinCategory="[^"]*"',f'PinType.PinCategory="{cat}"',line,1);line=re.sub(r'PinType.PinSubCategory="[^"]*"',f'PinType.PinSubCategory="{sub}"',line,1);line=re.sub(r'PinType.PinSubCategoryObject=(?:None|"[^"]*")','PinType.PinSubCategoryObject=None',line,1);return re.sub(r'PinType.ContainerType=(?:None|Array)',f'PinType.ContainerType={"Array" if array else "None"}',line,1)
 n.mutate_pin(p,f)
def main():
 p=argparse.ArgumentParser();p.add_argument("--project-root",type=Path,required=True);p.add_argument("--output",type=Path,required=True);p.add_argument("--paste-output",type=Path);a=p.parse_args();s=load(a.project_root);bp=s.load_helpers(a.project_root);forms=s.load_templates(a.project_root,bp);b=s.Builder(bp,forms,FUNCTION);edit=bp.read_blocks(a.project_root/"tools/blueprint/templates/waypoint-edit-node-forms.eddgraph");play=bp.read_blocks(a.project_root/"tools/blueprint/snippets/update-linear-playback.eddgraph");capture=bp.read_blocks(a.project_root/"tools/blueprint/templates/waypoint-capture-node-forms.eddgraph");reset=bp.read_blocks(a.project_root/"tools/blueprint/snippets/reset-adaptive-arc-build-v1.eddgraph");loops=bp.read_blocks(a.project_root/"tools/blueprint/templates/adaptive-arc-forloop-node-form.eddgraph");public=bp.read_blocks(a.project_root/"tools/blueprint/live-snippets/list-public-v1.eddgraph");template={"length":bp.find_block(edit,r'MemberName="Array_Length"'),"item":bp.find_block(play,r"^Begin Object Class=/Script/BlueprintGraph.K2Node_GetArrayItem"),"add":bp.find_block(capture,r'MemberName="Array_Add"'),"clear":bp.find_block(reset,r'MemberName="Array_Clear"'),"loop":bp.find_block(loops,r"StandardMacros:ForLoop"),"select":bp.find_block(public,r"^Begin Object Class=/Script/BlueprintGraph.K2Node_Select ")}
 def addform(key,form,x,y):raw=template[form];m=bp.BLOCK_RE.match(raw);cls=m.group("class").rsplit(".",1)[-1];i=b.serial.get(cls,0);b.serial[cls]=i+1;n=bp.Node.clone(key,raw,f"{cls}_{i}",x,y);b.nodes.append(n);return n
 def var(n,name,k,array=False):s.retarget_variable(n,name,"real" if k=="int" else k);kind(n,name,k,array);kind(n,"Output_Get",k,array) if "Output_Get" in n.pins else None
 def get(name,k,x,y,array=False):n=b.add(f"get_{name}_{len(b.nodes)}","get",x,y);var(n,name,k,array);return n
 def setv(name,k,x,y,default=None):n=b.add(f"set_{name}_{len(b.nodes)}","set",x,y);var(n,name,k);s.set_default(n,name,default) if default is not None else None;return n
 def length(src,pin,k,x,y):n=addform(f"len_{pin}_{len(b.nodes)}","length",x,y);kind(n,"TargetArray",k,True);kind(n,"ReturnValue","int");bp.connect(src,pin,n,"TargetArray");return n
 def item(src,pin,k,index,indexpin,x,y):n=addform(f"item_{pin}_{len(b.nodes)}","item",x,y);kind(n,"Array",k,True);kind(n,"Output",k);bp.connect(src,pin,n,"Array");bp.connect(index,indexpin,n,"Dimension 1");return n
 def arrayop(form,src,pin,k,x,y,new=None,newpin=None):n=addform(f"{form}_{pin}_{len(b.nodes)}",form,x,y);kind(n,"TargetArray",k,True);bp.connect(src,pin,n,"TargetArray");kind(n,"NewItem",k) if form=="add" else None;kind(n,"ReturnValue","int") if form=="add" else None;bp.connect(new,newpin,n,"NewItem") if form=="add" else None;return n
 def cmp(member,left,leftpin,x,y,right=None,rightpin=None,default=None,k="int"):n=b.add(f"cmp_{member}_{len(b.nodes)}","compare",x,y);s.retarget_function(n,member);kind(n,"A",k);kind(n,"B",k);kind(n,"ReturnValue","bool");bp.connect(left,leftpin,n,"A");bp.connect(right,rightpin,n,"B") if right is not None else s.set_default(n,"B",default);return n
 def math(member,left,leftpin,x,y,right=None,rightpin=None,default=None):n=b.math("Add_IntInt",x,y);s.retarget_function(n,member);[kind(n,pin,"int") for pin in ("A","B","ReturnValue")];bp.connect(left,leftpin,n,"A");bp.connect(right,rightpin,n,"B") if right is not None else s.set_default(n,"B",default);return n
 def select(condition,false_source,false_pin,true_default,x,y,false_default=None):n=addform(f"select_{len(b.nodes)}","select",x,y);kind(n,"Index","bool");[kind(n,pin,"real") for pin in ("Option 0","Option 1","ReturnValue")];bp.connect(condition,"ReturnValue",n,"Index");bp.connect(false_source,false_pin,n,"Option 0") if false_source is not None else s.set_default(n,"Option 0",false_default);s.set_default(n,"Option 1",true_default);return n
 invalidate=setv("CameraChannelScratchValidV1","bool",256,3040,"false");scalar_invalid=setv("CameraScalarTrackCompileValidV1","bool",480,3040,"false");bp.connect(b.entry,"then",invalidate,"execute");bp.connect(invalidate,"then",scalar_invalid,"execute");index=get("CameraChannelScratchChannelIndexV1","int",0,0);compiled_valid=get("CameraChannelCompileValidV1","bool",0,160);low=cmp("GreaterEqual_IntInt",index,"CameraChannelScratchChannelIndexV1",256,0,default="0");high=cmp("Less_IntInt",index,"CameraChannelScratchChannelIndexV1",256,160,default="13");range_ok=cmp("BooleanAND",low,"ReturnValue",480,80,high,"ReturnValue",k="bool");ready=cmp("BooleanAND",compiled_valid,"CameraChannelCompileValidV1",704,80,range_ok,"ReturnValue",k="bool")
 offsets=get("CameraChannelCompiledKeyOffsetsV1","int",0,480,True);counts=get("CameraChannelCompiledKeyCountsV1","int",0,640,True);domains=get("CameraChannelCompiledDomainsV1","string",0,800,True);offset_len=length(offsets,"CameraChannelCompiledKeyOffsetsV1","int",256,480);count_len=length(counts,"CameraChannelCompiledKeyCountsV1","int",256,640);domain_len=length(domains,"CameraChannelCompiledDomainsV1","string",256,800)
 for node in (offset_len,count_len,domain_len):
  exact=cmp("EqualEqual_IntInt",node,"ReturnValue",928,960,default="13");ready=cmp("BooleanAND",ready,"ReturnValue",1136,960,exact,"ReturnValue",k="bool")
 guard=b.add("guard","branch",1152,3040);bp.connect(scalar_invalid,"then",guard,"execute");bp.connect(ready,"ReturnValue",guard,"Condition");offset=item(offsets,"CameraChannelCompiledKeyOffsetsV1","int",index,"CameraChannelScratchChannelIndexV1",1376,1600);count=item(counts,"CameraChannelCompiledKeyCountsV1","int",index,"CameraChannelScratchChannelIndexV1",1376,1760);domain=item(domains,"CameraChannelCompiledDomainsV1","string",index,"CameraChannelScratchChannelIndexV1",1376,1920)
 sources={source:get(source,k,0,1120+i*144,True) for i,(source,_target,k) in enumerate(COPIES)};mode_source=get("CameraChannelCompiledInterpolationModesV1","string",0,1760,True);targets={target:get(target,k,0,2240+i*144,True) for i,(_source,target,k) in enumerate(COPIES)};mode_target=get("CameraScalarTrackCandidateInterpolationModesV1","string",0,2880,True)
 source_lengths=[length(sources[source],source,k,1600+i*208,1120) for i,(source,_target,k) in enumerate(COPIES)];mode_length=length(mode_source,"CameraChannelCompiledInterpolationModesV1","string",2432,1120);end=math("Add_IntInt",offset,"Output",1600,1440,count,"Output");mode_start_check=math("Subtract_IntInt",offset,"Output",1824,1440,index,"CameraChannelScratchChannelIndexV1");mode_count=math("Subtract_IntInt",count,"Output",2048,1440,default="1");mode_end=math("Add_IntInt",mode_start_check,"ReturnValue",2272,1440,mode_count,"ReturnValue")
 conditions=[cmp("GreaterEqual_IntInt",offset,"Output",1600,1280,default="0"),cmp("GreaterEqual_IntInt",count,"Output",1824,1280,default="1"),cmp("LessEqual_IntInt",count,"Output",2048,1280,default="512"),cmp("GreaterEqual_IntInt",mode_start_check,"ReturnValue",2272,1280,default="0")]
 conditions.extend(cmp("LessEqual_IntInt",end,"ReturnValue",2496+i*208,1280,node,"ReturnValue") for i,node in enumerate(source_lengths));conditions.append(cmp("LessEqual_IntInt",mode_end,"ReturnValue",3328,1280,mode_length,"ReturnValue"));linear=cmp("EqualEqual_StrStr",domain,"Output",3536,1280,default="linear",k="string");reciprocal=cmp("EqualEqual_StrStr",domain,"Output",3744,1280,default="reciprocal",k="string");focus=cmp("EqualEqual_IntInt",index,"CameraChannelScratchChannelIndexV1",3952,1280,default="2");not_focus=cmp("NotEqual_IntInt",index,"CameraChannelScratchChannelIndexV1",4160,1280,default="2");focus_domain=cmp("BooleanOR",linear,"ReturnValue",4368,1200,reciprocal,"ReturnValue",k="bool");focus_ok=cmp("BooleanAND",focus,"ReturnValue",4576,1200,focus_domain,"ReturnValue",k="bool");linear_ok=cmp("BooleanAND",not_focus,"ReturnValue",4368,1360,linear,"ReturnValue",k="bool");conditions.append(cmp("BooleanOR",focus_ok,"ReturnValue",4784,1280,linear_ok,"ReturnValue",k="bool"));slice_valid=conditions[0]
 for condition in conditions[1:]:slice_valid=cmp("BooleanAND",slice_valid,"ReturnValue",4992,1280,condition,"ReturnValue",k="bool")
 slice_branch=b.add("slice_branch","branch",1600,3040);bp.connect(guard,"then",slice_branch,"execute");bp.connect(slice_valid,"ReturnValue",slice_branch,"Condition");clears=[arrayop("clear",targets[target],target,k,1824+i*224,3040) for i,(_source,target,k) in enumerate(COPIES)];clears.insert(2,arrayop("clear",mode_target,"CameraScalarTrackCandidateInterpolationModesV1","string",1824+2*224,3040));bp.connect(slice_branch,"then",clears[0],"execute");[bp.connect(left,"then",right,"execute") for left,right in zip(clears,clears[1:])]
 equal=[cmp("EqualEqual_IntInt",index,"CameraChannelScratchChannelIndexV1",0,3360+i*112,default=str(i)) for i in (0,1,2,4)];minimum=None
 for condition,value in reversed(tuple(zip(equal,("1.0","0.1","1.0","-20.0")))):minimum=select(condition,minimum,"ReturnValue" if minimum else None,value,256+len(b.nodes)*0,3520,false_default="0.0" if minimum is None else None)
 maximum=None
 for condition,value in reversed(tuple(zip(equal,("1000.0","64.0","1000000000.0","20.0")))):maximum=select(condition,maximum,"ReturnValue" if maximum else None,value,736+len(b.nodes)*0,3680,false_default="1.0" if maximum is None else None)
 ge_effect=cmp("GreaterEqual_IntInt",index,"CameraChannelScratchChannelIndexV1",1216,3520,default="5");idx3=cmp("EqualEqual_IntInt",index,"CameraChannelScratchChannelIndexV1",1216,3680,default="3");clamp=cmp("BooleanOR",idx3,"ReturnValue",1440,3600,ge_effect,"ReturnValue",k="bool");duration=get("CameraChannelCompiledDurationV1","real",0,3040);policy=(("CameraScalarTrackInputDurationV1","real",duration,"CameraChannelCompiledDurationV1",None),("CameraScalarTrackInputDomainV1","string",domain,"Output",None),("CameraScalarTrackInputHasMinimumV1","bool",None,None,"true"),("CameraScalarTrackInputMinimumV1","real",minimum,"ReturnValue",None),("CameraScalarTrackInputHasMaximumV1","bool",None,None,"true"),("CameraScalarTrackInputMaximumV1","real",maximum,"ReturnValue",None),("CameraScalarTrackInputClampOutputV1","bool",clamp,"ReturnValue",None));sets=[]
 for i,(name,k,source,pin,default) in enumerate(policy):n=setv(name,k,2496+i*224,3040,default);bp.connect(source,pin,n,name) if source is not None else None;sets.append(n)
 bp.connect(clears[-1],"then",sets[0],"execute");[bp.connect(left,"then",right,"execute") for left,right in zip(sets,sets[1:])]
 last=math("Subtract_IntInt",count,"Output",4064,1760,default="1");loop=addform("copy_loop","loop",4288,3040);s.set_default(loop,"FirstIndex","0");bp.connect(last,"ReturnValue",loop,"LastIndex");bp.connect(sets[-1],"then",loop,"execute");flat=math("Add_IntInt",offset,"Output",4512,1760,loop,"Index");adds=[]
 for i,(source,target,k) in enumerate(COPIES):value=item(sources[source],source,k,flat,"ReturnValue",4736+i*224,1760);adds.append(arrayop("add",targets[target],target,k,4736+i*224,3040,value,"Output"))
 bp.connect(loop,"LoopBody",adds[0],"execute");[bp.connect(left,"then",right,"execute") for left,right in zip(adds,adds[1:])];one=math("Subtract_IntInt",count,"Output",5632,2080,default="1");not_last=cmp("Less_IntInt",loop,"Index",5856,2080,one,"ReturnValue");mode_branch=b.add("mode_branch","branch",6080,3040);bp.connect(adds[-1],"then",mode_branch,"execute");bp.connect(not_last,"ReturnValue",mode_branch,"Condition");mode_base=math("Subtract_IntInt",offset,"Output",6080,2240,index,"CameraChannelScratchChannelIndexV1");mode_index=math("Add_IntInt",mode_base,"ReturnValue",6304,2240,loop,"Index");mode=item(mode_source,"CameraChannelCompiledInterpolationModesV1","string",mode_index,"ReturnValue",6528,2240);mode_add=arrayop("add",mode_target,"CameraScalarTrackCandidateInterpolationModesV1","string",6752,3040,mode,"Output");bp.connect(mode_branch,"then",mode_add,"execute");scalar_valid=setv("CameraScalarTrackCompileValidV1","bool",6976,3040,"true");stage_valid=setv("CameraChannelScratchValidV1","bool",7200,3040,"true");bp.connect(loop,"Completed",scalar_valid,"execute");bp.connect(scalar_valid,"then",stage_valid,"execute")
 full="\n".join(n.text for n in b.nodes)+"\n";a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(full,encoding="utf-8")
 if a.paste_output:a.paste_output.parent.mkdir(parents=True,exist_ok=True);a.paste_output.write_text("\n".join(re.sub(r',LinkedTo=\(K2Node_FunctionEntry_0 [0-9A-F]{32},\)',"",n.text) for n in b.nodes[1:])+"\n",encoding="utf-8")
if __name__=="__main__":main()
