"""Build deterministic Blueprint graphs for bounded draft undo/redo history.

The first milestone stores full value snapshots.  This deliberately favors a
small, auditable transaction boundary over command-specific inverse logic.
Generated paste artifacts omit the native function entry; the live editor must
connect that one exposed execution input before the graph is accepted.
"""

from __future__ import annotations

import argparse
import importlib.util
import re
import sys
from pathlib import Path


CLIENT_ASSET = (
    "/Game/Mods/ExileDroneDirector/Core/Client/"
    "BPC_EDD_ClientDirector.BPC_EDD_ClientDirector"
)
DOCUMENT_STRUCT = (
    "/Script/CoreUObject.UserDefinedStruct'"
    "/Game/Mods/ExileDroneDirector/Data/Structs/"
    "ST_EDD_FlypathDocument.ST_EDD_FlypathDocument'"
)
WAYPOINT_STRUCT = (
    "/Script/CoreUObject.UserDefinedStruct'"
    "/Game/Mods/ExileDroneDirector/Data/Structs/"
    "ST_EDD_Waypoint.ST_EDD_Waypoint'"
)
SEGMENT_STRUCT = (
    "/Script/CoreUObject.UserDefinedStruct'"
    "/Game/Mods/ExileDroneDirector/Data/Structs/"
    "ST_EDD_Segment.ST_EDD_Segment'"
)
TRANSFORM_STRUCT = "/Script/CoreUObject.ScriptStruct'/Script/CoreUObject.Transform'"


def load_helpers(project_root: Path):
    path = project_root / "tools" / "blueprint" / "Build-WaypointCaptureGraph.py"
    spec = importlib.util.spec_from_file_location("edd_draft_history_base", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load graph helpers: {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def set_function_entry(node, name: str) -> None:
    node.text = re.sub(
        r'FunctionReference=\(MemberName="[^"]+"\)',
        f'FunctionReference=(MemberName="{name}")',
        node.text,
        count=1,
    )


def set_pin_int(node, pin_name: str, *, array: bool = False) -> None:
    def mutate(line: str) -> str:
        line = re.sub(r'PinType\.PinCategory="[^"]+"', 'PinType.PinCategory="int"', line, count=1)
        line = re.sub(r'PinType\.PinSubCategory="[^"]*"', 'PinType.PinSubCategory=""', line, count=1)
        line = re.sub(
            r'PinType\.PinSubCategoryObject=(?:None|"[^"]+")',
            'PinType.PinSubCategoryObject=None',
            line,
            count=1,
        )
        line = re.sub(
            r'PinType\.ContainerType=(?:None|Array)',
            f'PinType.ContainerType={"Array" if array else "None"}',
            line,
            count=1,
        )
        return line

    node.mutate_pin(pin_name, mutate)


def set_pin_document(node, pin_name: str, *, array: bool = False) -> None:
    set_pin_struct(node, pin_name, DOCUMENT_STRUCT, array=array)


def set_pin_struct(node, pin_name: str, struct_type: str, *, array: bool = False) -> None:
    def mutate(line: str) -> str:
        line = re.sub(r'PinType\.PinCategory="[^"]+"', 'PinType.PinCategory="struct"', line, count=1)
        line = re.sub(r'PinType\.PinSubCategory="[^"]*"', 'PinType.PinSubCategory=""', line, count=1)
        line = re.sub(
            r'PinType\.PinSubCategoryObject=(?:None|"[^"]+")',
            f'PinType.PinSubCategoryObject="{struct_type}"',
            line,
            count=1,
        )
        line = re.sub(
            r'PinType\.ContainerType=(?:None|Array)',
            f'PinType.ContainerType={"Array" if array else "None"}',
            line,
            count=1,
        )
        line = re.sub(r',DefaultValue="[^"]*"', '', line)
        line = re.sub(r',AutogeneratedDefaultValue="[^"]*"', '', line)
        return line

    node.mutate_pin(pin_name, mutate)


def set_pin_real(node, pin_name: str, *, array: bool = False) -> None:
    def mutate(line: str) -> str:
        line = re.sub(r'PinType\.PinCategory="[^"]+"', 'PinType.PinCategory="real"', line, count=1)
        line = re.sub(r'PinType\.PinSubCategory="[^"]*"', 'PinType.PinSubCategory="double"', line, count=1)
        line = re.sub(r'PinType\.PinSubCategoryObject=(?:None|"[^"]+")', 'PinType.PinSubCategoryObject=None', line, count=1)
        line = re.sub(r'PinType\.ContainerType=(?:None|Array)', f'PinType.ContainerType={"Array" if array else "None"}', line, count=1)
        return line
    node.mutate_pin(pin_name, mutate)


def set_pin_transform(node, pin_name: str, *, array: bool = False) -> None:
    set_pin_struct(node, pin_name, TRANSFORM_STRUCT, array=array)


def retarget_variable(node, old_name: str, new_name: str, kind: str, *, array: bool = False) -> None:
    node.text = re.sub(
        rf'VariableReference=\(MemberName="{re.escape(old_name)}"[^)]*\)',
        f'VariableReference=(MemberName="{new_name}",bSelfContext=True)',
        node.text,
        count=1,
    )
    node.text = node.text.replace(f'PinName="{old_name}"', f'PinName="{new_name}"')
    node.pins[new_name] = node.pins.pop(old_name)
    setter_output = "Output_Get" in node.pins
    if kind == "int":
        set_pin_int(node, new_name, array=array)
        if setter_output:
            set_pin_int(node, "Output_Get")
    elif kind == "document":
        set_pin_document(node, new_name, array=array)
        if setter_output:
            set_pin_document(node, "Output_Get")
    elif kind == "waypoint":
        set_pin_struct(node, new_name, WAYPOINT_STRUCT, array=array)
        if setter_output:
            set_pin_struct(node, "Output_Get", WAYPOINT_STRUCT)
    elif kind == "segment":
        set_pin_struct(node, new_name, SEGMENT_STRUCT, array=array)
        if setter_output:
            set_pin_struct(node, "Output_Get", SEGMENT_STRUCT)
    else:
        raise RuntimeError(f"Unsupported variable kind: {kind}")


def retarget_array_node(node, kind: str) -> None:
    value_pins = ("TargetArray", "NewItem")
    for pin in value_pins:
        if pin not in node.pins:
            continue
        if kind == "int":
            set_pin_int(node, pin, array=(pin == "TargetArray"))
        elif kind == "document":
            set_pin_document(node, pin, array=(pin == "TargetArray"))
        elif kind == "real":
            set_pin_real(node, pin, array=(pin == "TargetArray"))
        elif kind == "transform":
            set_pin_transform(node, pin, array=(pin == "TargetArray"))
        else:
            raise RuntimeError(f"Unsupported array kind: {kind}")


def retarget_array_get(node, kind: str) -> None:
    if kind == "int":
        set_pin_int(node, "Array", array=True)
        set_pin_int(node, "Output")
    elif kind == "document":
        set_pin_document(node, "Array", array=True)
        set_pin_document(node, "Output")
    else:
        raise RuntimeError(f"Unsupported array-get kind: {kind}")


def retarget_self_call(node, name: str) -> None:
    node.text = re.sub(
        r'FunctionReference=\([^)]*\)',
        f'FunctionReference=(MemberName="{name}",bSelfContext=True)',
        node.text,
        count=1,
    )


class Builder:
    def __init__(self, bp, templates: dict[str, str], graph_name: str):
        self.bp = bp
        self.templates = templates
        self.nodes = []
        bp.TARGET_ASSET = CLIENT_ASSET
        bp.TARGET_GRAPH = graph_name
        self.entry = self.add("entry", "K2Node_FunctionEntry_0", 0, 0)
        set_function_entry(self.entry, graph_name)

    def add(self, template: str, name: str, x: int, y: int):
        node = self.bp.Node.clone(name, self.templates[template], name, x, y)
        self.nodes.append(node)
        return node

    def getter(self, name: str, kind: str, x: int, y: int, *, array: bool = False):
        template = "int_array_get" if array else "int_get"
        node = self.add(template, f"K2Node_VariableGet_{len(self.nodes)}", x, y)
        old = "DraftWaypointIds" if array else "NextWaypointId"
        retarget_variable(node, old, name, kind, array=array)
        return node

    def setter(self, name: str, kind: str, x: int, y: int, *, array: bool = False):
        node = self.add("int_set", f"K2Node_VariableSet_{len(self.nodes)}", x, y)
        retarget_variable(node, "NextWaypointId", name, kind, array=array)
        return node

    def array_add(self, kind: str, x: int, y: int):
        node = self.add("array_add", f"K2Node_CallArrayFunction_{len(self.nodes)}", x, y)
        retarget_array_node(node, kind)
        return node

    def array_remove(self, kind: str, x: int, y: int):
        node = self.add("array_remove", f"K2Node_CallArrayFunction_{len(self.nodes)}", x, y)
        retarget_array_node(node, kind)
        return node

    def array_clear(self, kind: str, x: int, y: int):
        node = self.add("array_clear", f"K2Node_CallArrayFunction_{len(self.nodes)}", x, y)
        retarget_array_node(node, kind)
        return node

    def array_get(self, kind: str, x: int, y: int):
        node = self.add("array_get", f"K2Node_GetArrayItem_{len(self.nodes)}", x, y)
        retarget_array_get(node, kind)
        return node

    def call(self, name: str, x: int, y: int):
        node = self.add("self_call", f"K2Node_CallFunction_{len(self.nodes)}", x, y)
        retarget_self_call(node, name)
        return node


def build_templates(project_root: Path, bp) -> dict[str, str]:
    snippets = project_root / "tools" / "blueprint" / "snippets"
    templates = project_root / "tools" / "blueprint" / "templates"
    capture_forms = bp.read_blocks(templates / "waypoint-capture-node-forms.eddgraph")
    edit_forms = bp.read_blocks(templates / "waypoint-edit-node-forms.eddgraph")
    capture_live = bp.read_blocks(snippets / "capture-current-waypoint-preview.eddgraph")
    sync_live = bp.read_blocks(snippets / "sync-draft-waypoints-v1.eddgraph")
    enter = bp.read_blocks(snippets / "enter-drone-mode.eddgraph")
    event = bp.read_blocks(snippets / "client-director-event-graph.eddgraph")
    preview_markers = bp.read_blocks(snippets / "rebuild-path-preview-markers-v1.eddgraph")
    return {
        "entry": bp.find_block(capture_forms, r"^Begin Object Class=/Script/BlueprintGraph\.K2Node_FunctionEntry\b"),
        "int_get": bp.find_block(capture_forms, r'MemberName="NextWaypointId"'),
        "int_set": bp.find_block(capture_forms, r'K2Node_VariableSet.*MemberName="NextWaypointId"'),
        "int_array_get": bp.find_block(sync_live, r'K2Node_VariableGet.*MemberName="DraftWaypointIds"'),
        "array_add": bp.find_block(capture_forms, r'MemberName="Array_Add"'),
        "array_remove": bp.find_block(edit_forms, r'MemberName="Array_Remove"'),
        "array_clear": bp.find_block(sync_live, r'MemberName="Array_Clear"'),
        "array_length": bp.find_block(event, r'MemberName="Array_Length"'),
        "array_get": bp.find_block(sync_live, r"^Begin Object Class=/Script/BlueprintGraph\.K2Node_GetArrayItem\b"),
        "branch": bp.find_block(enter, r"^Begin Object Class=/Script/BlueprintGraph\.K2Node_IfThenElse\b"),
        "greater_int": bp.find_block(sync_live, r'MemberName="Greater_IntInt"'),
        "subtract_int": bp.find_block(snippets.joinpath("delete-selected-waypoint-preview.eddgraph").exists() and bp.read_blocks(snippets / "delete-selected-waypoint-preview.eddgraph") or [], r'MemberName="Subtract_IntInt"'),
        "self_call": bp.find_block(capture_live, r'MemberName="SyncDraftDocumentV1"'),
        "break_document": bp.find_block(preview_markers, r'StructType="[^"]*ST_EDD_FlypathDocument'),
        "foreach": bp.find_block(preview_markers, r"K2Node_MacroInstance.*StandardMacros:ForEachLoop"),
        "break_waypoint": bp.find_block(preview_markers, r'StructType="[^"]*ST_EDD_Waypoint'),
        "legacy_ids": bp.find_block(sync_live, r'K2Node_VariableGet.*MemberName="DraftWaypointIds"'),
        "legacy_transforms": bp.find_block(sync_live, r'K2Node_VariableGet.*MemberName="DraftWaypointTransforms"'),
        "legacy_focals": bp.find_block(sync_live, r'K2Node_VariableGet.*MemberName="DraftWaypointFocalLengths"'),
        "legacy_apertures": bp.find_block(sync_live, r'K2Node_VariableGet.*MemberName="DraftWaypointApertures"'),
        "legacy_focuses": bp.find_block(sync_live, r'K2Node_VariableGet.*MemberName="DraftWaypointFocusDistances"'),
        "legacy_holds": bp.find_block(sync_live, r'K2Node_VariableGet.*MemberName="DraftWaypointHoldSeconds"'),
    }


def set_default(node, pin: str, value: str) -> None:
    def mutate(line: str) -> str:
        if "DefaultValue=" in line:
            return re.sub(r'DefaultValue="[^"]*"', f'DefaultValue="{value}"', line, count=1)
        return line.replace(",PersistentGuid=", f',DefaultValue="{value}",PersistentGuid=', 1)
    node.mutate_pin(pin, mutate)


def build_push(bp, templates: dict[str, str], graph_name: str, prefix: str):
    b = Builder(bp, templates, graph_name)
    documents = b.getter(f"{prefix}DocumentsV1", "document", 0, 256, array=True)
    current_document = b.getter("DraftDocumentV1", "document", 0, 448)
    add_document = b.array_add("document", 288, 0)
    selections = b.getter(f"{prefix}SelectionsV1", "int", 288, 256, array=True)
    current_selection = b.getter("SelectedWaypointIndex", "int", 288, 448)
    add_selection = b.array_add("int", 576, 0)
    next_ids = b.getter(f"{prefix}NextWaypointIdsV1", "int", 576, 256, array=True)
    current_next_id = b.getter("NextWaypointId", "int", 576, 448)
    add_next = b.array_add("int", 864, 0)
    length = b.add("array_length", f"K2Node_CallArrayFunction_{len(b.nodes)}", 1120, 256)
    retarget_array_node(length, "document")
    limit = b.getter("HistoryLimitV1", "int", 1120, 448)
    greater = b.add("greater_int", f"K2Node_CallFunction_{len(b.nodes)}", 1376, 256)
    branch = b.add("branch", f"K2Node_IfThenElse_{len(b.nodes)}", 1632, 0)
    remove_document = b.array_remove("document", 1888, 0)
    remove_selection = b.array_remove("int", 2160, 0)
    remove_next = b.array_remove("int", 2432, 0)
    for node in (remove_document, remove_selection, remove_next):
        set_default(node, "IndexToRemove", "0")

    bp.connect(b.entry, "then", add_document, "execute")
    bp.connect(documents, f"{prefix}DocumentsV1", add_document, "TargetArray")
    bp.connect(current_document, "DraftDocumentV1", add_document, "NewItem")
    bp.connect(add_document, "then", add_selection, "execute")
    bp.connect(selections, f"{prefix}SelectionsV1", add_selection, "TargetArray")
    bp.connect(current_selection, "SelectedWaypointIndex", add_selection, "NewItem")
    bp.connect(add_selection, "then", add_next, "execute")
    bp.connect(next_ids, f"{prefix}NextWaypointIdsV1", add_next, "TargetArray")
    bp.connect(current_next_id, "NextWaypointId", add_next, "NewItem")
    bp.connect(add_next, "then", branch, "execute")
    bp.connect(documents, f"{prefix}DocumentsV1", length, "TargetArray")
    bp.connect(length, "ReturnValue", greater, "A")
    bp.connect(limit, "HistoryLimitV1", greater, "B")
    bp.connect(greater, "ReturnValue", branch, "Condition")
    bp.connect(branch, "then", remove_document, "execute")
    bp.connect(documents, f"{prefix}DocumentsV1", remove_document, "TargetArray")
    bp.connect(remove_document, "then", remove_selection, "execute")
    bp.connect(selections, f"{prefix}SelectionsV1", remove_selection, "TargetArray")
    bp.connect(remove_selection, "then", remove_next, "execute")
    bp.connect(next_ids, f"{prefix}NextWaypointIdsV1", remove_next, "TargetArray")
    return b.nodes


def build_record(bp, templates: dict[str, str]):
    b = Builder(bp, templates, "RecordUndoSnapshotV1")
    push = b.call("PushCurrentToUndoV1", 256, 0)
    redo_documents = b.getter("RedoDocumentsV1", "document", 256, 256, array=True)
    clear_documents = b.array_clear("document", 512, 0)
    redo_selections = b.getter("RedoSelectionsV1", "int", 512, 256, array=True)
    clear_selections = b.array_clear("int", 768, 0)
    redo_next_ids = b.getter("RedoNextWaypointIdsV1", "int", 768, 256, array=True)
    clear_next_ids = b.array_clear("int", 1024, 0)
    bp.connect(b.entry, "then", push, "execute")
    bp.connect(push, "then", clear_documents, "execute")
    bp.connect(redo_documents, "RedoDocumentsV1", clear_documents, "TargetArray")
    bp.connect(clear_documents, "then", clear_selections, "execute")
    bp.connect(redo_selections, "RedoSelectionsV1", clear_selections, "TargetArray")
    bp.connect(clear_selections, "then", clear_next_ids, "execute")
    bp.connect(redo_next_ids, "RedoNextWaypointIdsV1", clear_next_ids, "TargetArray")
    return b.nodes


def build_pop(bp, templates: dict[str, str], *, source: str, opposite: str, graph_name: str):
    """Pop one full snapshot, preserving the current state on the opposite stack."""
    b = Builder(bp, templates, graph_name)
    documents = b.getter(f"{source}DocumentsV1", "document", 0, 320, array=True)
    length = b.add("array_length", f"K2Node_CallArrayFunction_{len(b.nodes)}", 256, 320)
    retarget_array_node(length, "document")
    greater = b.add("greater_int", f"K2Node_CallFunction_{len(b.nodes)}", 512, 320)
    set_default(greater, "B", "0")
    branch = b.add("branch", f"K2Node_IfThenElse_{len(b.nodes)}", 768, 0)
    subtract = b.add("subtract_int", f"K2Node_PromotableOperator_{len(b.nodes)}", 768, 320)
    set_default(subtract, "B", "1")

    document_get = b.array_get("document", 1024, 320)
    stage_document = b.setter("HistoryRestoreDocumentV1", "document", 1024, 0)
    selections = b.getter(f"{source}SelectionsV1", "int", 1024, 544, array=True)
    selection_get = b.array_get("int", 1280, 544)
    stage_selection = b.setter("HistoryRestoreSelectionV1", "int", 1280, 0)
    next_ids = b.getter(f"{source}NextWaypointIdsV1", "int", 1280, 768, array=True)
    next_get = b.array_get("int", 1536, 768)
    stage_next = b.setter("HistoryRestoreNextWaypointIdV1", "int", 1536, 0)
    push_opposite = b.call(f"PushCurrentTo{opposite}V1", 1792, 0)

    remove_document = b.array_remove("document", 2048, 0)
    remove_selection = b.array_remove("int", 2304, 0)
    remove_next = b.array_remove("int", 2560, 0)
    apply_snapshot = b.call("ApplyHistorySnapshotV1", 2816, 0)

    bp.connect(b.entry, "then", branch, "execute")
    bp.connect(documents, f"{source}DocumentsV1", length, "TargetArray")
    bp.connect(length, "ReturnValue", greater, "A")
    bp.connect(greater, "ReturnValue", branch, "Condition")
    bp.connect(length, "ReturnValue", subtract, "A")
    bp.connect(branch, "then", stage_document, "execute")
    bp.connect(documents, f"{source}DocumentsV1", document_get, "Array")
    bp.connect(subtract, "ReturnValue", document_get, "Dimension 1")
    bp.connect(document_get, "Output", stage_document, "HistoryRestoreDocumentV1")
    bp.connect(stage_document, "then", stage_selection, "execute")
    bp.connect(selections, f"{source}SelectionsV1", selection_get, "Array")
    bp.connect(subtract, "ReturnValue", selection_get, "Dimension 1")
    bp.connect(selection_get, "Output", stage_selection, "HistoryRestoreSelectionV1")
    bp.connect(stage_selection, "then", stage_next, "execute")
    bp.connect(next_ids, f"{source}NextWaypointIdsV1", next_get, "Array")
    bp.connect(subtract, "ReturnValue", next_get, "Dimension 1")
    bp.connect(next_get, "Output", stage_next, "HistoryRestoreNextWaypointIdV1")
    bp.connect(stage_next, "then", push_opposite, "execute")
    bp.connect(push_opposite, "then", remove_document, "execute")
    bp.connect(documents, f"{source}DocumentsV1", remove_document, "TargetArray")
    bp.connect(subtract, "ReturnValue", remove_document, "IndexToRemove")
    bp.connect(remove_document, "then", remove_selection, "execute")
    bp.connect(selections, f"{source}SelectionsV1", remove_selection, "TargetArray")
    bp.connect(subtract, "ReturnValue", remove_selection, "IndexToRemove")
    bp.connect(remove_selection, "then", remove_next, "execute")
    bp.connect(next_ids, f"{source}NextWaypointIdsV1", remove_next, "TargetArray")
    bp.connect(subtract, "ReturnValue", remove_next, "IndexToRemove")
    bp.connect(remove_next, "then", apply_snapshot, "execute")
    return b.nodes


def pin_starting(node, prefix: str) -> str:
    matches = [name for name in node.pins if name.startswith(prefix)]
    if len(matches) != 1:
        raise RuntimeError(f"Expected one {node.key} pin starting {prefix!r}; found {matches}")
    return matches[0]


def build_apply(bp, templates: dict[str, str]):
    b = Builder(bp, templates, "ApplyHistorySnapshotV1")
    document = b.getter("HistoryRestoreDocumentV1", "document", 0, 448)
    break_document = b.add("break_document", f"K2Node_BreakStruct_{len(b.nodes)}", 256, 448)
    loop = b.add("foreach", f"K2Node_MacroInstance_{len(b.nodes)}", 1792, 0)
    break_waypoint = b.add("break_waypoint", f"K2Node_BreakStruct_{len(b.nodes)}", 1792, 448)

    legacy_specs = (
        ("legacy_ids", "DraftWaypointIds", "int", "WaypointId_"),
        ("legacy_transforms", "DraftWaypointTransforms", "transform", "CameraTransform_"),
        ("legacy_focals", "DraftWaypointFocalLengths", "real", "FocalLength_"),
        ("legacy_apertures", "DraftWaypointApertures", "real", "Aperture_"),
        ("legacy_focuses", "DraftWaypointFocusDistances", "real", "ManualFocusDistance_"),
        ("legacy_holds", "DraftWaypointHoldSeconds", "real", "HoldSeconds_"),
    )
    getters = []
    clears = []
    adds = []
    for index, (template, member, kind, field_prefix) in enumerate(legacy_specs):
        getter = b.add(template, f"K2Node_VariableGet_{len(b.nodes)}", index * 256, 256)
        clear = b.array_clear(kind, index * 256, 0)
        add = b.array_add(kind, 2048 + index * 256, 0)
        getters.append((getter, member, kind, field_prefix))
        clears.append(clear)
        adds.append(add)

    typed_waypoints = b.setter("DraftWaypointsV1", "waypoint", 3584, 0, array=True)
    typed_segments = b.setter("DraftSegmentsV1", "segment", 3840, 0, array=True)
    typed_document = b.setter("DraftDocumentV1", "document", 4096, 0)
    selected = b.getter("HistoryRestoreSelectionV1", "int", 4096, 320)
    set_selected = b.setter("SelectedWaypointIndex", "int", 4352, 0)
    next_id = b.getter("HistoryRestoreNextWaypointIdV1", "int", 4352, 320)
    set_next = b.setter("NextWaypointId", "int", 4608, 0)
    refresh = b.call("RefreshPathPreviewV1", 4864, 0)

    bp.connect(document, "HistoryRestoreDocumentV1", break_document, "ST_EDD_FlypathDocument")
    waypoints_pin = pin_starting(break_document, "Waypoints_")
    segments_pin = pin_starting(break_document, "Segments_")
    bp.connect(break_document, waypoints_pin, loop, "Array")
    bp.connect(loop, "Array Element", break_waypoint, "ST_EDD_Waypoint")

    bp.connect(b.entry, "then", clears[0], "execute")
    for index, ((getter, member, _kind, field_prefix), clear, add) in enumerate(zip(getters, clears, adds)):
        bp.connect(getter, member, clear, "TargetArray")
        bp.connect(getter, member, add, "TargetArray")
        if index + 1 < len(clears):
            bp.connect(clear, "then", clears[index + 1], "execute")
        else:
            bp.connect(clear, "then", loop, "Exec")
        bp.connect(break_waypoint, pin_starting(break_waypoint, field_prefix), add, "NewItem")
        if index == 0:
            bp.connect(loop, "LoopBody", add, "execute")
        else:
            bp.connect(adds[index - 1], "then", add, "execute")

    bp.connect(loop, "Completed", typed_waypoints, "execute")
    bp.connect(break_document, waypoints_pin, typed_waypoints, "DraftWaypointsV1")
    bp.connect(typed_waypoints, "then", typed_segments, "execute")
    bp.connect(break_document, segments_pin, typed_segments, "DraftSegmentsV1")
    bp.connect(typed_segments, "then", typed_document, "execute")
    bp.connect(document, "HistoryRestoreDocumentV1", typed_document, "DraftDocumentV1")
    bp.connect(typed_document, "then", set_selected, "execute")
    bp.connect(selected, "HistoryRestoreSelectionV1", set_selected, "SelectedWaypointIndex")
    bp.connect(set_selected, "then", set_next, "execute")
    bp.connect(next_id, "HistoryRestoreNextWaypointIdV1", set_next, "NextWaypointId")
    bp.connect(set_next, "then", refresh, "execute")
    return b.nodes


def write_graph(nodes, output: Path, *, paste: bool) -> None:
    blocks = []
    for node in nodes:
        if paste and node is nodes[0]:
            continue
        text = node.text
        if paste:
            text = re.sub(r',LinkedTo=\(K2Node_FunctionEntry_0 [0-9A-F]{32},\)', '', text)
        blocks.append(text)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(blocks) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-root", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--paste-dir", type=Path)
    args = parser.parse_args()
    bp = load_helpers(args.project_root)
    templates = build_templates(args.project_root, bp)
    graphs = {
        "push-current-to-undo-v1": build_push(bp, templates, "PushCurrentToUndoV1", "Undo"),
        "push-current-to-redo-v1": build_push(bp, templates, "PushCurrentToRedoV1", "Redo"),
        "record-undo-snapshot-v1": build_record(bp, templates),
        "undo-draft-v1": build_pop(
            bp, templates, source="Undo", opposite="Redo", graph_name="UndoDraftV1"
        ),
        "redo-draft-v1": build_pop(
            bp, templates, source="Redo", opposite="Undo", graph_name="RedoDraftV1"
        ),
        "apply-history-snapshot-v1": build_apply(bp, templates),
    }
    for stem, nodes in graphs.items():
        write_graph(nodes, args.output_dir / f"{stem}.eddgraph", paste=False)
        if args.paste_dir:
            write_graph(nodes, args.paste_dir / f"{stem}-paste.eddgraph", paste=True)


if __name__ == "__main__":
    main()
