"""Exact executable contracts for authored position-route validation."""
from __future__ import annotations
import argparse,importlib.util,re,sys
from pathlib import Path

def load(root):
 p=root/"tools/blueprint/Test-WaypointCaptureContracts.py";s=importlib.util.spec_from_file_location("edd_position_validation_contract_base",p);m=importlib.util.module_from_spec(s);sys.modules[s.name]=m;s.loader.exec_module(m);return m
def default(node,pin,value):
 match=re.search(r'(?:^|,)DefaultValue="([^"]*)"',node.pins[pin].body);return match is not None and match.group(1)==value
def one(c,nodes,member):return c.one(nodes,f'MemberName="{member}"')
def main():
 p=argparse.ArgumentParser();p.add_argument("--project-root",type=Path,required=True);p.add_argument("--graph",type=Path,required=True);p.add_argument("--paste",action="store_true");a=p.parse_args();c=load(a.project_root);nodes=c.parse_graph(a.graph);c.require(len(nodes)==(71 if a.paste else 72),f"node count {len(nodes)}")
 entries=[n for n in nodes.values() if "K2Node_FunctionEntry" in n.node_class];c.require(len(entries)==(0 if a.paste else 1),"entry count")
 arrays=(("PositionRouteInputWaypointPositionsV1","vector"),("PositionRouteInputDurationsV1","real"),("PositionRouteInputSpatialCurveTypesV1","string"),("PositionRouteInputTimeProfilesV1","string"));sources={name:one(c,nodes,name) for name,_ in arrays};lengths=[n for n in nodes.values() if 'MemberName="Array_Length"' in n.text];c.require(len(lengths)==4,"four exact lengths")
 lens={name:next(n for n in lengths if c.linked(sources[name],name,n,"TargetArray")) for name,_ in arrays};integer_mins=[n for n in nodes.values() if 'MemberName="GreaterEqual_IntInt"' in n.text];integer_maxes=[n for n in nodes.values() if 'MemberName="LessEqual_IntInt"' in n.text];minimum=next(n for n in integer_mins if default(n,"B","2"));maximum=next(n for n in integer_maxes if default(n,"B","512"));subtract=one(c,nodes,"Subtract_IntInt");c.require(default(subtract,"B","1"),"route cardinality subtract changed");c.require_link(lens[arrays[0][0]],"ReturnValue",minimum,"A","minimum source");c.require_link(lens[arrays[0][0]],"ReturnValue",maximum,"A","maximum source");c.require_link(lens[arrays[0][0]],"ReturnValue",subtract,"A","segment count source")
 shapes=[n for n in nodes.values() if 'MemberName="EqualEqual_IntInt"' in n.text];c.require(len(shapes)==3,"three exact shape comparisons")
 for name,_ in arrays[1:]:c.require(any(c.linked(lens[name],"ReturnValue",n,"A") and c.linked(subtract,"ReturnValue",n,"B") for n in shapes),f"shape missing:{name}")
 tolerance=one(c,nodes,"PositionRouteInputArcToleranceV1");finite=[n for n in nodes.values() if 'MemberName="GreaterEqual_DoubleDouble"' in n.text or 'MemberName="LessEqual_DoubleDouble"' in n.text];c.require(len(finite)==4,"two tolerance and two duration finite bounds");c.require(sum(c.linked(tolerance,"PositionRouteInputArcToleranceV1",n,"A") for n in finite)==2,"tolerance finite bounds")
 real_positive=[n for n in nodes.values() if 'MemberName="Greater_DoubleDouble"' in n.text];c.require(len(real_positive)==2 and all(default(n,"B","0.0") for n in real_positive),"positive predicates changed")
 depth=one(c,nodes,"PositionRouteInputMaxArcDepthV1");ops=one(c,nodes,"PositionRouteInputMaxArcOperationsV1");c.require(any(default(n,"B","1") and c.linked(depth,"PositionRouteInputMaxArcDepthV1",n,"A") for n in integer_mins),"depth min");c.require(any(default(n,"B","12") and c.linked(depth,"PositionRouteInputMaxArcDepthV1",n,"A") for n in integer_maxes),"depth max");c.require(any(default(n,"B","1") and c.linked(ops,"PositionRouteInputMaxArcOperationsV1",n,"A") for n in integer_mins),"operations min");c.require(any(default(n,"B","8191") and c.linked(ops,"PositionRouteInputMaxArcOperationsV1",n,"A") for n in integer_maxes),"operations max")
 loops=[n for n in nodes.values() if "K2Node_MacroInstance" in n.node_class];c.require(len(loops)==4,"four foreach loops");loop_by={name:next(n for n in loops if c.linked(sources[name],name,n,"Array")) for name,_ in arrays};vector_call=one(c,nodes,"EvaluateQuinticVectorV1");time_call=one(c,nodes,"EvaluateTimeProfileV1");vector_valid=one(c,nodes,"TrajectoryResultVectorValidV1");time_valid=one(c,nodes,"TrajectoryResultValidV1");c.require(any(c.linked(vector_call,"then",n,"execute") and c.linked(vector_valid,"TrajectoryResultVectorValidV1",n,"Condition") for n in nodes.values() if "K2Node_IfThenElse" in n.node_class),"vector primitive gate");c.require(any(c.linked(time_call,"then",n,"execute") and c.linked(time_valid,"TrajectoryResultValidV1",n,"Condition") for n in nodes.values() if "K2Node_IfThenElse" in n.node_class),"time primitive gate")
 equals=[n for n in nodes.values() if 'MemberName="EqualEqual_StrStr"' in n.text];c.require(len(equals)==2,"spatial mode equality count");c.require({re.search(r'(?:^|,)DefaultValue="([^"]*)"',n.pins["B"].body).group(1) for n in equals}=={"linear","auto_cinematic"},"spatial modes changed");c.require(all(c.linked(loop_by["PositionRouteInputSpatialCurveTypesV1"],"Array Element",n,"A") for n in equals),"spatial mode source")
 stage=[n for n in nodes.values() if 'MemberName="PositionRouteStageValidV1"' in n.text];c.require(len(stage)==6,"reset accept and four rejects");values=["true" if default(n,"PositionRouteStageValidV1","true") else "false" for n in stage];c.require(values.count("true")==1 and values.count("false")==5,"stage writes changed")
 reset=next(n for n in stage if (not n.pins["execute"].links if a.paste else c.linked(entries[0],"then",n,"execute")));c.require(reset is not None,"reset root")
 known=set(nodes);external={target for n in nodes.values() for pin in n.pins.values() for target,_ in pin.links if target not in known};c.require(not external,f"external links {external}");print(f"Position route validation contracts passed ({'paste' if a.paste else 'full'}): {len(nodes)} nodes")
if __name__=="__main__":main()
