"""Exact ownership contracts for camera channel result reset."""
from __future__ import annotations
import argparse,importlib.util,re,sys
from pathlib import Path
ARRAYS=("CameraChannelResultValuesV1","CameraChannelResultVelocitiesV1","CameraChannelResultAccelerationsV1");SCALARS=("CameraChannelResultFilmbackPresetIdV1","CameraChannelResultFilmbackSensorWidthMmV1","CameraChannelResultFilmbackSensorHeightMmV1","CameraChannelResultCompleteV1","CameraChannelResultValidV1","CameraChannelScratchChannelIndexV1","CameraChannelScratchKeyIndexV1","CameraChannelScratchValidV1");PRESERVED=("CameraChannelCompiledKeyTimesV1","CameraChannelCompiledDomainValuesV1","CameraChannelCompiledDomainsV1","CameraChannelCompiledDurationV1","CameraChannelCompiledFilmbackPresetIdV1","CameraChannelCompileValidV1","CameraChannelFailureCodeV1","CameraChannelQueryTimeV1","CameraChannelInputKeyTimesV1")
def load(path):s=importlib.util.spec_from_file_location("edd_camera_channel_result_reset_contract_base",path);m=importlib.util.module_from_spec(s);sys.modules[s.name]=m;s.loader.exec_module(m);return m
def member(node):m=re.search(r'MemberName="([^"]+)"',node.text);return None if m is None else m.group(1)
def main():
 a=argparse.ArgumentParser();a.add_argument("--project-root",type=Path,required=True);a.add_argument("--graph",type=Path,required=True);a.add_argument("--paste",action="store_true");x=a.parse_args();c=load(x.project_root/"tools/blueprint/Test-WaypointCaptureContracts.py");nodes=c.parse_graph(x.graph);c.require(len(nodes)==(14 if x.paste else 15),f"node count {len(nodes)}");entries=[n for n in nodes.values() if "K2Node_FunctionEntry" in n.node_class];c.require(len(entries)==(0 if x.paste else 1),"entry count");getters={member(n) for n in nodes.values() if "K2Node_VariableGet" in n.node_class};setters={member(n) for n in nodes.values() if "K2Node_VariableSet" in n.node_class};c.require(getters==set(ARRAYS),"exact result arrays cleared");c.require(setters==set(SCALARS),"exact result/scratch scalars reset");text=x.graph.read_text(encoding="utf-8");c.require(not any(name in text for name in PRESERVED),"compiled/input/query/diagnostic preservation")
 state={name:["poison"] for name in ARRAYS};state.update({name:"poison" for name in SCALARS});state.update({name:[name] for name in PRESERVED});before={name:state[name] for name in PRESERVED}
 for name in ARRAYS:state[name]=[]
 state.update(CameraChannelResultFilmbackPresetIdV1="",CameraChannelResultFilmbackSensorWidthMmV1=0.0,CameraChannelResultFilmbackSensorHeightMmV1=0.0,CameraChannelResultCompleteV1=False,CameraChannelResultValidV1=False,CameraChannelScratchChannelIndexV1=0,CameraChannelScratchKeyIndexV1=0,CameraChannelScratchValidV1=False);c.require(all(state[name]==[] for name in ARRAYS) and not state["CameraChannelResultValidV1"],"reset execution");c.require(all(state[name]==before[name] for name in PRESERVED),"compiled snapshot preserved");print(f"Camera channel result-reset contracts passed ({'paste' if x.paste else 'full'}): compiled bank preserved")
if __name__=="__main__":main()

