"""Exact graph and execution contracts for common camera scalar reset."""
from __future__ import annotations
import argparse,importlib.util,re,sys
from pathlib import Path
ARRAYS=("CameraScalarTrackCandidateKeyTimesV1","CameraScalarTrackCandidateDomainValuesV1","CameraScalarTrackCandidateInterpolationModesV1","CameraScalarTrackCandidateArriveTangentsV1","CameraScalarTrackCandidateLeaveTangentsV1")
SCALARS=("CameraScalarTrackCompileValidV1","CameraScalarTrackFailureCodeV1","CameraScalarTrackResultValueV1","CameraScalarTrackResultVelocityV1","CameraScalarTrackResultAccelerationV1","CameraScalarTrackResultSegmentIndexV1","CameraScalarTrackResultLocalAlphaV1","CameraScalarTrackResultCompleteV1","CameraScalarTrackResultValidV1","CameraScalarTrackScratchIndexV1","CameraScalarTrackScratchValidV1","CameraScalarTrackScratchDomainValueV1","CameraScalarTrackScratchDomainVelocityV1","CameraScalarTrackScratchDomainAccelerationV1")
PRESERVED=("CameraScalarTrackInputKeyTimesV1","CameraScalarTrackInputKeyValuesV1","CameraScalarTrackInputInterpolationModesV1","CameraScalarTrackInputArriveTangentsV1","CameraScalarTrackInputLeaveTangentsV1","CameraScalarTrackQueryTimeV1")
def load(path):s=importlib.util.spec_from_file_location("edd_camera_scalar_reset_contract_base",path);m=importlib.util.module_from_spec(s);sys.modules[s.name]=m;s.loader.exec_module(m);return m
def member(node):m=re.search(r'MemberName="([^"]+)"',node.text);return None if m is None else m.group(1)
def main():
 a=argparse.ArgumentParser();a.add_argument("--project-root",type=Path,required=True);a.add_argument("--graph",type=Path,required=True);a.add_argument("--paste",action="store_true");x=a.parse_args();c=load(x.project_root/"tools/blueprint/Test-WaypointCaptureContracts.py");nodes=c.parse_graph(x.graph);c.require(len(nodes)==(24 if x.paste else 25),f"node count {len(nodes)}")
 entries=[n for n in nodes.values() if "K2Node_FunctionEntry" in n.node_class];c.require(len(entries)==(0 if x.paste else 1),"entry count");clears=[n for n in nodes.values() if member(n)=="Array_Clear"];c.require(len(clears)==5,"five candidate clears");root=nodes["K2Node_CallArrayFunction_0"];c.require(not root.pins["execute"].links,"paste execution root") if x.paste else c.require_link(entries[0],"then",root,"execute","native entry to first clear")
 getters=[n for n in nodes.values() if "K2Node_VariableGet" in n.node_class];c.require({member(n) for n in getters}==set(ARRAYS),"candidate ownership");setters=[n for n in nodes.values() if "K2Node_VariableSet" in n.node_class];c.require({member(n) for n in setters}==set(SCALARS),"scalar reset ownership");text=x.graph.read_text(encoding="utf-8");c.require(not any(name in text for name in PRESERVED),"authored/query input mutation")
 state={name:["poison"] for name in ARRAYS};state.update({name:"poison" for name in SCALARS});state.update({name:[name] for name in PRESERVED});before={name:state[name] for name in PRESERVED}
 for name in ARRAYS:state[name]=[]
 state.update(CameraScalarTrackCompileValidV1=False,CameraScalarTrackFailureCodeV1="",CameraScalarTrackResultValueV1=0.0,CameraScalarTrackResultVelocityV1=0.0,CameraScalarTrackResultAccelerationV1=0.0,CameraScalarTrackResultSegmentIndexV1=-1,CameraScalarTrackResultLocalAlphaV1=0.0,CameraScalarTrackResultCompleteV1=False,CameraScalarTrackResultValidV1=False,CameraScalarTrackScratchIndexV1=0,CameraScalarTrackScratchValidV1=False,CameraScalarTrackScratchDomainValueV1=0.0,CameraScalarTrackScratchDomainVelocityV1=0.0,CameraScalarTrackScratchDomainAccelerationV1=0.0)
 c.require(all(state[name]==[] for name in ARRAYS) and not state["CameraScalarTrackCompileValidV1"] and not state["CameraScalarTrackResultValidV1"],"reset execution");c.require(all(state[name]==before[name] for name in PRESERVED),"preserved inputs");print(f"Camera scalar-track reset contracts passed ({'paste' if x.paste else 'full'}): {len(nodes)} nodes")
if __name__=="__main__":main()
