"""Pin-level contracts for absolute-time linear playback Blueprint graphs."""

from __future__ import annotations

import argparse
import importlib.util
import re
import sys
from pathlib import Path


def helpers_module():
    path = Path(__file__).with_name("Test-WaypointCaptureContracts.py")
    spec = importlib.util.spec_from_file_location("edd_linear_contract_helpers", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load graph helpers: {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def explicit_default(node, pin_name: str) -> str:
    match = re.search(r'(?<!Autogenerated)DefaultValue="([^"]*)"', node.pins[pin_name].body)
    return match.group(1) if match else ""


def assert_start(path: Path, h) -> None:
    nodes = h.parse_graph(path)
    h.require(len(nodes) == 17, f"Start graph expected 17 nodes; found {len(nodes)}")
    entry = h.one(nodes, 'MemberName="StartLinearPlayback"')
    transforms = h.one(nodes, 'MemberName="DraftWaypointTransforms"')
    length = h.one(nodes, 'MemberName="Array_Length"')
    count_ge = h.one(nodes, 'MemberName="GreaterEqual_IntInt"')
    duration = h.one(nodes, 'MemberName="PlaybackSecondsPerSegment"')
    duration_ge = h.one(nodes, 'MemberName="GreaterEqual_DoubleDouble"')
    time = h.one(nodes, 'MemberName="GetGameTimeInSeconds"')
    start_set = h.one(nodes, 'VariableReference=(MemberName="PlaybackStartTimeSeconds"')
    active_set = h.one(nodes, 'VariableReference=(MemberName="PlaybackActive"')
    array_get = next(n for n in nodes.values() if n.node_class.endswith("K2Node_GetArrayItem"))
    set_transform = h.one(nodes, 'MemberName="K2_SetActorTransform"')
    h.require(explicit_default(count_ge, "B") == "2", "Start requires at least two waypoints")
    h.require(explicit_default(duration_ge, "B") == "0.001", "Start rejects zero duration")
    h.require(explicit_default(array_get, "Dimension 1") == "0", "Start must snap to waypoint zero")
    h.require(explicit_default(active_set, "PlaybackActive") == "true", "Start must activate playback")
    h.require_link(transforms, "DraftWaypointTransforms", length, "TargetArray", "Start count source changed")
    h.require_link(length, "ReturnValue", count_ge, "A", "Start must validate transform count")
    h.require_link(duration, "PlaybackSecondsPerSegment", duration_ge, "A", "Start must validate duration")
    h.require_link(time, "ReturnValue", start_set, "PlaybackStartTimeSeconds", "Start must snapshot absolute game time")
    h.require_link(transforms, "DraftWaypointTransforms", array_get, "Array", "Start must read the captured transforms")
    h.require_link(array_get, "Output", set_transform, "NewTransform", "Start must snap to the first transform")
    h.require('DefaultValue="[EDD] Linear playback started"' in "".join(n.text for n in nodes.values()), "Start diagnostic missing")
    h.require('ErrorType=' not in "".join(n.text for n in nodes.values()), "Start graph retains compiler errors")
    h.require(h.pin(entry, "then").links, "Start native entry must be reciprocal in the complete graph")


def assert_update(path: Path, h) -> None:
    nodes = h.parse_graph(path)
    h.require(len(nodes) == 34, f"Update graph expected 34 nodes; found {len(nodes)}")
    entry = h.one(nodes, 'MemberName="UpdateLinearPlayback"')
    active = next(
        n for n in nodes.values()
        if n.node_class.endswith("K2Node_VariableGet") and 'MemberName="PlaybackActive"' in n.text
    )
    transforms = h.one(nodes, 'MemberName="DraftWaypointTransforms"')
    length = h.one(nodes, 'MemberName="Array_Length"')
    duration = h.one(nodes, 'MemberName="PlaybackSecondsPerSegment"')
    now = h.one(nodes, 'MemberName="GetGameTimeInSeconds"')
    start = next(
        n for n in nodes.values()
        if n.node_class.endswith("K2Node_VariableGet") and 'MemberName="PlaybackStartTimeSeconds"' in n.text
    )
    subtracts = [n for n in nodes.values() if 'MemberName="Subtract_DoubleDouble"' in n.text]
    h.require(len(subtracts) == 2, "Update needs elapsed and local-alpha subtraction")
    elapsed = next(n for n in subtracts if h.linked(now, "ReturnValue", n, "A"))
    alpha = next(n for n in subtracts if n.name != elapsed.name)
    segment_count = h.one(nodes, 'MemberName="Subtract_IntInt"')
    count_double = [n for n in nodes.values() if 'MemberName="Conv_IntToDouble"' in n.text]
    h.require(len(count_double) == 2, "Update needs count and index conversion")
    total = h.one(nodes, 'MemberName="Multiply_DoubleDouble"')
    complete_ge = next(
        n for n in nodes.values()
        if 'MemberName="GreaterEqual_DoubleDouble"' in n.text and h.linked(elapsed, "ReturnValue", n, "A")
    )
    segment_time = h.one(nodes, 'MemberName="Divide_DoubleDouble"')
    floor_node = h.one(nodes, 'MemberName="FFloor"')
    add_index = h.one(nodes, 'MemberName="Add_IntInt"')
    array_gets = [n for n in nodes.values() if n.node_class.endswith("K2Node_GetArrayItem")]
    h.require(len(array_gets) == 3, "Update needs last, current, and next transform reads")
    tlerp = h.one(nodes, 'MemberName="TLerp"')
    set_transforms = [n for n in nodes.values() if 'MemberName="K2_SetActorTransform"' in n.text]
    h.require(len(set_transforms) == 2, "Update needs in-progress and exact-final transform writes")
    active_sets = [
        n for n in nodes.values()
        if n.node_class.endswith("K2Node_VariableSet") and 'MemberName="PlaybackActive"' in n.text
    ]
    selected_sets = [n for n in nodes.values() if 'K2Node_VariableSet' in n.text and 'MemberName="SelectedWaypointIndex"' in n.text]
    h.require(len(selected_sets) == 2, "Update must expose current segment and final waypoint selection")

    h.require_link(now, "ReturnValue", elapsed, "A", "Elapsed time must use current absolute game time")
    h.require_link(start, "PlaybackStartTimeSeconds", elapsed, "B", "Elapsed time must subtract the captured start")
    h.require_link(length, "ReturnValue", segment_count, "A", "Segment count must be waypoint count minus one")
    h.require(explicit_default(segment_count, "B") == "1", "Segment count subtraction changed")
    h.require(any(h.linked(n, "ReturnValue", total, "A") for n in count_double), "Total duration must use converted segment count")
    h.require_link(duration, "PlaybackSecondsPerSegment", total, "B", "Total duration must use fixed per-segment duration")
    h.require_link(elapsed, "ReturnValue", complete_ge, "A", "Completion must compare absolute elapsed time")
    h.require_link(total, "ReturnValue", complete_ge, "B", "Completion must compare against total duration")
    h.require_link(elapsed, "ReturnValue", segment_time, "A", "Segment time must derive from absolute elapsed time")
    h.require_link(duration, "PlaybackSecondsPerSegment", segment_time, "B", "Segment time must divide by configured duration")
    h.require_link(segment_time, "ReturnValue", floor_node, "A", "Segment index must floor segment time")
    h.require_link(segment_time, "ReturnValue", alpha, "A", "Local alpha must derive from segment time")
    h.require_link(floor_node, "ReturnValue", add_index, "A", "Next waypoint must be current index plus one")
    h.require(explicit_default(add_index, "B") == "1", "Next-index addition changed")
    h.require_link(transforms, "DraftWaypointTransforms", array_gets[0], "Array", "All evaluation reads must use captured transforms")
    for array_get in array_gets[1:]:
        h.require_link(transforms, "DraftWaypointTransforms", array_get, "Array", "All evaluation reads must use captured transforms")
    h.require_link(alpha, "ReturnValue", tlerp, "Alpha", "Transform lerp must use the local segment alpha")
    h.require(explicit_default(tlerp, "InterpMode") == "QuatInterp", "Rotation must use quaternion interpolation")
    h.require(not active_sets, "Completion must hold the final frame until explicit stop")
    combined = "".join(n.text for n in nodes.values())
    h.require("GetWorldDeltaSeconds" not in combined and "FInterpTo" not in combined, "Update must not integrate from frame delta")
    h.require('DefaultValue="[EDD] Linear playback complete"' not in combined, "Final-frame hold must not print every tick")
    h.require('ErrorType=' not in combined, "Update graph retains compiler errors")
    h.require(h.pin(entry, "then").links, "Update native entry must be reciprocal in the complete graph")


def assert_stop(path: Path, h) -> None:
    nodes = h.parse_graph(path)
    h.require(len(nodes) == 3, f"Stop graph expected 3 nodes; found {len(nodes)}")
    entry = h.one(nodes, 'MemberName="StopLinearPlayback"')
    active_set = h.one(nodes, 'MemberName="PlaybackActive"')
    print_node = h.one(nodes, 'MemberName="PrintString"')
    h.require(explicit_default(active_set, "PlaybackActive") == "false", "Stop must clear playback state")
    h.require_link(entry, "then", active_set, "execute", "Stop entry must clear playback")
    h.require_link(active_set, "then", print_node, "execute", "Stop must report only after state is clear")
    h.require('DefaultValue="[EDD] Linear playback stopped"' in print_node.text, "Stop diagnostic missing")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--start", type=Path, required=True)
    parser.add_argument("--update", type=Path, required=True)
    parser.add_argument("--stop", type=Path, required=True)
    args = parser.parse_args()
    h = helpers_module()
    assert_start(args.start, h)
    assert_update(args.update, h)
    assert_stop(args.stop, h)
    print("Linear playback contracts valid: absolute-time start, traversal, completion, and stop")


if __name__ == "__main__":
    main()
